"use client";

import { Plus, Trash2, Upload } from "lucide-react";
import type { WorksheetActivity, WorksheetBlock, WorksheetItem } from "@/lib/worksheet/types";

export function ActivityContentEditor({activity,updateActivity}:{activity:WorksheetActivity;updateActivity:(id:string,patch:Partial<WorksheetActivity>)=>void}){
  const items=activity.items||[];const blocks=activity.blocks||[];
  function setItems(next:WorksheetItem[]){updateActivity(activity.id,{items:next});}
  function setBlocks(next:WorksheetBlock[]){updateActivity(activity.id,{blocks:next});}
  function patchItem(index:number,patch:Partial<WorksheetItem>){setItems(items.map((item,itemIndex)=>itemIndex===index?{...item,...patch}:item));}
  function addBlock(type:"formula"|"tikz"|"table") { const id=crypto.randomUUID(); if(type==="table")setBlocks([...blocks,{id,type,headers:["Cột 1","Cột 2"],rows:[["",""]],expectedCells:{}}]);else setBlocks([...blocks,{id,type,content:type==="formula"?"\\frac{U}{I}=R":"\\begin{tikzpicture}\n\\draw (0,0)--(2,0);\n\\end{tikzpicture}"}]); }
  async function addImage(file?:File){if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>5*1024*1024)return;const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});setBlocks([...blocks,{id:crypto.randomUUID(),type:"image",assetId:crypto.randomUUID(),alt:file.name,dataUrl}]);}
  return <section className="rounded-[24px] border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Câu hỏi, lựa chọn và khối nội dung</h2><p className="text-sm text-slate-500">Chỉnh từng mục; công thức, bảng, hình và TikZ được lưu trong cùng hoạt động.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setItems([...items,{id:crypto.randomUUID(),prompt:"Câu hỏi mới",answer:""}])}><Plus size={15}/>Thêm câu</button><button className="btn-secondary" onClick={()=>addBlock("formula")}>Thêm công thức</button><button className="btn-secondary" onClick={()=>addBlock("table")}>Thêm bảng</button><button className="btn-secondary" onClick={()=>addBlock("tikz")}>Thêm TikZ</button><label className="btn-secondary cursor-pointer"><Upload size={15}/>Thêm ảnh<input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event)=>void addImage(event.target.files?.[0])}/></label></div></div>
    <div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map((item,index)=><article key={item.id} className="rounded-2xl border p-3"><label className="label">Nội dung {index+1}</label><textarea className="form-field mt-1 min-h-20" value={item.prompt} onChange={(event)=>patchItem(index,{prompt:event.target.value})}/><label className="label mt-2 block">Các lựa chọn, mỗi dòng một phương án</label><textarea className="form-field mt-1 min-h-20" value={(item.options||[]).map((option)=>`${option.label}. ${option.text}`).join("\n")} onChange={(event)=>patchItem(index,{options:event.target.value.split(/\r?\n/).filter(Boolean).map((line,optionIndex)=>({id:item.options?.[optionIndex]?.id||crypto.randomUUID(),label:String.fromCharCode(65+optionIndex),text:line.replace(/^[A-Z][.)]\s*/,"")}))})}/><label className="label mt-2 block">Đáp án</label><input className="form-field mt-1" value={item.answer||""} onChange={(event)=>patchItem(index,{answer:event.target.value})}/><label className="label mt-2 block">Giải thích</label><textarea className="form-field mt-1 min-h-16" value={item.explanation||""} onChange={(event)=>patchItem(index,{explanation:event.target.value})}/><button aria-label="Xóa câu" className="mt-2 text-red-600" onClick={()=>setItems(items.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={16}/></button></article>)}</div>
    <div className="mt-4 space-y-3">{blocks.map((block,index)=><article key={block.id} className="rounded-2xl border p-3"><div className="flex justify-between"><strong>{block.type==="formula"?"Công thức":block.type==="tikz"?"TikZ":block.type==="table"?"Bảng":block.type==="image"?"Hình ảnh":"Văn bản"}</strong><button aria-label="Xóa khối" className="text-red-600" onClick={()=>setBlocks(blocks.filter((_,blockIndex)=>blockIndex!==index))}><Trash2 size={16}/></button></div>{block.type==="formula"||block.type==="tikz"||block.type==="text"?<textarea className="form-field mt-2 min-h-24 font-mono" value={block.content} onChange={(event)=>setBlocks(blocks.map((item,blockIndex)=>blockIndex===index?{...block,content:event.target.value}:item))}/>:block.type==="table"?<textarea className="form-field mt-2 min-h-24" value={[block.headers,...block.rows].map((row)=>row.join("\t")).join("\n")} onChange={(event)=>{const rows=event.target.value.split(/\r?\n/).map((row)=>row.split("\t"));setBlocks(blocks.map((item,blockIndex)=>blockIndex===index?{...block,headers:rows[0]||[],rows:rows.slice(1)}:item));}}/>:<div className="mt-2 flex items-center gap-3"><span className="rounded-lg bg-slate-100 px-3 py-2 text-sm">{block.alt}</span><input className="form-field" value={block.alt} onChange={(event)=>setBlocks(blocks.map((item,blockIndex)=>blockIndex===index?{...block,alt:event.target.value}:item))}/></div>}</article>)}</div>
  </section>;
}

export function DifferentiationComparison({worksheet}:{worksheet:import("@/lib/worksheet/types").Worksheet}){const objective=worksheet.objectives?.[0]||worksheet.topic||"Mục tiêu chung";const titles=(level:"basic"|"standard"|"advanced")=>worksheet.activities.filter((item)=>item.level===level).map((item)=>item.title).filter(Boolean).join("; ")||"Chưa có";return <section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="font-black">Đối chiếu phân hóa</h2><div className="mt-3 overflow-x-auto"><table className="min-w-[760px] text-sm"><thead><tr><th className="p-2 text-left">Mục tiêu</th><th>Cơ bản</th><th>Tiêu chuẩn</th><th>Nâng cao</th></tr></thead><tbody><tr className="border-t align-top"><td className="p-2 font-bold">{objective}</td><td className="p-2">{titles("basic")}</td><td className="p-2">{titles("standard")}</td><td className="p-2">{titles("advanced")}</td></tr></tbody></table></div></section>}
