import type { GeneratedDocument } from "@/lib/types";
import type { SlideBlock } from "@/lib/lesson-slides/types";
import type { ActivityStep, LessonActivity, LessonPeriod, LessonPhase, LessonPlan, LessonPlanSourcePreview, LessonTimingResult, ObjectiveCoverage } from "@/lib/lesson-plan/types";

const uid=()=>typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();
const lines=(value:string)=>value.split(/\r?\n/).map((item)=>item.replace(/^#{1,5}\s*|^[-*•\d.)\s]+/,"").trim()).filter(Boolean);
export function stableLessonPlanHash(value:unknown){const text=typeof value==="string"?value:JSON.stringify(value);let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(36);}
const objective=(content:string,index:number)=>({id:`objective-${index+1}-${stableLessonPlanHash(content)}`,category:index===0?"knowledge" as const:index===1?"skill" as const:"competency" as const,content,evidence:"Sản phẩm và phản hồi của học sinh trong hoạt động liên quan."});

export function createLessonPlanDraft(input:Partial<LessonPlan>={}):LessonPlan{
  const created=input.metadata?.createdAt||now(); const topic=input.topic||"Chủ đề bài học";
  return {id:input.id||uid(),ownerId:input.ownerId,title:input.title||`Giáo án - ${topic}`,subject:input.subject||"",grade:input.grade||"",topic,textbookSeries:input.textbookSeries||"",lessonType:input.lessonType||"new_lesson",periodCount:Math.min(10,Math.max(1,input.periodCount||1)),minutesPerPeriod:input.minutesPerPeriod||45,objectives:input.objectives?.length?input.objectives:[objective("Trình bày được kiến thức trọng tâm của bài học.",0),objective("Vận dụng được kiến thức vào nhiệm vụ học tập phù hợp.",1)],preparation:input.preparation||{teacher:[],students:[],equipment:[],materials:[]},periods:input.periods||[],assessmentPlan:input.assessmentPlan||{methods:["observation","oral_question"]},differentiation:input.differentiation||{mode:"none"},homework:input.homework||{task:`Hoàn thành nhiệm vụ củng cố về ${topic}.`,purpose:"Củng cố kiến thức và chuẩn bị cho hoạt động tiếp theo.",expectedProduct:"Bài làm được giáo viên rà soát ở tiết sau.",nextLessonPreparation:"Xem lại ghi chép và chuẩn bị nội dung được giao."},linkedMaterials:input.linkedMaterials||{},requirements:input.requirements||[],keyKnowledge:input.keyKnowledge||[],methods:input.methods||["Kết hợp"],classProfile:input.classProfile||"",notes:input.notes||"",settings:{detailLevel:"standard",layout:"activities",defaultWorkMode:"mixed",sourceOnly:true,includeWarmUp:true,includeKnowledge:true,includePractice:true,includeApplication:true,includeConsolidation:true,includeHomework:true,includeAssessment:true,includeSlideGuide:false,includeWorksheet:false,includeRubric:false,includeExpectedProducts:true,...input.settings},metadata:{sourceType:"manual",createdAt:created,updatedAt:now(),version:"2.0",...input.metadata}};
}

const phaseLabels:Record<LessonPhase,string>={warm_up:"Khởi động",knowledge:"Hình thành kiến thức",practice:"Luyện tập",application:"Vận dụng",consolidation:"Củng cố",homework:"Bài tập về nhà",assessment:"Đánh giá",other:"Hoạt động khác"};
export function phaseLabel(value:LessonPhase){return phaseLabels[value];}
function outlinePhases(plan:LessonPlan):LessonPhase[]{const phases:LessonPhase[]=[];if(plan.settings.includeWarmUp)phases.push("warm_up");if(plan.settings.includeKnowledge)phases.push("knowledge");if(plan.settings.includePractice)phases.push("practice");if(plan.settings.includeApplication)phases.push("application");if(plan.settings.includeConsolidation)phases.push("consolidation");return phases.length?phases:["knowledge","practice"];}
function durationDistribution(total:number,count:number){const base=Math.floor(total/count);const values=Array.from({length:count},()=>base);for(let i=0;i<total-base*count;i++)values[i%count]+=1;return values;}
export function createLessonOutline(plan:LessonPlan):LessonPeriod[]{const phases=outlinePhases(plan);return Array.from({length:plan.periodCount},(_,periodIndex)=>{const durations=durationDistribution(plan.minutesPerPeriod,phases.length);return{id:`period-${periodIndex+1}-${stableLessonPlanHash(plan.id||plan.title)}`,periodNumber:periodIndex+1,title:`Tiết ${periodIndex+1}`,durationMinutes:plan.minutesPerPeriod,activities:phases.map((phase,index)=>createOutlineActivity(plan,phase,index+1,durations[index],periodIndex))};});}
function createOutlineActivity(plan:LessonPlan,phase:LessonPhase,order:number,duration:number,periodIndex:number):LessonActivity{const target=plan.objectives[(order+periodIndex-1)%Math.max(1,plan.objectives.length)];return{id:`activity-${periodIndex+1}-${order}-${stableLessonPlanHash(`${plan.id}-${phase}`)}`,order,phase,title:phaseLabel(phase),durationMinutes:duration,objectiveIds:target?[target.id]:[],content:"Chưa tạo nội dung chi tiết.",steps:[],teacherActions:[],studentActions:[],expectedProduct:expectedProduct(phase),assessmentMethod:phase==="consolidation"?"exit_ticket":"observation",assessmentEvidence:expectedProduct(phase),workMode:plan.settings.defaultWorkMode,differentiation:buildDifferentiation(plan,phase),generationStatus:"outline",teacherEdited:false};}
function expectedProduct(phase:LessonPhase){return({warm_up:"Câu trả lời hoặc dự đoán ban đầu",knowledge:"Ghi chép và kết luận kiến thức",practice:"Bài làm hoàn chỉnh",application:"Sản phẩm vận dụng",consolidation:"Phiếu trả lời ngắn",homework:"Bài làm ở nhà",assessment:"Minh chứng đánh giá",other:"Sản phẩm học tập"} as const)[phase];}
function buildDifferentiation(plan:LessonPlan,phase:LessonPhase){if(plan.differentiation?.mode==="none")return undefined;return{support:`Cung cấp gợi ý và một bước mẫu cho nhiệm vụ ${phaseLabel(phase).toLowerCase()}.`,standard:`Thực hiện nhiệm vụ theo yêu cầu chung về ${plan.topic}.`,advanced:`Mở rộng nhiệm vụ bằng giải thích, so sánh hoặc vận dụng trong tình huống mới.`,hint:"Nhắc lại kiến thức trọng tâm trước khi thực hiện."};}

function step(name:string,teacherAction:string,studentAction:string,output?:string):ActivityStep{return{id:uid(),name,teacherAction,studentAction,output};}
export function generateLessonActivityFallback(plan:LessonPlan,activity:LessonActivity):LessonActivity{const topic=plan.topic||"bài học";const product=activity.expectedProduct||expectedProduct(activity.phase);const steps=[step("Chuyển giao nhiệm vụ",`Nêu nhiệm vụ cụ thể về ${topic}, tiêu chí hoàn thành và thời gian thực hiện.`,`Đọc yêu cầu, xác định dữ kiện và nêu câu hỏi cần làm rõ.`,"Học sinh hiểu đúng nhiệm vụ."),step("Thực hiện nhiệm vụ",`Quan sát tiến độ, đặt câu hỏi gợi mở và hỗ trợ theo nhu cầu.`,`Thực hiện nhiệm vụ ${activity.workMode==="group"?"theo nhóm":"theo hình thức đã chọn"}; ghi lại lập luận hoặc kết quả.`,product),step("Báo cáo và thảo luận",`Mời học sinh trình bày; yêu cầu đối chiếu với tiêu chí và phản hồi có căn cứ.`,`Trình bày sản phẩm, trao đổi và điều chỉnh khi có minh chứng phù hợp.`,product),step("Kết luận và đánh giá",`Tổng hợp kết quả liên quan trực tiếp đến ${topic}; phản hồi theo minh chứng quan sát được.`,`Tự đối chiếu sản phẩm với tiêu chí và ghi lại điểm cần hoàn thiện.`,`Kết luận và phản hồi học tập.`)];return{...activity,content:`Tổ chức ${phaseLabel(activity.phase).toLowerCase()} nhằm giúp học sinh thực hiện mục tiêu đã chọn về ${topic}.`,steps,teacherActions:steps,studentActions:steps,expectedProduct:product,assessmentCriteria:`Đúng kiến thức, trình bày rõ và hoàn thành sản phẩm trong ${activity.durationMinutes} phút.`,assessmentEvidence:product,feedbackMethod:"Phản hồi trực tiếp theo tiêu chí và cho học sinh tự điều chỉnh.",generationStatus:"ready",generationError:undefined,teacherEdited:false};}

export function parseLessonActivityResponse(raw:string,plan:LessonPlan,base:LessonActivity):LessonActivity{try{const cleaned=raw.replace(/^```(?:json)?/i,"").replace(/```$/,"" ).trim();const value=JSON.parse(cleaned) as Partial<LessonActivity>&{steps?:Partial<ActivityStep>[]};if(!value.content||!Array.isArray(value.steps)||!value.steps.length)throw new Error("invalid");const steps=value.steps.map((item,index)=>({id:item.id||`${base.id}-step-${index+1}`,name:item.name||`Bước ${index+1}`,teacherAction:item.teacherAction||"",studentAction:item.studentAction||"",output:item.output}));return{...base,...value,id:base.id,order:base.order,objectiveIds:base.objectiveIds,steps,teacherActions:steps,studentActions:steps,generationStatus:"ready",generationError:undefined,teacherEdited:false};}catch{return generateLessonActivityFallback(plan,base);}}

export function validateLessonTiming(plan:LessonPlan):LessonTimingResult[]{return plan.periods.map((period)=>{const actual=period.activities.filter((item)=>item.phase!=="homework").reduce((sum,item)=>sum+Math.max(0,Number(item.durationMinutes)||0),0);const difference=actual-period.durationMinutes;const status=period.activities.some((item)=>item.durationMinutes<=0)?"adjust":difference===0?"match":difference<0?"under":"over";const message=status==="match"?`Tiết ${period.periodNumber} khớp thời lượng ${period.durationMinutes} phút.`:status==="under"?`Tiết ${period.periodNumber} còn thiếu ${Math.abs(difference)} phút.`:status==="over"?`Tiết ${period.periodNumber} có tổng thời lượng ${actual} phút, vượt ${difference} phút.`:`Tiết ${period.periodNumber} có hoạt động chưa có thời lượng hợp lệ.`;return{periodId:period.id,periodNumber:period.periodNumber,configured:period.durationMinutes,actual,difference,status,message};});}
export function redistributePeriod(period:LessonPeriod):LessonPeriod{const counted=period.activities.filter((item)=>item.phase!=="homework");const durations=durationDistribution(period.durationMinutes,Math.max(1,counted.length));let index=0;return{...period,activities:period.activities.map((item)=>item.phase==="homework"?item:{...item,durationMinutes:durations[index++]})};}
export function objectiveCoverage(plan:LessonPlan):ObjectiveCoverage[]{return plan.objectives.map((item)=>{const activities=plan.periods.flatMap((period)=>period.activities).filter((activity)=>activity.objectiveIds.includes(item.id));const evidence=activities.map((activity)=>activity.assessmentEvidence||"").filter(Boolean);return{objectiveId:item.id,objective:item.content,activityTitles:activities.map((activity)=>activity.title),evidence,status:!activities.length?"missing_activity":!evidence.length?"missing_evidence":activities.some((activity)=>activity.generationStatus!=="ready")?"needs_confirmation":"covered"};});}
export function validateLessonPlan(plan:LessonPlan){const errors:string[]=[];const warnings:string[]=[];if(plan.periodCount<1||plan.periodCount>10)errors.push("Số tiết phải từ 1 đến 10.");if(!plan.periods.length)errors.push("Giáo án chưa có tiến trình.");validateLessonTiming(plan).forEach((item)=>{if(item.status==="over"||item.status==="adjust")errors.push(item.message);else if(item.status==="under")warnings.push(item.message);});objectiveCoverage(plan).forEach((item)=>{if(item.status==="missing_activity")errors.push(`Mục tiêu chưa có hoạt động: ${item.objective}`);if(item.status==="missing_evidence")warnings.push(`Mục tiêu chưa có minh chứng: ${item.objective}`);});for(const activity of plan.periods.flatMap((period)=>period.activities)){if(!activity.title.trim()||!activity.objectiveIds.length)errors.push(`Hoạt động ${activity.order} thiếu tiêu đề hoặc mục tiêu.`);if(activity.generationStatus==="ready"&&(!activity.steps.length||activity.steps.some((item)=>!item.teacherAction||!item.studentAction)))errors.push(`${activity.title} thiếu hành động cụ thể của giáo viên hoặc học sinh.`);}return{valid:errors.length===0,errors,warnings,timing:validateLessonTiming(plan),coverage:objectiveCoverage(plan)};}

function slideText(block:SlideBlock){if(block.teacherOnly)return"";if(block.type==="bullets")return block.content.join("; ");if(block.type==="table")return[block.headers.join(" | "),...block.rows.map((row)=>row.join(" | "))].join("\n");if(block.type==="process")return block.steps.join(" → ");if(block.type==="formula")return block.latex;if(block.type==="tikz")return block.tikz;return block.content;}
export function lessonSourceFromDocument(document:GeneratedDocument):LessonPlanSourcePreview{
  if(document.lessonPlan)return{title:document.title,sourceType:"previous_lesson_plan",sourceDocumentId:document.id,subject:document.lessonPlan.subject,grade:document.lessonPlan.grade,topic:document.lessonPlan.topic,objectives:document.lessonPlan.objectives.map((item)=>item.content),concepts:document.lessonPlan.keyKnowledge||[],examples:[],exercises:[],text:lessonPlanToText(document.lessonPlan,"full"),confirmed:true,warnings:[]};
  if(document.slideDeck){const slides=document.slideDeck.slides.filter((item)=>!item.hidden);const content=slides.flatMap((slide)=>slide.blocks.map(slideText)).filter(Boolean);return{title:document.title,sourceType:"slide_deck",sourceDocumentId:document.id,subject:document.slideDeck.subject,grade:document.slideDeck.grade,topic:document.slideDeck.topic,objectives:slides.filter((item)=>item.type==="objectives").flatMap((item)=>item.blocks.map(slideText)).filter(Boolean),concepts:content.slice(0,24),examples:slides.filter((item)=>item.type==="example").flatMap((item)=>item.blocks.map(slideText)).filter(Boolean),exercises:slides.filter((item)=>["practice","question"].includes(item.type)).flatMap((item)=>item.blocks.map(slideText)).filter(Boolean),text:content.join("\n"),confirmed:true,warnings:[]};}
  if(document.recognitionDraft){const confirmed=document.recognitionDraft.reviewStatus==="confirmed";const content=document.recognitionDraft.pages.flatMap((page)=>page.blocks).filter((block)=>block.reviewed&&!block.excluded).map((block)=>block.text).filter(Boolean);return{title:document.title,sourceType:"document",sourceDocumentId:document.id,objectives:[],concepts:content.slice(0,24),examples:[],exercises:[],text:content.join("\n"),confirmed,warnings:confirmed?[]:["Tài liệu nhận dạng chưa được giáo viên xác nhận."]};}
  const content=lines(document.content);const sourceType=document.type==="lesson-plan"?"previous_lesson_plan":document.worksheet?"worksheet":document.examSolutionSet?"solution":document.type==="exam"?"exam":document.type==="rubric"?"rubric":"document";return{title:document.title,sourceType,sourceDocumentId:document.id,subject:document.generationMeta?.subject||document.examMeta?.subject,grade:document.generationMeta?.grade||document.examMeta?.grade,topic:document.generationMeta?.topic||document.examMeta?.topic,objectives:content.filter((item)=>/mục tiêu|yêu cầu cần đạt/i.test(item)).slice(0,8),concepts:content.slice(0,24),examples:content.filter((item)=>/ví dụ|bài mẫu/i.test(item)).slice(0,8),exercises:content.filter((item)=>/câu \d+|bài tập|luyện tập/i.test(item)).slice(0,12),text:document.content,confirmed:true,warnings:[]};
}

export type LessonExportFormat="short"|"full"|"teacher_student_table"|"timeline"|"appendices";
export function lessonPlanToText(plan:LessonPlan,format:LessonExportFormat="full"){
  const rows=[plan.title,`Môn: ${plan.subject||""} | Lớp: ${plan.grade||""}`,`Chủ đề: ${plan.topic||""} | Số tiết: ${plan.periodCount} | ${plan.minutesPerPeriod} phút/tiết`,"","I. MỤC TIÊU",...plan.objectives.map((item,index)=>`${index+1}. ${item.content}${item.evidence?` — Minh chứng: ${item.evidence}`:""}`),"","II. CHUẨN BỊ",`Giáo viên: ${plan.preparation.teacher.join("; ")||"Giáo viên bổ sung"}`,`Học sinh: ${plan.preparation.students.join("; ")||"Học sinh chuẩn bị theo hướng dẫn"}`,`Thiết bị và học liệu: ${[...plan.preparation.equipment,...plan.preparation.materials].join("; ")||"Theo điều kiện lớp học"}`,"","III. TIẾN TRÌNH DẠY HỌC"];
  for(const period of plan.periods){
    rows.push("",`TIẾT ${period.periodNumber}. ${period.title||""} (${period.durationMinutes} PHÚT)`);
    if(format==="timeline"){
      rows.push("| Giai đoạn | Hoạt động | Mục tiêu | Sản phẩm | Thời gian |","|---|---|---|---|---:|");
      for(const activity of period.activities)rows.push(`| ${phaseLabel(activity.phase)} | ${activity.title} | ${activity.objectiveIds.map((id)=>plan.objectives.find((item)=>item.id===id)?.content).filter(Boolean).join("; ")} | ${activity.expectedProduct||""} | ${activity.durationMinutes} phút |`);
      continue;
    }
    if(format==="teacher_student_table"){
      rows.push("| Hoạt động của giáo viên | Hoạt động của học sinh | Sản phẩm | Đánh giá | Thời gian |","|---|---|---|---|---:|");
      for(const activity of period.activities)rows.push(`| ${activity.steps.map((item)=>item.teacherAction).join("; ")} | ${activity.steps.map((item)=>item.studentAction).join("; ")} | ${activity.expectedProduct||""} | ${activity.assessmentEvidence||""} | ${activity.durationMinutes} phút |`);
      continue;
    }
    for(const activity of period.activities){
      rows.push("",`HOẠT ĐỘNG ${activity.order}. ${activity.title} (${activity.durationMinutes} phút)`,`Giai đoạn: ${phaseLabel(activity.phase)} | Hình thức: ${activity.workMode}`,`Mục tiêu: ${activity.objectiveIds.map((id)=>plan.objectives.find((item)=>item.id===id)?.content).filter(Boolean).join("; ")}`,format==="short"?activity.content:`Nội dung: ${activity.content}`);
      if(format!=="short")activity.steps.forEach((item,index)=>rows.push(`${index+1}. ${item.name}`,`- Giáo viên: ${item.teacherAction}`,`- Học sinh: ${item.studentAction}`,item.output?`- Sản phẩm: ${item.output}`:""));
      rows.push(`Sản phẩm dự kiến: ${activity.expectedProduct||"Giáo viên bổ sung"}`,`Đánh giá/minh chứng: ${activity.assessmentEvidence||"Giáo viên bổ sung"}`);
      if(format!=="short")rows.push(`Phương pháp đánh giá: ${activity.assessmentMethod||"Giáo viên lựa chọn"}`,`Tiêu chí: ${activity.assessmentCriteria||"Giáo viên bổ sung"}`,`Phản hồi: ${activity.feedbackMethod||"Phản hồi trực tiếp"}`,activity.teacherNote?`Ghi chú giáo viên: ${activity.teacherNote}`:"");
      if(format!=="short"&&activity.differentiation)rows.push(`Phân hóa hỗ trợ: ${activity.differentiation.support||""}`,`Nhiệm vụ nâng cao: ${activity.differentiation.advanced||""}`);
      if(format!=="short"&&activity.materials?.length)rows.push(`Tài liệu sử dụng: ${activity.materials.map((item)=>item.title).join("; ")}`);
    }
  }
  if(plan.homework)rows.push("","IV. BÀI TẬP VỀ NHÀ",`Nhiệm vụ: ${plan.homework.task}`,`Mục đích: ${plan.homework.purpose||""}`,`Sản phẩm: ${plan.homework.expectedProduct||""}`);if(format==="appendices")rows.push("","PHỤ LỤC TÀI LIỆU",...Object.entries(plan.linkedMaterials||{}).filter(([,ids])=>ids?.length).map(([key,ids])=>`${key}: ${(ids||[]).join(", ")}`));rows.push("","Nội dung là bản nháp hỗ trợ giáo viên. Giáo viên cần kiểm tra, chỉnh sửa theo lớp học và yêu cầu chuyên môn trước khi sử dụng.");return rows.filter((item)=>item!==undefined).join("\n");
}
export function normalizeLessonPlan(plan:LessonPlan):LessonPlan{const periodCount=Math.min(10,Math.max(1,Number(plan.periodCount)||1));return{...plan,periodCount,minutesPerPeriod:Math.max(1,Number(plan.minutesPerPeriod)||45,0),periods:plan.periods.slice(0,periodCount).map((period,index)=>({...period,periodNumber:index+1,durationMinutes:Math.max(1,Number(period.durationMinutes)||plan.minutesPerPeriod),activities:period.activities.map((activity,activityIndex)=>({...activity,order:activityIndex+1,durationMinutes:Math.max(0,Number(activity.durationMinutes)||0,0),objectiveIds:activity.objectiveIds||[],steps:activity.steps||activity.teacherActions||[],teacherActions:activity.steps||activity.teacherActions||[],studentActions:activity.steps||activity.studentActions||[]}))})),metadata:{...plan.metadata,updatedAt:now()}};}
export function lessonPlanToDocument(plan:LessonPlan,format:LessonExportFormat="full"):GeneratedDocument{const normalized=normalizeLessonPlan(plan);const validation=validateLessonPlan(normalized);normalized.metadata.validationStatus=validation.valid?"ready":"warning";return{id:normalized.id||uid(),title:normalized.title,type:"lesson-plan",content:lessonPlanToText(normalized,format),createdAt:normalized.metadata.createdAt,folder:"Giáo án",lessonPlan:normalized,generationMeta:{subject:normalized.subject,grade:normalized.grade,topic:normalized.topic,source:normalized.metadata.sourceType,exportStatus:validation.valid?"ready":"warning"}};}
export function canAccessLessonPlan(plan:LessonPlan,userId:string,isAdmin=false){return isAdmin||!plan.ownerId||plan.ownerId===userId;}
