"use client";

import Image from "next/image";
import { Check, Code2, Download, Eye, GitCompare, Move, RotateCcw, ShieldCheck, Undo2 } from "lucide-react";
import { useMemo, useState } from "react";
import { compareDiagramModels } from "@/lib/tikz/comparison";
import { applyManualTikzCode, applyStructuredEdit } from "@/lib/tikz/editor";
import { proposeLayoutRepairs } from "@/lib/tikz/layout-repair";
import { objectTypeLabel } from "@/lib/tikz/model";
import { parseNaturalDiagramEdit } from "@/lib/tikz/natural-edits";
import { renderTikzDraftToSvg, svgDataUrl } from "@/lib/tikz/render-svg";
import { repairTikzSyntax } from "@/lib/tikz/syntax";
import type { DiagramObject, StructuredEditOperation, TikzDiagramDraft } from "@/lib/tikz/types";
import { qualitySummary, validateTikzDraft } from "@/lib/tikz/validation";

type Tab = "review" | "objects" | "relationships" | "code" | "errors" | "compare";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "review", label: "Xem hình" }, { id: "objects", label: "Đối tượng" }, { id: "relationships", label: "Quan hệ" }, { id: "code", label: "Mã TikZ" }, { id: "errors", label: "Lỗi" }, { id: "compare", label: "So sánh" }];
const anchors: NonNullable<DiagramObject["anchor"]>[] = ["above", "below", "left", "right", "above left", "above right", "below left", "below right"];

export function TikzReviewWorkspace({ draft, sourceUrl, onChange }: { draft: TikzDiagramDraft; sourceUrl?: string; onChange: (draft: TikzDiagramDraft) => void }) {
  const [tab, setTab] = useState<Tab>("review"); const [code, setCode] = useState(draft.tikz.snippet); const [command, setCommand] = useState(""); const [proposal, setProposal] = useState<{ operations: StructuredEditOperation[]; warnings: string[] }>();
  const [zoom, setZoom] = useState(1); const [opacity, setOpacity] = useState(50); const [overlay, setOverlay] = useState(false); const [showBoxes, setShowBoxes] = useState(false); const [showLabels, setShowLabels] = useState(true); const [showHidden, setShowHidden] = useState(true); const [initial] = useState(draft);
  const rendered = useMemo(() => renderTikzDraftToSvg(draft, { showObjectBoxes: showBoxes, showLabels, showHiddenEdges: showHidden }), [draft, showBoxes, showLabels, showHidden]);
  const previewUrl = useMemo(() => svgDataUrl(rendered.svg), [rendered.svg]); const comparison = useMemo(() => compareDiagramModels(initial, draft), [initial, draft]); const layoutRepairs = useMemo(() => proposeLayoutRepairs(draft), [draft]);

  function edit(operation: StructuredEditOperation) { const next = applyStructuredEdit(draft, operation); setCode(next.tikz.snippet); onChange(next); }
  function applyCode() { onChange(applyManualTikzCode(draft, code)); }
  function confirmClassification() { const next = structuredClone(draft); next.classification.teacherConfirmed = true; next.validation = validateTikzDraft(next); next.quality = qualitySummary(next); next.status = next.validation.valid ? "confirmed" : "needs_review"; next.metadata.updatedAt = new Date().toISOString(); onChange(next); }
  async function download(format: "svg" | "png" | "zip") { const response = await fetch("/api/tikz/render", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draft, format, fileName: draft.source.sourceName || "soan-lab-tikz" }) }); if (!response.ok) return; const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `soan-lab-tikz.${format}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function applyProposal() { if (!proposal) return; let next = draft; for (const operation of proposal.operations) next = applyStructuredEdit(next, operation); setCode(next.tikz.snippet); onChange(next); setProposal(undefined); setCommand(""); }

  const qualityItems = [{ label: "Phân loại hình", value: draft.quality.classification }, { label: "Đầy đủ đối tượng", value: draft.quality.objectCoverage }, { label: "Đầy đủ nhãn", value: draft.quality.labelCoverage }, { label: "Quan hệ hình học", value: draft.quality.relationships }, { label: "Kiểm tra mã", value: draft.quality.compilation }, { label: "Bố cục", value: draft.quality.layout }];
  return <div className="space-y-4">
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-slate-950">Không gian rà soát TikZ</p><p className="text-sm text-slate-600">Kiểm tra ảnh gốc, đối tượng, quan hệ và mã trước khi xác nhận.</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${draft.quality.overall === "unreliable" ? "bg-red-100 text-red-700" : draft.quality.overall === "needs_review" ? "bg-amber-100 text-amber-800" : "bg-blue-100 text-blue-700"}`}>{draft.quality.overall === "ready" ? "Sẵn sàng sử dụng" : draft.quality.overall === "warning" ? "Có cảnh báo" : draft.quality.overall === "needs_review" ? "Cần rà soát" : "Không thể dựng chắc chắn"}</span></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{qualityItems.map((item) => <div key={item.label} className="rounded-xl bg-white p-3"><div className="flex justify-between text-xs font-bold text-slate-600"><span>{item.label}</span><span>{item.value}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${item.value}%` }} /></div></div>)}</div>
      {!draft.compilation.available ? <p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900">Preview SVG/PNG được dựng an toàn từ mô hình đối tượng. Máy chủ hiện chưa có trình biên dịch TeX, vì vậy SOẠN LAB không xem preview này là bằng chứng mã đã biên dịch hoặc hình đã đúng hoàn toàn.</p> : null}
    </div>
    <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`shrink-0 rounded-xl px-3 py-2 text-sm font-bold ${tab === item.id ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-700"}`}>{item.label}</button>)}</div>

    {tab === "review" ? <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-3 text-xs font-bold text-slate-700"><label>Thu phóng <input className="ml-2 align-middle" type="range" min="70" max="160" value={zoom * 100} onChange={(event) => setZoom(Number(event.target.value) / 100)} /></label>{sourceUrl ? <label><input type="checkbox" checked={overlay} onChange={(event) => setOverlay(event.target.checked)} /> <span className="ml-1">Chồng ảnh gốc</span></label> : null}{overlay ? <label>Độ mờ <input className="ml-2 align-middle" type="range" min="10" max="90" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} /></label> : null}<label><input type="checkbox" checked={showBoxes} onChange={(event) => setShowBoxes(event.target.checked)} /> <span className="ml-1">Khung đối tượng</span></label><label><input type="checkbox" checked={showLabels} onChange={(event) => setShowLabels(event.target.checked)} /> <span className="ml-1">Nhãn</span></label><label><input type="checkbox" checked={showHidden} onChange={(event) => setShowHidden(event.target.checked)} /> <span className="ml-1">Cạnh khuất</span></label></div>
      <div className={`grid gap-3 ${sourceUrl && !overlay ? "lg:grid-cols-2" : ""}`}>{sourceUrl && !overlay ? <PreviewCard title="Ảnh gốc" url={sourceUrl} zoom={zoom} /> : null}<div className="relative min-h-80 overflow-auto rounded-2xl border bg-[#fffdf8]">{sourceUrl && overlay ? <div className="absolute inset-0"><Image src={sourceUrl} alt="Ảnh nguồn" fill className="object-contain" unoptimized /></div> : null}<div className="absolute inset-0" style={{ opacity: overlay ? opacity / 100 : 1, transform: `scale(${zoom})` }}><Image src={previewUrl} alt="Bản xem trước semantic" fill className="object-contain" unoptimized /></div></div></div>
      <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" onClick={() => void download("svg")}><Download size={15} />Tải SVG</button><button type="button" className="btn-secondary" onClick={() => void download("png")}><Download size={15} />Tải PNG</button><button type="button" className="btn-secondary" onClick={() => void download("zip")}><Download size={15} />Tải gói ZIP</button></div>
    </div> : null}

    {tab === "objects" ? <div className="space-y-3">{draft.objects.length ? draft.objects.map((object) => <article key={object.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{objectTypeLabel(object.type)} {object.label ? `· ${object.label}` : ""}</strong><span className="text-xs text-slate-500">{object.confidence === "high" ? "Tin cậy cao" : object.confidence === "medium" ? "Cần kiểm tra" : "Tin cậy thấp"}</span></div><div className="mt-3 flex flex-wrap gap-2">{object.type === "point" ? <><input aria-label="Tên điểm" className="form-field max-w-28" value={object.label || ""} onChange={(event) => edit({ type: "rename_point", objectId: object.id, label: event.target.value })}/>{object.position ? <><input aria-label="Tọa độ x" type="number" step="0.1" className="form-field max-w-24" value={object.position.x} onChange={(event) => edit({ type: "move_object", objectId: object.id, position: { x: Number(event.target.value), y: object.position!.y } })}/><input aria-label="Tọa độ y" type="number" step="0.1" className="form-field max-w-24" value={object.position.y} onChange={(event) => edit({ type: "move_object", objectId: object.id, position: { x: object.position!.x, y: Number(event.target.value) } })}/></> : null}</> : null}{["segment", "line", "ray", "vector"].includes(object.type) ? <select className="form-field max-w-36" value={object.style || "solid"} onChange={(event) => edit({ type: "change_line_style", objectId: object.id, style: event.target.value as "solid" | "dashed" | "dotted" })}><option value="solid">Nét liền</option><option value="dashed">Nét đứt</option><option value="dotted">Nét chấm</option></select> : null}{object.label ? <select className="form-field max-w-40" value={object.anchor || "above right"} onChange={(event) => edit({ type: "move_label", objectId: object.id, anchor: event.target.value as DiagramObject["anchor"] })}>{anchors.map((anchor) => <option key={anchor}>{anchor}</option>)}</select> : null}</div></article>) : <p className="empty-state">Chưa có đối tượng semantic đủ rõ. Thầy cô nên giữ ảnh gốc.</p>}
      {layoutRepairs.length ? <div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4"><p className="font-bold">Đề xuất tách nhãn chồng nhau</p>{layoutRepairs.map((repair) => <button type="button" className="btn-secondary mt-2 mr-2" key={repair.objectId} onClick={() => edit({ type: "move_label", objectId: repair.objectId, anchor: repair.to })}><Move size={14} />{repair.reason}</button>)}</div> : null}
    </div> : null}

    {tab === "relationships" ? <div className="space-y-2">{draft.relationships.length ? draft.relationships.map((relationship) => <div key={relationship.id} className="rounded-xl border border-slate-200 p-3"><strong>{relationship.type}</strong><p className="mt-1 text-xs text-slate-500">{relationship.objectIds.join(" · ")}</p><p className="text-xs text-slate-600">{relationship.teacherConfirmed ? "Giáo viên đã xác nhận" : relationship.confidence === "low" ? "Cần giáo viên xác nhận" : "Được nhận diện tự động"}</p></div>) : <p className="empty-state">Chưa có quan hệ hình học được nhận diện chắc chắn.</p>}<button type="button" className="btn-secondary" onClick={confirmClassification}><Check size={15} />Xác nhận phân loại và quan hệ đã kiểm tra</button></div> : null}

    {tab === "code" ? <div className="space-y-3"><div className="grid grid-cols-[auto_1fr] overflow-hidden rounded-2xl border bg-slate-950 text-xs text-slate-100"><pre className="select-none border-r border-slate-700 px-3 py-4 text-right text-slate-500">{code.split(/\r?\n/).map((_, index) => index + 1).join("\n")}</pre><textarea aria-label="Mã TikZ" className="min-h-96 resize-y bg-transparent p-4 font-mono outline-none" value={code} onChange={(event) => setCode(event.target.value)} /></div>{draft.tikz.semanticSync === "partially_detached" ? <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Mã đã được chỉnh sửa thủ công. Một số điều khiển trực quan có thể không còn đồng bộ hoàn toàn.</p> : null}<div className="flex flex-wrap gap-2"><button type="button" className="btn-primary" onClick={applyCode}><Code2 size={15} />Kiểm tra và giữ bản sửa</button><button type="button" className="btn-secondary" onClick={() => { const fixed = repairTikzSyntax(code); setCode(fixed.code); }}><ShieldCheck size={15} />Xem sửa lỗi an toàn</button><button type="button" className="btn-secondary" onClick={() => setCode(draft.tikz.generatedSnippet)}><RotateCcw size={15} />Khôi phục bản dựng</button><button type="button" className="btn-secondary" onClick={() => navigator.clipboard.writeText(code)}><Code2 size={15} />Sao chép</button></div></div> : null}

    {tab === "errors" ? <div className="space-y-3">{draft.compilation.errors.length ? draft.compilation.errors.map((error, index) => <div key={`${error.code}-${index}`} className="rounded-xl border border-red-200 bg-red-50 p-3"><strong>{error.message}</strong>{error.line ? <p className="text-sm">Dòng {error.line}</p> : null}{error.suggestion ? <p className="text-sm text-red-800">Đề xuất: {error.suggestion}</p> : null}</div>) : <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Không phát hiện lỗi cú pháp hoặc lệnh nguy hiểm trong kiểm tra tĩnh. Đây chưa phải kết quả biên dịch TeX.</p>}<div className="rounded-2xl border p-4"><p className="font-bold">Yêu cầu chỉnh hình</p><textarea className="form-field mt-2 min-h-24" value={command} onChange={(event) => setCommand(event.target.value)} placeholder="Ví dụ: Đổi cạnh AC thành nét đứt."/><button type="button" className="btn-secondary mt-2" onClick={() => setProposal(parseNaturalDiagramEdit(command, draft))}>Tạo đề xuất</button>{proposal ? <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Thay đổi đề xuất</p>{proposal.operations.map((operation, index) => <p key={index}>• {operation.type}</p>)}{proposal.warnings.map((warning) => <p key={warning} className="text-amber-700">• {warning}</p>)}{proposal.operations.length ? <button type="button" className="btn-primary mt-2" onClick={applyProposal}><Check size={15} />Xác nhận áp dụng</button> : null}</div> : null}</div></div> : null}

    {tab === "compare" ? <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Bao phủ đối tượng" value={comparison.objectCoverage}/><Metric label="Bao phủ nhãn" value={comparison.labelCoverage}/><Metric label="Quan hệ cấu trúc" value={comparison.structuralSimilarity}/><Metric label="Tỉ lệ bố cục" value={comparison.sourceRenderAlignment}/></div><p className={`rounded-xl p-3 text-sm font-bold ${comparison.status === "near_match" ? "bg-emerald-50 text-emerald-800" : comparison.status === "needs_review" ? "bg-amber-50 text-amber-900" : "bg-red-50 text-red-800"}`}>{comparison.status === "near_match" ? "Gần khớp theo mô hình semantic" : comparison.status === "needs_review" ? "Cần kiểm tra" : "Không khớp"}</p>{comparison.suspiciousDifferences.map((item) => <p key={item} className="text-sm text-amber-800">• {item}</p>)}<p className="text-xs leading-5 text-slate-500">So sánh này dùng đối tượng, nhãn, quan hệ và tỉ lệ bố cục; không phải đánh giá giống pixel và không chứng minh hình học đã đúng.</p></div> : null}
    <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={!draft.teacherEdits.length} onClick={() => { const latest = draft.teacherEdits.at(-1); if (latest?.source === "code" && typeof latest.before === "string") onChange(applyManualTikzCode({ ...draft, teacherEdits: draft.teacherEdits.slice(0, -1) }, latest.before)); }}><Undo2 size={15} />Hoàn tác sửa mã gần nhất</button><button type="button" className="btn-secondary" onClick={() => setTab("review")}><Eye size={15} />Xem preview</button><button type="button" className="btn-secondary" onClick={() => setTab("compare")}><GitCompare size={15} />So sánh</button></div>
  </div>;
}

function PreviewCard({ title, url, zoom }: { title: string; url: string; zoom: number }) { return <div className="rounded-2xl border bg-white p-3"><p className="mb-2 text-xs font-black text-slate-600">{title}</p><div className="relative min-h-80 overflow-auto"><div className="absolute inset-0" style={{ transform: `scale(${zoom})` }}><Image src={url} alt={title} fill className="object-contain" unoptimized /></div></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border p-3"><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${value}%` }}/></div></div>; }
