"use client";

import Image from "next/image";
import { Check, Code2, Download, Eye, FileInput, GitCompare, Move, RotateCcw, ShieldCheck, Undo2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { listCloudDocuments, saveDocumentToCloud } from "@/lib/data/documents-store";
import { getHistory, saveDocument } from "@/lib/history";
import { getQuestions, saveQuestions } from "@/lib/question-bank";
import { normalizeQuestionItems, toLegacyQuestion } from "@/lib/question-bank-core/normalize";
import { compareDiagramModels } from "@/lib/tikz/comparison";
import { insertConfirmedDiagram, insertDiagramIntoQuestion, listDiagramInsertionTargets } from "@/lib/tikz/document-insertion";
import { applyManualTikzCode, applyStructuredEdit } from "@/lib/tikz/editor";
import { proposeLayoutRepairs } from "@/lib/tikz/layout-repair";
import { objectTypeLabel } from "@/lib/tikz/model";
import { parseNaturalDiagramEdit } from "@/lib/tikz/natural-edits";
import { uploadPrivateTikzAsset } from "@/lib/tikz/private-assets";
import { buildTikzReviewQueue, createConfirmedDiagramAsset, decideReviewItem, evaluateTikzReadiness } from "@/lib/tikz/readiness";
import { renderTikzDraftToSvg, svgDataUrl } from "@/lib/tikz/render-svg";
import { repairTikzSyntax } from "@/lib/tikz/syntax";
import type { DiagramObject, StructuredEditOperation, TikzDiagramDraft, TikzReviewItem } from "@/lib/tikz/types";
import type { GeneratedDocument } from "@/lib/types";
import { qualitySummary, validateTikzDraft } from "@/lib/tikz/validation";

type Tab = "review" | "objects" | "relationships" | "code" | "errors" | "compare";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "review", label: "Xem hình" }, { id: "objects", label: "Đối tượng" }, { id: "relationships", label: "Quan hệ" }, { id: "code", label: "Mã TikZ" }, { id: "errors", label: "Lỗi" }, { id: "compare", label: "So sánh" }];
const anchors: NonNullable<DiagramObject["anchor"]>[] = ["above", "below", "left", "right", "above left", "above right", "below left", "below right"];

export function TikzReviewWorkspace({ draft, sourceUrl, onChange }: { draft: TikzDiagramDraft; sourceUrl?: string; onChange: (draft: TikzDiagramDraft) => void }) {
  const [tab, setTab] = useState<Tab>("review"); const [code, setCode] = useState(draft.tikz.snippet); const [command, setCommand] = useState(""); const [proposal, setProposal] = useState<{ operations: StructuredEditOperation[]; warnings: string[] }>();
  const [zoom, setZoom] = useState(1); const [opacity, setOpacity] = useState(50); const [overlay, setOverlay] = useState(false); const [showBoxes, setShowBoxes] = useState(false); const [showLabels, setShowLabels] = useState(true); const [showHidden, setShowHidden] = useState(true); const [initial] = useState(draft);
  const [background, setBackground] = useState<"transparent" | "white">("white"); const [lineWeight, setLineWeight] = useState<"thin" | "standard" | "bold">("standard"); const [pngScale, setPngScale] = useState<1 | 2 | 4>(2);
  const [documents, setDocuments] = useState<GeneratedDocument[]>([]); const [usingCloudDocuments, setUsingCloudDocuments] = useState(false); const [targetDocumentId, setTargetDocumentId] = useState(""); const [targetLocationId, setTargetLocationId] = useState(""); const [selectedObjectId, setSelectedObjectId] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(false); const [compiler, setCompiler] = useState({ available: false, supportsPdf: false, supportsSvg: false });
  const [questions, setQuestions] = useState(() => normalizeQuestionItems(getQuestions()).filter((item) => item.scope === "user"));
  const rendered = useMemo(() => renderTikzDraftToSvg(draft, { showObjectBoxes: showBoxes, showLabels, showHiddenEdges: showHidden, background, lineWeight }), [draft, showBoxes, showLabels, showHidden, background, lineWeight]);
  const previewUrl = useMemo(() => svgDataUrl(rendered.svg), [rendered.svg]); const comparison = useMemo(() => compareDiagramModels(initial, draft), [initial, draft]); const layoutRepairs = useMemo(() => proposeLayoutRepairs(draft), [draft]); const reviewQueue = useMemo(() => buildTikzReviewQueue(draft), [draft]); const readiness = useMemo(() => evaluateTikzReadiness(draft), [draft]);
  const targetDocument = documents.find((item) => item.id === targetDocumentId); const insertionTargets = useMemo(() => targetDocument ? listDiagramInsertionTargets(targetDocument) : [], [targetDocument]); const selectedObject = draft.objects.find((item) => item.id === selectedObjectId);

  useEffect(() => { queueMicrotask(async () => { const cloud = await listCloudDocuments(); setUsingCloudDocuments(cloud !== null); setDocuments((cloud || getHistory()).filter((item) => ["exam", "worksheet", "lesson-plan", "lesson-slides", "review-pack", "answer-key"].includes(item.type))); const response = await fetch("/api/tikz/compiler").catch(() => null); if (response?.ok) { const data = await response.json() as { available?: boolean; supportsPdf?: boolean; supportsSvg?: boolean }; setCompiler({ available: Boolean(data.available), supportsPdf: Boolean(data.supportsPdf), supportsSvg: Boolean(data.supportsSvg) }); } }); }, []);

  function edit(operation: StructuredEditOperation) { const next = applyStructuredEdit(draft, operation); setCode(next.tikz.snippet); onChange(next); }
  function applyCode() { onChange(applyManualTikzCode(draft, code)); }
  function confirmClassification() { const next = structuredClone(draft); next.classification.teacherConfirmed = true; next.validation = validateTikzDraft(next); next.reviewQueue = buildTikzReviewQueue(next); next.quality = qualitySummary(next); next.status = next.validation.valid ? "valid" : "needs_review"; next.metadata.updatedAt = new Date().toISOString(); onChange(next); }
  async function download(format: "svg" | "png" | "zip" | "pdf") { const endpoint = format === "pdf" ? "/api/tikz/compiler" : "/api/tikz/render"; const body = format === "pdf" ? { source: draft.tikz.standalone } : { draft, format, fileName: draft.source.sourceName || "soan-lab-tikz", settings: { background, lineWeight, showLabels, scale: pngScale } }; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { setNotice(format === "pdf" ? "Máy chủ hiện chưa có trình biên dịch TeX. SOẠN LAB vẫn tạo mã TikZ và bản SVG để thầy cô kiểm tra." : "Chưa tạo được định dạng hình này. Các kết quả hiện có vẫn được giữ."); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `soan-lab-tikz.${format}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function applyProposal() { if (!proposal) return; let next = draft; for (const operation of proposal.operations) next = applyStructuredEdit(next, operation); setCode(next.tikz.snippet); onChange(next); setProposal(undefined); setCommand(""); }
  function review(id: string, status: TikzReviewItem["status"]) { const next = decideReviewItem(draft, id, status); next.validation = validateTikzDraft(next); next.quality = qualitySummary(next); onChange(next); }
  async function blobDataUrl(blob: Blob) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(new Error("read_failed")); reader.readAsDataURL(blob); }); }
  async function confirmForUse() { setWorking(true); setNotice(""); try { const next = structuredClone(draft); next.classification.teacherConfirmed = true; next.reviewQueue = buildTikzReviewQueue(next); next.validation = validateTikzDraft(next); const gate = evaluateTikzReadiness(next); if (gate.blockers.length) { next.status = "needs_review"; next.quality = qualitySummary(next); onChange(next); setNotice(gate.blockers[0]); return; } const svg = rendered.svg; const pngResponse = await fetch("/api/tikz/render", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draft: next, format: "png", settings: { background, lineWeight, showLabels, scale: pngScale } }) }); if (!pngResponse.ok) throw new Error("asset_generation_failed"); const pngBlob = await pngResponse.blob(); const svgBlob = new Blob([svg], { type: "image/svg+xml" }); const svgUrl = await blobDataUrl(svgBlob); const pngUrl = await blobDataUrl(pngBlob); let svgAssetId: string | undefined; let pngAssetId: string | undefined; if (next.source.sourceAsset?.id) { svgAssetId = (await uploadPrivateTikzAsset(svgBlob, "svg", next.source.sourceAsset.id))?.id; pngAssetId = (await uploadPrivateTikzAsset(pngBlob, "png", next.source.sourceAsset.id))?.id; } next.confirmedAsset = createConfirmedDiagramAsset(next, { svgDataUrl: svgUrl, pngDataUrl: pngUrl, svgAssetId, pngAssetId }); next.status = "confirmed"; next.quality = qualitySummary(next); next.metadata.updatedAt = new Date().toISOString(); onChange(next); setNotice("Đã xác nhận hình và tạo tài sản SVG/PNG dùng cho tài liệu."); } catch { setNotice("Chưa tạo được một định dạng hình. Các định dạng đã tạo thành công vẫn được giữ."); } finally { setWorking(false); } }
  async function insertIntoTarget() { if (!draft.confirmedAsset) return setNotice("Cần xác nhận hình trước khi chèn vào tài liệu."); try { const maintenanceResponse = await fetch("/api/maintenance", { cache: "no-store" }); const maintenance = maintenanceResponse.ok ? await maintenanceResponse.json() as { maintenance?: boolean; message?: string } : null; if (maintenance?.maintenance) return setNotice(maintenance.message || "Hệ thống đang bảo trì nên chưa thể chèn hình vào tài liệu."); if (targetDocumentId.startsWith("question:")) { const questionId = targetDocumentId.slice(9); const nextQuestions = questions.map((item) => item.id === questionId ? insertDiagramIntoQuestion(item, draft.confirmedAsset!) : item); setQuestions(nextQuestions); saveQuestions(nextQuestions.map(toLegacyQuestion)); setNotice("Đã gắn hình đã xác nhận vào câu hỏi trong Ngân hàng câu hỏi."); return; } if (!targetDocument || !targetLocationId) return setNotice("Vui lòng chọn tài liệu và vị trí chèn."); const updated = insertConfirmedDiagram(targetDocument, draft.confirmedAsset, targetLocationId); if (usingCloudDocuments && !(await saveDocumentToCloud(updated))) throw new Error("cloud_document_save_failed"); saveDocument(updated); setDocuments((items) => items.map((item) => item.id === updated.id ? updated : item)); const next = structuredClone(draft); next.documentReferences = [...(next.documentReferences || []).filter((item) => !(item.documentId === updated.id && item.locationId === targetLocationId)), { documentId: updated.id, documentType: updated.examSolutionSet ? "answer-solutions" : updated.type as "exam" | "worksheet" | "lesson-plan" | "lesson-slides" | "review-pack", locationId: targetLocationId, diagramVersion: draft.metadata.version, insertedAt: new Date().toISOString() }]; onChange(next); setNotice("Đã chèn hình vào tài liệu. Mở lại tài liệu để kiểm tra trước khi xuất."); } catch { setNotice("Chưa thể chèn hình vào tài liệu. Bản TikZ và hình đã xác nhận vẫn được giữ lại."); } }

  const qualityItems = [{ label: "Phân loại hình", value: draft.quality.classification }, { label: "Đầy đủ đối tượng", value: draft.quality.objectCoverage }, { label: "Đầy đủ nhãn", value: draft.quality.labelCoverage }, { label: "Quan hệ hình học", value: draft.quality.relationships }, { label: "Kiểm tra mã", value: draft.quality.compilation }, { label: "Bố cục", value: draft.quality.layout }];
  return <div className="space-y-4">
    <div className="ui-panel p-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-slate-950">Không gian rà soát TikZ</p><p className="text-sm text-slate-600">Phiên bản {draft.metadata.version} · Kiểm tra ảnh gốc, đối tượng, quan hệ và mã trước khi xác nhận.</p>{draft.documentReferences?.length ? <p className="mt-1 text-xs font-bold text-amber-700">Hình này đã được sử dụng trong {new Set(draft.documentReferences.map((item) => item.documentId)).size} tài liệu. Khi chỉnh sửa, SOẠN LAB tạo phiên bản mới và không đổi tài liệu cũ.</p> : null}</div><span className={`rounded-full px-3 py-1 text-xs font-black ${readiness.status === "unbuildable" ? "bg-red-100 text-red-700" : readiness.status === "needs_review" ? "bg-amber-100 text-amber-800" : "bg-blue-100 text-blue-700"}`}>{readiness.status === "ready" ? "Sẵn sàng sử dụng" : readiness.status === "warning" ? "Có cảnh báo" : readiness.status === "needs_review" ? "Cần rà soát" : "Không thể dựng"}</span></div>
      <details className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-black text-slate-800">Chất lượng nhận diện</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{qualityItems.map((item) => <div key={item.label} className="rounded-xl bg-white p-3"><div className="flex justify-between text-xs font-bold text-slate-600"><span>{item.label}</span><span>{item.value}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${item.value}%` }} /></div></div>)}</div></details>
      {!compiler.available ? <p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900">Bản xem trước hiện được dựng từ cấu trúc hình. Mã TikZ chưa được kiểm tra bằng trình biên dịch TeX trên máy chủ này.</p> : <p className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800">Máy chủ có môi trường TeX. Chỉ khi tệp PDF hợp lệ được tạo, SOẠN LAB mới ghi nhận “Đã biên dịch bằng TeX”.</p>}
      {reviewQueue.filter((item) => item.status === "pending").length ? <p className="mt-2 text-sm font-black text-amber-700">Còn {reviewQueue.filter((item) => item.status === "pending").length} mục cần xác nhận.</p> : null}
    </div>
    <div className="flex max-w-full gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`min-h-11 shrink-0 rounded-xl px-3 py-2 text-sm font-bold ${tab === item.id ? "bg-emerald-700 text-white" : "text-slate-600 hover:bg-emerald-50 hover:text-emerald-800"}`}>{item.label}</button>)}</div>

    {tab === "review" ? <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-4 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-700"><label className="min-h-11">Thu phóng <input className="ml-2 align-middle" type="range" min="70" max="160" value={zoom * 100} onChange={(event) => setZoom(Number(event.target.value) / 100)} /></label>{sourceUrl ? <label className="flex min-h-11 items-center"><input type="checkbox" checked={overlay} onChange={(event) => setOverlay(event.target.checked)} /> <span className="ml-1">Chồng ảnh gốc</span></label> : null}{overlay ? <label className="min-h-11">Độ mờ <input className="ml-2 align-middle" type="range" min="10" max="90" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} /></label> : null}<label className="flex min-h-11 items-center"><input type="checkbox" checked={showBoxes} onChange={(event) => setShowBoxes(event.target.checked)} /> <span className="ml-1">Khung đối tượng</span></label><label className="flex min-h-11 items-center"><input type="checkbox" checked={showLabels} onChange={(event) => setShowLabels(event.target.checked)} /> <span className="ml-1">Nhãn</span></label><label className="flex min-h-11 items-center"><input type="checkbox" checked={showHidden} onChange={(event) => setShowHidden(event.target.checked)} /> <span className="ml-1">Cạnh khuất</span></label></div>
      <div className={`grid gap-3 ${sourceUrl && !overlay ? "lg:grid-cols-2" : ""}`}>{sourceUrl && !overlay ? <PreviewCard title="Ảnh gốc" url={sourceUrl} zoom={zoom} /> : null}<div className="relative min-h-80 overflow-auto rounded-2xl border bg-[#fffdf8]">{sourceUrl && overlay ? <div className="absolute inset-0"><Image src={sourceUrl} alt="Ảnh nguồn" fill className="object-contain" unoptimized /></div> : null}<div className="absolute inset-0" style={{ opacity: overlay ? opacity / 100 : 1, transform: `scale(${zoom})` }}><Image src={previewUrl} alt="Bản xem trước semantic" fill className="object-contain" unoptimized /></div></div></div>
      <div className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-3 sm:grid-cols-4"><label className="text-xs font-bold">Nền<select className="form-field mt-1" value={background} onChange={(event) => setBackground(event.target.value as "transparent" | "white")}><option value="white">Nền trắng</option><option value="transparent">Trong suốt</option></select></label><label className="text-xs font-bold">Độ dày nét<select className="form-field mt-1" value={lineWeight} onChange={(event) => setLineWeight(event.target.value as "thin" | "standard" | "bold")}><option value="thin">Nét mảnh</option><option value="standard">Nét tiêu chuẩn</option><option value="bold">Nét đậm</option></select></label><label className="text-xs font-bold">PNG<select className="form-field mt-1" value={pngScale} onChange={(event) => setPngScale(Number(event.target.value) as 1 | 2 | 4)}><option value={1}>1x</option><option value={2}>2x</option><option value={4}>4x</option></select></label><label className="flex items-end gap-2 pb-2 text-xs font-bold"><input type="checkbox" checked={showLabels} onChange={(event) => setShowLabels(event.target.checked)} /> Có nhãn</label></div>
      <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" onClick={() => void download("svg")}><Download size={15} />Tải SVG</button><button type="button" className="btn-secondary" onClick={() => void download("png")}><Download size={15} />Tải PNG</button><button type="button" className="btn-secondary" onClick={() => void download("zip")}><Download size={15} />Tải gói ZIP</button>{compiler.supportsPdf ? <button type="button" className="btn-secondary" onClick={() => void download("pdf")}><Download size={15} />Tải PDF TeX</button> : null}<button type="button" className="btn-primary" disabled={working} onClick={() => void confirmForUse()}><Check size={15} />{working ? "Đang tạo tài sản..." : "Xác nhận hình để sử dụng"}</button></div>
    </div> : null}

    {tab === "objects" ? <div className="space-y-3">{draft.objects.length ? draft.objects.map((object) => <article key={object.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{objectTypeLabel(object.type)} {object.label ? `· ${object.label}` : ""}</strong><span className="text-xs text-slate-500">{object.confidence === "high" ? "Tin cậy cao" : object.confidence === "medium" ? "Cần kiểm tra" : "Tin cậy thấp"}</span></div><div className="mt-3 flex flex-wrap gap-2">{object.type === "point" ? <><input aria-label="Tên điểm" className="form-field max-w-28" value={object.label || ""} onChange={(event) => edit({ type: "rename_point", objectId: object.id, label: event.target.value })}/>{object.position ? <><input aria-label="Tọa độ x" type="number" step="0.1" className="form-field max-w-24" value={object.position.x} onChange={(event) => edit({ type: "move_object", objectId: object.id, position: { x: Number(event.target.value), y: object.position!.y } })}/><input aria-label="Tọa độ y" type="number" step="0.1" className="form-field max-w-24" value={object.position.y} onChange={(event) => edit({ type: "move_object", objectId: object.id, position: { x: object.position!.x, y: Number(event.target.value) } })}/></> : null}</> : null}{["segment", "line", "ray", "vector"].includes(object.type) ? <select className="form-field max-w-36" value={object.style || "solid"} onChange={(event) => edit({ type: "change_line_style", objectId: object.id, style: event.target.value as "solid" | "dashed" | "dotted" })}><option value="solid">Nét liền</option><option value="dashed">Nét đứt</option><option value="dotted">Nét chấm</option></select> : null}{object.label ? <select className="form-field max-w-40" value={object.anchor || "above right"} onChange={(event) => edit({ type: "move_label", objectId: object.id, anchor: event.target.value as DiagramObject["anchor"] })}>{anchors.map((anchor) => <option key={anchor}>{anchor}</option>)}</select> : null}<button type="button" className="btn-secondary" onClick={() => { setSelectedObjectId(object.id); setShowBoxes(true); }}><Eye size={14}/>Kiểm tra nguồn</button></div></article>) : <p className="empty-state">Chưa có đối tượng semantic đủ rõ. Thầy cô nên giữ ảnh gốc.</p>}
      {selectedObject ? <div className="grid gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 lg:grid-cols-2"><div><p className="font-black">Đối chiếu đối tượng nguồn</p><p className="mt-1 text-sm">{objectTypeLabel(selectedObject.type)} · {selectedObject.label || selectedObject.text || "Chưa có nhãn"} · {selectedObject.confidence === "high" ? "Tin cậy cao" : selectedObject.confidence === "medium" ? "Cần kiểm tra" : "Tin cậy thấp"}</p>{sourceUrl ? <div className="relative mt-3 h-44 overflow-hidden rounded-xl bg-white"><Image src={sourceUrl} alt="Vùng ảnh nguồn của đối tượng" fill className="object-contain" unoptimized style={{ transform: "scale(1.8)" }}/></div> : <p className="mt-3 text-sm text-amber-800">Bản TikZ cũ không còn ảnh nguồn để đối chiếu.</p>}</div><div><p className="font-black">Quan hệ và mã liên quan</p>{draft.relationships.filter((item) => item.objectIds.includes(selectedObject.id)).map((item) => <p key={item.id} className="mt-1 text-sm">• {item.type}</p>)}<pre className="mt-3 max-h-36 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-white">{draft.tikz.snippet.split(/\r?\n/).filter((line) => selectedObject.label && line.includes(selectedObject.label)).join("\n") || "Mã được sinh qua tham chiếu nội bộ của đối tượng."}</pre></div></div> : null}
      {layoutRepairs.length ? <div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4"><p className="font-bold">Đề xuất tách nhãn chồng nhau</p>{layoutRepairs.map((repair) => <button type="button" className="btn-secondary mt-2 mr-2" key={repair.objectId} onClick={() => edit({ type: "move_label", objectId: repair.objectId, anchor: repair.to })}><Move size={14} />{repair.reason}</button>)}</div> : null}
    </div> : null}

    {tab === "relationships" ? <div className="space-y-2">{draft.relationships.length ? draft.relationships.map((relationship) => <div key={relationship.id} className="rounded-xl border border-slate-200 p-3"><strong>{relationship.type}</strong><p className="mt-1 text-xs text-slate-500">{relationship.objectIds.join(" · ")}</p><p className="text-xs text-slate-600">{relationship.teacherConfirmed ? "Giáo viên đã xác nhận" : relationship.confidence === "low" ? "Cần giáo viên xác nhận" : "Được nhận diện tự động"}</p></div>) : <p className="empty-state">Chưa có quan hệ hình học được nhận diện chắc chắn.</p>}<button type="button" className="btn-secondary" onClick={confirmClassification}><Check size={15} />Xác nhận phân loại</button>{reviewQueue.length ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-black">Hàng đợi rà soát</p>{reviewQueue.map((item) => <div key={item.id} className="mt-3 rounded-xl bg-white p-3"><p className="text-sm font-bold">{item.message}</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" className="btn-secondary" onClick={() => review(item.id, "confirmed")}>Xác nhận</button><button type="button" className="btn-secondary" onClick={() => { if (item.objectId) { setSelectedObjectId(item.objectId); setTab("objects"); } }}>Sửa</button><button type="button" className="btn-secondary" onClick={() => review(item.id, "ignored")}>Bỏ qua</button><button type="button" className="btn-secondary" onClick={() => review(item.id, "keep_source")}>Giữ ảnh gốc</button></div></div>)}</div> : null}</div> : null}

    {tab === "code" ? <div className="space-y-3"><div className="grid grid-cols-[auto_1fr] overflow-hidden rounded-2xl border bg-slate-950 text-xs text-slate-100"><pre className="select-none border-r border-slate-700 px-3 py-4 text-right text-slate-500">{code.split(/\r?\n/).map((_, index) => index + 1).join("\n")}</pre><textarea aria-label="Mã TikZ" className="min-h-96 resize-y bg-transparent p-4 font-mono outline-none" value={code} onChange={(event) => setCode(event.target.value)} /></div>{draft.tikz.semanticSync === "partially_detached" ? <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Mã đã được chỉnh sửa thủ công. Một số điều khiển trực quan có thể không còn đồng bộ hoàn toàn.</p> : null}<div className="flex flex-wrap gap-2"><button type="button" className="btn-primary" onClick={applyCode}><Code2 size={15} />Kiểm tra và giữ bản sửa</button><button type="button" className="btn-secondary" onClick={() => { const fixed = repairTikzSyntax(code); setCode(fixed.code); }}><ShieldCheck size={15} />Xem sửa lỗi an toàn</button><button type="button" className="btn-secondary" onClick={() => setCode(draft.tikz.generatedSnippet)}><RotateCcw size={15} />Khôi phục bản dựng</button><button type="button" className="btn-secondary" onClick={() => navigator.clipboard.writeText(code)}><Code2 size={15} />Sao chép</button></div></div> : null}

    {tab === "errors" ? <div className="space-y-3">{draft.compilation.errors.length ? draft.compilation.errors.map((error, index) => <div key={`${error.code}-${index}`} className="rounded-xl border border-red-200 bg-red-50 p-3"><strong>{error.message}</strong>{error.line ? <p className="text-sm">Dòng {error.line}</p> : null}{error.suggestion ? <p className="text-sm text-red-800">Đề xuất: {error.suggestion}</p> : null}</div>) : <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Không phát hiện lỗi cú pháp hoặc lệnh nguy hiểm trong kiểm tra tĩnh. Đây chưa phải kết quả biên dịch TeX.</p>}<div className="rounded-2xl border p-4"><p className="font-bold">Yêu cầu chỉnh hình</p><textarea className="form-field mt-2 min-h-24" value={command} onChange={(event) => setCommand(event.target.value)} placeholder="Ví dụ: Đổi cạnh AC thành nét đứt."/><button type="button" className="btn-secondary mt-2" onClick={() => setProposal(parseNaturalDiagramEdit(command, draft))}>Tạo đề xuất</button>{proposal ? <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Thay đổi đề xuất</p>{proposal.operations.map((operation, index) => <p key={index}>• {operation.type}</p>)}{proposal.warnings.map((warning) => <p key={warning} className="text-amber-700">• {warning}</p>)}{proposal.operations.length ? <button type="button" className="btn-primary mt-2" onClick={applyProposal}><Check size={15} />Xác nhận áp dụng</button> : null}</div> : null}</div></div> : null}

    {tab === "compare" ? <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Bao phủ đối tượng" value={comparison.objectCoverage}/><Metric label="Bao phủ nhãn" value={comparison.labelCoverage}/><Metric label="Quan hệ cấu trúc" value={comparison.structuralSimilarity}/><Metric label="Tỉ lệ bố cục" value={comparison.sourceRenderAlignment}/></div><p className={`rounded-xl p-3 text-sm font-bold ${comparison.status === "near_match" ? "bg-emerald-50 text-emerald-800" : comparison.status === "needs_review" ? "bg-amber-50 text-amber-900" : "bg-red-50 text-red-800"}`}>{comparison.status === "near_match" ? "Gần khớp theo mô hình semantic" : comparison.status === "needs_review" ? "Cần kiểm tra" : "Không khớp"}</p>{comparison.suspiciousDifferences.map((item) => <p key={item} className="text-sm text-amber-800">• {item}</p>)}<p className="text-xs leading-5 text-slate-500">So sánh này dùng đối tượng, nhãn, quan hệ và tỉ lệ bố cục; không phải đánh giá giống pixel và không chứng minh hình học đã đúng.</p></div> : null}
    {draft.confirmedAsset ? <section className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><p className="font-black">Chèn hình đã xác nhận vào tài liệu</p><p className="mt-1 text-sm text-slate-600">Tài liệu lưu tham chiếu phiên bản {draft.confirmedAsset.version}; chỉnh hình sau này không tự đổi tài liệu cũ.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="form-field" value={targetDocumentId} onChange={(event) => { setTargetDocumentId(event.target.value); setTargetLocationId(""); }}><option value="">Chọn tài liệu hoặc câu hỏi</option>{documents.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}{questions.map((item) => <option key={`question:${item.id}`} value={`question:${item.id}`}>Ngân hàng · {item.prompt.slice(0, 70)}</option>)}</select>{!targetDocumentId.startsWith("question:") ? <select className="form-field" value={targetLocationId} onChange={(event) => setTargetLocationId(event.target.value)}><option value="">Chọn vị trí chèn</option>{insertionTargets.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select> : <div className="rounded-xl bg-white p-3 text-sm">Gắn vào câu hỏi đã chọn.</div>}</div><button type="button" className="btn-primary mt-3" onClick={() => void insertIntoTarget()}><FileInput size={15}/>Chèn vào tài liệu</button></section> : null}
    {notice ? <p className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-bold text-blue-900">{notice}</p> : null}
    <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={!draft.teacherEdits.length} onClick={() => { const latest = draft.teacherEdits.at(-1); if (latest?.source === "code" && typeof latest.before === "string") onChange(applyManualTikzCode({ ...draft, teacherEdits: draft.teacherEdits.slice(0, -1) }, latest.before)); }}><Undo2 size={15} />Hoàn tác sửa mã gần nhất</button><button type="button" className="btn-secondary" onClick={() => setTab("review")}><Eye size={15} />Xem preview</button><button type="button" className="btn-secondary" onClick={() => setTab("compare")}><GitCompare size={15} />So sánh</button></div>
  </div>;
}

function PreviewCard({ title, url, zoom }: { title: string; url: string; zoom: number }) { return <div className="rounded-2xl border bg-white p-3"><p className="mb-2 text-xs font-black text-slate-600">{title}</p><div className="relative min-h-80 overflow-auto"><div className="absolute inset-0" style={{ transform: `scale(${zoom})` }}><Image src={url} alt={title} fill className="object-contain" unoptimized /></div></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border p-3"><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${value}%` }}/></div></div>; }
