import Link from "next/link";
import { ArrowRight, CheckCircle2, FileCheck2, FileText, FolderClock, Library, MousePointerClick, PenLine, Sparkles } from "lucide-react";
import { BrandLogo } from "@/components/BrandLogo";
import { Navbar } from "@/components/Navbar";
import { SiteFooter } from "@/components/SiteFooter";
import { ToolCard } from "@/components/ToolCard";
import { toolRegistry } from "@/lib/tool-registry";

const painPoints = ["Soạn đề kiểm tra", "Làm đáp án và thang điểm", "Tạo ma trận đề", "Viết nhận xét học sinh", "Chuẩn bị phiếu học tập", "Chỉnh file Word"];
const benefits = [
  ["Không cần viết prompt dài", "Chọn công cụ và điền form theo đúng nghiệp vụ.", Sparkles],
  ["Form rõ ràng", "Các trường nhập quen thuộc với giáo viên Việt Nam.", PenLine],
  ["Xuất Word nhanh", "Tải bản nháp để kiểm tra, chỉnh sửa và sử dụng.", FileText],
  ["Lưu lịch sử", "Mở lại tài liệu đã tạo ngay trên trình duyệt.", FolderClock],
  ["Mẫu cá nhân", "Dùng lại cấu trúc tài liệu quen thuộc.", FileCheck2],
  ["Ngân hàng câu hỏi local", "Lưu và tái sử dụng theo môn, lớp, chủ đề.", Library]
];
const steps = [["01", "Chọn công cụ"], ["02", "Nhập thông tin"], ["03", "Xem kết quả"], ["04", "Sao chép, lưu hoặc xuất Word"]];
const coreHrefs = ["/tools/exam-generator", "/tools/matrix-generator", "/tools/exam-shuffler", "/tools/bulk-student-comments", "/tools/lesson-plan-generator", "/question-bank"];

export default function HomePage() {
  const coreTools = toolRegistry.filter((tool) => coreHrefs.includes(tool.href));
  return <main><Navbar />
    <section className="relative overflow-hidden border-b border-slate-200 bg-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(79,70,229,0.13),transparent_32%),radial-gradient(circle_at_85%_25%,rgba(37,99,235,0.10),transparent_28%)]" />
      <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 md:py-24 lg:grid-cols-[1.15fr_0.85fr]">
        <div><span className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-indigo-700">MVP/demo · AI mô phỏng</span><div className="mt-6"><BrandLogo /></div><h1 className="mt-7 max-w-3xl text-4xl font-extrabold tracking-tight text-ink sm:text-5xl md:text-6xl">Bộ công cụ AI cho giáo viên Việt Nam</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Soạn Lab giúp giáo viên soạn đề, tạo phiếu học tập, viết nhận xét học sinh, tạo ma trận đề và xuất Word nhanh hơn.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/tools" className="btn-primary">Khám phá công cụ<ArrowRight size={17} /></Link><Link href="/dashboard" className="btn-secondary">Dùng thử demo</Link></div><p className="mt-6 text-sm font-semibold text-slate-500">Soạn đề, tạo tài liệu, xuất Word trong vài phút.</p></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2rem] bg-gradient-to-br from-blue-200/50 to-violet-200/50 blur-2xl" /><div className="card relative overflow-hidden p-6 sm:p-8"><div className="flex items-center justify-between"><span className="text-sm font-bold text-ink">Workspace giáo viên</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Zero-cost demo</span></div><div className="mt-6 space-y-3">{["Tạo đề kiểm tra có đáp án", "Tạo ma trận theo mức độ", "Xuất Word để chỉnh sửa"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600 text-sm font-bold text-white">{index + 1}</span><span className="text-sm font-semibold text-ink">{item}</span><CheckCircle2 className="ml-auto text-emerald-500" size={18} /></div>)}</div></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Vấn đề thực tế</p><h2 className="mt-2 max-w-3xl text-3xl font-bold tracking-tight text-ink">Những việc lặp lại đang lấy quá nhiều thời gian của giáo viên</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{painPoints.map((item) => <div key={item} className="card flex items-center gap-4 p-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-brand"><CheckCircle2 size={19} /></span><span className="font-semibold text-ink">{item}</span></div>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Giải pháp</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-ink">Soạn Lab gom các công cụ đó vào một nơi</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([title, text, Icon]) => { const BenefitIcon = Icon as typeof Sparkles; return <article key={title as string} className="card p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-blue-50 to-indigo-100 text-brand"><BenefitIcon size={21} /></span><h3 className="mt-5 font-bold text-ink">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{text as string}</p></article>; })}</div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-16"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-brand">Công cụ nổi bật</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-ink">Bắt đầu từ workflow quen thuộc</h2></div><Link href="/tools" className="hidden font-semibold text-brand sm:block">Xem tất cả</Link></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{coreTools.map((tool) => <ToolCard key={tool.href} {...tool} categoryLabel="Soạn Lab" />)}</div></section>
    <section className="border-y border-slate-200 bg-gradient-to-br from-slate-900 to-indigo-950 text-white"><div className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-blue-300">Cách hoạt động</p><h2 className="mt-2 text-3xl font-bold">Từ ý tưởng đến tài liệu trong bốn bước</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{steps.map(([number, text]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur"><span className="text-sm font-bold text-blue-300">{number}</span><MousePointerClick className="mt-5 text-white" size={22} /><p className="mt-3 font-semibold">{text}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-16 md:grid-cols-[0.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-wide text-brand">Founder</p><h2 className="mt-2 text-3xl font-bold text-ink">Về người tạo ra Soạn Lab</h2><p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-800">Soạn Lab hiện đang ở giai đoạn MVP/demo và sẽ tiếp tục được cải thiện dựa trên góp ý thực tế từ giáo viên.</p></div><div className="space-y-4 text-lg leading-8 text-slate-700"><p>Soạn Lab được tạo ra bởi Trần Đức Duy, sinh viên của TUM và HCMUT, với mong muốn giúp giáo viên tiết kiệm thời gian trong những công việc đơn giản nhưng lặp lại hằng ngày như soạn đề, tạo phiếu học tập, viết nhận xét học sinh và chuẩn bị tài liệu giảng dạy.</p><p>Mục tiêu của Soạn Lab không phải là thay thế giáo viên, mà là giúp giáo viên có thêm thời gian cho những việc quan trọng hơn: giảng dạy, hỗ trợ học sinh và cải thiện chất lượng bài học.</p></div></section>
    <section className="mx-auto max-w-6xl px-4 pb-16"><div className="overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 to-indigo-700 px-6 py-10 text-white shadow-2xl shadow-blue-200 md:px-10"><h2 className="text-3xl font-bold">Dùng thử Soạn Lab bản demo</h2><p className="mt-3 max-w-2xl leading-7 text-blue-100">Khám phá workflow hiện tại và giúp sản phẩm gần hơn với công việc thật của giáo viên.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-white px-4 py-2 text-sm font-bold text-blue-700">Mở dashboard</Link><Link href="/feedback" className="inline-flex min-h-11 items-center justify-center rounded-xl border border-white/30 px-4 py-2 text-sm font-bold text-white">Góp ý cho Soạn Lab</Link></div></div></section>
    <SiteFooter />
  </main>;
}
