import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileCheck2, FileText, FolderClock, GraduationCap, Library, MessageSquareText, MousePointerClick, PenLine, Sparkles } from "lucide-react";
import { BrandLogo } from "@/components/BrandLogo";
import { Navbar } from "@/components/Navbar";
import { SiteFooter } from "@/components/SiteFooter";
import { ToolCard } from "@/components/ToolCard";
import { toolRegistry } from "@/lib/tool-registry";

const painPoints = ["Soạn đề kiểm tra", "Làm đáp án và thang điểm", "Tạo ma trận đề", "Viết nhận xét học sinh", "Chuẩn bị phiếu học tập", "Chỉnh file Word"];
const benefits = [
  ["Không cần viết prompt dài", "Chọn công cụ và điền form theo đúng nghiệp vụ.", Sparkles],
  ["Form rõ ràng", "Các trường nhập quen thuộc với giáo viên Việt Nam.", PenLine],
  ["Xuất Word nhanh", "Tải bản nháp để kiểm tra, chỉnh sửa và sử dụng.", FileText],
  ["Lưu lịch sử", "Mở lại tài liệu đã tạo ngay trên trình duyệt.", FolderClock],
  ["Mẫu cá nhân", "Dùng lại cấu trúc tài liệu quen thuộc.", FileCheck2],
  ["Ngân hàng câu hỏi local", "Lưu và tái sử dụng theo môn, lớp, chủ đề.", Library]
];
const steps = [["01", "Chọn công cụ"], ["02", "Nhập thông tin"], ["03", "Xem kết quả"], ["04", "Sao chép, lưu hoặc xuất Word"]];
const coreHrefs = ["/tools/exam-generator", "/tools/matrix-generator", "/tools/answer-key-generator", "/tools/worksheet-generator", "/tools/student-comments", "/tools/bulk-student-comments", "/tools/lesson-plan-generator", "/question-bank"];
const dailyWork = [
  ["Soạn đề kiểm tra", "Tạo cấu trúc đề, câu hỏi và nội dung kiểm tra.", PenLine],
  ["Tạo ma trận đề", "Phân bổ câu hỏi theo chủ đề và mức độ.", ClipboardCheck],
  ["Tạo phiếu học tập", "Chuẩn bị hoạt động và bài tập cho tiết học.", FileText],
  ["Viết nhận xét học sinh", "Tạo bản nháp nhận xét để giáo viên chỉnh sửa.", MessageSquareText],
  ["Tạo giáo án", "Sắp xếp mục tiêu, chuẩn bị và tiến trình dạy học.", GraduationCap],
  ["Xuất Word/PDF", "Chuyển tài liệu sang định dạng quen thuộc để sử dụng.", FileCheck2]
];

export default function HomePage() {
  const coreTools = toolRegistry.filter((tool) => coreHrefs.includes(tool.href));
  return <main><Navbar />
    <section className="relative overflow-hidden border-b border-slate-200 bg-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(79,70,229,0.13),transparent_32%),radial-gradient(circle_at_85%_25%,rgba(37,99,235,0.10),transparent_28%)]" />
      <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 md:py-24 lg:grid-cols-[1.15fr_0.85fr]">
        <div><div className="flex flex-wrap gap-2">{["MVP/demo", "AI mô phỏng", "Xuất Word", "Dành cho giáo viên Việt Nam"].map((badge) => <span key={badge} className="soft-badge">{badge}</span>)}</div><div className="mt-6"><BrandLogo /></div><h1 className="mt-7 max-w-3xl text-4xl font-extrabold tracking-tight text-ink sm:text-5xl md:text-6xl">Bộ công cụ AI cho giáo viên Việt Nam</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted">Soạn Lab giúp giáo viên soạn đề, tạo phiếu học tập, viết nhận xét học sinh, tạo ma trận đề và xuất Word nhanh hơn.</p><p className="mt-4 font-bold text-brand">Soạn đề, tạo tài liệu, xuất Word trong vài phút.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href="/dashboard" className="btn-primary">Dùng thử demo<ArrowRight size={17} /></Link><Link href="/tools" className="btn-secondary">Khám phá công cụ</Link><Link href="/feedback" className="btn-ghost">Góp ý cho Soạn Lab</Link></div></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2rem] bg-gradient-to-br from-blue-200/60 to-violet-200/60 blur-2xl" /><div className="card relative overflow-hidden p-3 shadow-2xl"><div className="flex min-h-[390px] overflow-hidden rounded-2xl bg-slate-50"><div className="hidden w-24 bg-slate-900 p-3 sm:block"><div className="h-8 w-8 rounded-lg bg-blue-500" /><div className="mt-8 space-y-3">{[1,2,3,4,5].map((item) => <div key={item} className="h-2 rounded bg-white/20" />)}</div></div><div className="min-w-0 flex-1 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-muted">Dashboard</p><p className="mt-1 font-bold text-ink">Gặp Soạn Lab</p></div><span className="soft-badge">AI demo</span></div><div className="mt-4 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 p-5 text-white"><p className="font-bold">Tạo tài liệu nhanh hơn</p><p className="mt-2 text-xs text-blue-100">Form rõ ràng · Lưu lịch sử · Xuất Word</p></div><div className="mt-4 grid grid-cols-2 gap-3">{["Tạo đề", "Ma trận", "Phiếu học tập", "Nhận xét"].map((item) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-3"><div className="h-8 w-8 rounded-lg bg-blue-50" /><p className="mt-3 text-xs font-bold text-ink">{item}</p></div>)}</div><div className="mt-4 flex items-center justify-between rounded-xl border border-emerald-100 bg-emerald-50 p-3"><span className="text-xs font-bold text-emerald-700">Tài liệu sẵn sàng</span><span className="rounded-lg bg-white px-2 py-1 text-xs font-bold text-emerald-700">Xuất Word</span></div></div></div></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Thiết kế theo công việc thực tế</p><h2 className="mt-2 max-w-3xl text-3xl font-bold tracking-tight text-ink">Được thiết kế cho những việc giáo viên làm mỗi ngày</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{dailyWork.map(([title, description, Icon]) => { const WorkIcon = Icon as typeof PenLine; return <article key={title as string} className="card p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-brand"><WorkIcon size={21} /></span><h3 className="mt-4 font-bold text-ink">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{description as string}</p></article>; })}</div></section>
    <section className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Vấn đề thực tế</p><h2 className="mt-2 max-w-3xl text-3xl font-bold tracking-tight text-ink">Những việc lặp lại đang lấy quá nhiều thời gian của giáo viên</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{painPoints.map((item) => <div key={item} className="card flex items-center gap-4 p-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-brand"><CheckCircle2 size={19} /></span><span className="font-semibold text-ink">{item}</span></div>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Giải pháp</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-ink">Soạn Lab gom các công cụ đó vào một nơi</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([title, text, Icon]) => { const BenefitIcon = Icon as typeof Sparkles; return <article key={title as string} className="card p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-blue-50 to-indigo-100 text-brand"><BenefitIcon size={21} /></span><h3 className="mt-5 font-bold text-ink">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{text as string}</p></article>; })}</div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-16"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-brand">Công cụ nổi bật</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-ink">Bắt đầu từ workflow quen thuộc</h2></div><Link href="/tools" className="hidden font-semibold text-brand sm:block">Xem tất cả</Link></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{coreTools.map((tool) => <ToolCard key={tool.href} {...tool} categoryLabel="Soạn Lab" />)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-brand">Product preview</p><h2 className="mt-2 text-3xl font-bold text-ink">Một không gian làm việc gọn hơn cho giáo viên</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">{[["Dashboard", "Tìm công cụ, tài liệu gần đây và workflow gợi ý.", GridPreview], ["Tool form", "Nhập môn, lớp, chủ đề bằng form rõ ràng.", FormPreview], ["Xuất tài liệu", "Sao chép, lưu lịch sử, xuất Word hoặc PDF.", ExportPreview]].map(([title, text, Preview]) => { const PreviewComponent = Preview as () => React.ReactNode; return <article key={title as string} className="card overflow-hidden"><div className="h-48 bg-gradient-to-br from-slate-100 to-blue-50 p-5"><PreviewComponent /></div><div className="p-5"><h3 className="font-bold text-ink">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{text as string}</p></div></article>; })}</div></div></section>
    <section className="border-y border-slate-200 bg-gradient-to-br from-slate-900 to-indigo-950 text-white"><div className="mx-auto max-w-6xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-wide text-blue-300">Cách hoạt động</p><h2 className="mt-2 text-3xl font-bold">Từ ý tưởng đến tài liệu trong bốn bước</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{steps.map(([number, text]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur"><span className="text-sm font-bold text-blue-300">{number}</span><MousePointerClick className="mt-5 text-white" size={22} /><p className="mt-3 font-semibold">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-8 rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 to-indigo-50 p-6 sm:p-9 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="soft-badge">Minh bạch bản demo</span><h2 className="mt-4 text-3xl font-bold text-ink">Hiện tại là bản MVP/demo</h2><p className="mt-3 max-w-3xl leading-7 text-muted">Soạn Lab hiện dùng AI mô phỏng để kiểm thử giao diện, quy trình và định dạng tài liệu. Nội dung thật sẽ được kích hoạt ở bản beta khi hệ thống AI được tích hợp.</p><div className="mt-5 flex flex-wrap gap-2">{["Chưa cần đăng nhập", "Chưa thu phí", "Dữ liệu lưu trên trình duyệt", "Giáo viên cần kiểm tra nội dung"].map((item) => <span key={item} className="rounded-full bg-white px-3 py-1.5 text-xs font-bold text-slate-600 shadow-sm">{item}</span>)}</div></div><Link href="/known-issues" className="btn-secondary">Xem giới hạn hiện tại</Link></div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-16 md:grid-cols-[0.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-wide text-brand">Founder</p><h2 className="mt-2 text-3xl font-bold text-ink">Về người tạo ra Soạn Lab</h2><p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-800">Soạn Lab hiện đang ở giai đoạn MVP/demo và sẽ tiếp tục được cải thiện dựa trên góp ý thực tế từ giáo viên.</p></div><div className="space-y-4 text-lg leading-8 text-slate-700"><p>Soạn Lab được tạo ra bởi Trần Đức Duy, sinh viên của TUM và HCMUT, với mong muốn giúp giáo viên tiết kiệm thời gian trong những công việc đơn giản nhưng lặp lại hằng ngày như soạn đề, tạo phiếu học tập, viết nhận xét học sinh và chuẩn bị tài liệu giảng dạy.</p><p>Mục tiêu của Soạn Lab không phải là thay thế giáo viên, mà là giúp giáo viên có thêm thời gian cho những việc quan trọng hơn: giảng dạy, hỗ trợ học sinh và cải thiện chất lượng bài học.</p></div></section>
    <section className="mx-auto max-w-6xl px-4 pb-16"><div className="overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 to-indigo-700 px-6 py-10 text-white shadow-2xl shadow-blue-200 md:px-10"><h2 className="text-3xl font-bold">Sẵn sàng thử Soạn Lab?</h2><p className="mt-3 max-w-2xl leading-7 text-blue-100">Dùng thử bản demo, tạo một tài liệu đầu tiên và gửi góp ý để Soạn Lab được cải thiện đúng nhu cầu thực tế của giáo viên.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-white px-4 py-2 text-sm font-bold text-blue-700">Mở dashboard</Link><Link href="/feedback" className="inline-flex min-h-11 items-center justify-center rounded-xl border border-white/30 px-4 py-2 text-sm font-bold text-white">Gửi góp ý</Link></div></div></section>
    <SiteFooter />
  </main>;
}

function GridPreview() { return <div className="grid h-full grid-cols-[45px_1fr] gap-3 rounded-xl bg-white p-3 shadow-lg"><div className="rounded-lg bg-slate-900" /><div><div className="h-9 rounded-lg bg-blue-600" /><div className="mt-3 grid grid-cols-2 gap-2"><div className="h-12 rounded-lg bg-blue-50" /><div className="h-12 rounded-lg bg-indigo-50" /></div></div></div>; }
function FormPreview() { return <div className="mx-auto h-full max-w-xs rounded-xl bg-white p-4 shadow-lg"><div className="h-3 w-24 rounded bg-slate-200" /><div className="mt-4 h-9 rounded-lg border border-slate-200" /><div className="mt-3 h-9 rounded-lg border border-slate-200" /><div className="mt-3 h-8 rounded-lg bg-blue-600" /></div>; }
function ExportPreview() { return <div className="mx-auto h-full max-w-xs rounded-xl bg-white p-4 shadow-lg"><div className="h-3 w-28 rounded bg-slate-300" /><div className="mt-4 space-y-2"><div className="h-2 rounded bg-slate-100" /><div className="h-2 rounded bg-slate-100" /><div className="h-2 w-4/5 rounded bg-slate-100" /></div><div className="mt-6 flex gap-2"><span className="rounded-lg bg-blue-600 px-3 py-2 text-[10px] font-bold text-white">Word</span><span className="rounded-lg bg-slate-100 px-3 py-2 text-[10px] font-bold text-slate-600">PDF</span></div></div>; }
