export type ToolCategory =
  | "exam-assessment"
  | "lesson-materials"
  | "homeroom-parent"
  | "formula-latex"
  | "visual-tools"
  | "personalization";

export type ToolMeta = {
  title: string;
  description: string;
  href: string;
  category: ToolCategory;
  badge?: string;
  popular?: boolean;
  aliases?: string[];
  tags?: string[];
  example?: string;
};

export const categoryLabels: Record<ToolCategory, string> = {
  "exam-assessment": "Soạn đề & kiểm tra",
  "lesson-materials": "Soạn bài & tài liệu",
  "homeroom-parent": "Chủ nhiệm & phụ huynh",
  "formula-latex": "Công thức & LaTeX",
  "visual-tools": "Công cụ trực quan",
  personalization: "Cá nhân hóa",
};

export const categoryOrder: ToolCategory[] = [
  "exam-assessment",
  "lesson-materials",
  "homeroom-parent",
  "formula-latex",
  "visual-tools",
  "personalization",
];

export const toolRegistry: ToolMeta[] = [
  {
    title: "Soạn đề kiểm tra",
    description: "Tạo đề, đáp án và thang điểm theo môn, lớp, chủ đề.",
    href: "/tools/exam-generator",
    category: "exam-assessment",
    popular: true,
    aliases: ["đề", "kiểm tra", "thptqg", "thi", "bài kiểm tra"],
    tags: ["Word/PDF", "Đáp án", "THPTQG"],
    example: "Ví dụ: Toán 12 THPTQG, kiểm tra 45 phút",
  },
  {
    title: "Đọc đề từ ảnh/PDF",
    description: "Nhận dạng đề đã quét hoặc PDF hỗn hợp, rà soát từng khối rồi tạo đề có cấu trúc.",
    href: "/tools/document-recognition",
    category: "exam-assessment",
    badge: "Beta",
    popular: true,
    aliases: ["đọc đề", "scan đề", "ảnh đề", "pdf đề", "nhận dạng đề", "ocr đề"],
    tags: ["Ảnh/PDF", "Rà soát", "Nhập đề"],
    example: "Ví dụ: đề giấy đã chụp, PDF quét hoặc PDF có cả chữ và hình",
  },
  {
    title: "Chấm bài",
    description: "Nhận dạng bài làm, chấm phần khách quan và rà soát điểm trước khi xuất báo cáo.",
    href: "/tools/grading-assistant",
    category: "exam-assessment",
    popular: true,
    badge: "Mới",
    aliases: ["chấm bài", "bảng điểm", "bài làm", "mã đề", "phiếu trả lời"],
    tags: ["Ảnh/PDF", "Bảng điểm", "Rà soát"],
    example: "Ví dụ: chấm bài trắc nghiệm theo mã đề 101–104",
  },
  {
    title: "Tạo ma trận đề",
    description: "Lập bảng ma trận, phân bổ câu hỏi và gợi ý thang điểm.",
    href: "/tools/matrix-generator",
    category: "exam-assessment",
    popular: true,
    aliases: ["ma trận", "đặc tả", "mức độ", "nhận biết"],
    tags: ["Ma trận", "Thang điểm"],
    example: "Ví dụ: ma trận giữa kỳ môn Lịch sử 12",
  },
  {
    title: "Tạo đáp án và thang điểm",
    description: "Soạn đáp án, lời giải, thang điểm và lưu ý khi chấm.",
    href: "/tools/answer-key-generator",
    category: "exam-assessment",
    aliases: ["đáp án", "thang điểm", "lời giải"],
    tags: ["Đáp án", "Chấm điểm"],
  },
  {
    title: "Lời giải & đáp án",
    description: "Tạo đáp án nhanh, lời giải chi tiết và kiểm tra độc lập đáp án của đề đã hoàn thiện.",
    href: "/tools/answer-solutions",
    category: "exam-assessment",
    popular: true,
    badge: "Mới",
    aliases: ["lời giải", "đáp án", "kiểm tra đáp án", "hướng dẫn chấm"],
    tags: ["Lời giải", "Đáp án", "Word/PDF"],
  },
  {
    title: "Tạo rubric",
    description: "Tạo bảng tiêu chí đánh giá với các mức độ và điểm số.",
    href: "/tools/rubric-generator",
    category: "exam-assessment",
    popular: true,
    aliases: ["rubric", "tiêu chí", "đánh giá", "chấm điểm"],
    tags: ["Rubric", "Đánh giá"],
    example: "Ví dụ: rubric bài thuyết trình, bài viết, dự án",
  },
  {
    title: "Kiểm tra đề",
    description: "Rà soát cấu trúc, đáp án, điểm, câu trùng và mức sẵn sàng xuất file.",
    href: "/tools/exam-audit",
    popular: true,
    badge: "Mới",
    category: "exam-assessment",
    aliases: ["rà soát đề", "lỗi đề", "kiểm tra đề"],
    tags: ["Rà soát", "Đề kiểm tra", "Safe fix", "Word/PDF"],
  },
  {
    title: "Tạo ngân hàng câu hỏi",
    description: "Sinh danh sách câu hỏi theo chủ đề, loại câu hỏi và mức độ.",
    href: "/tools/question-bank-generator",
    category: "exam-assessment",
    aliases: ["ngân hàng", "câu hỏi", "trắc nghiệm"],
    tags: ["Câu hỏi", "Tái sử dụng"],
  },
  {
    title: "Ngân hàng câu hỏi",
    description: "Lưu, lọc, chỉnh sửa và tái sử dụng câu hỏi.",
    href: "/question-bank",
    category: "exam-assessment",
    popular: true,
    aliases: ["câu hỏi", "kho câu hỏi", "lưu câu hỏi"],
    tags: ["Kho câu hỏi", "Lọc nhanh"],
  },
  {
    title: "Nhập câu hỏi từ văn bản/CSV",
    description: "Phân tích câu hỏi đã có và lưu vào ngân hàng câu hỏi.",
    href: "/tools/import-questions",
    category: "exam-assessment",
    badge: "Import",
    aliases: ["csv", "nhập câu hỏi", "import"],
    tags: ["CSV", "Văn bản"],
  },
  {
    title: "Tạo biến thể câu hỏi",
    description: "Tạo nhiều phiên bản câu hỏi từ câu gốc.",
    href: "/tools/question-variant-generator",
    category: "exam-assessment",
    aliases: ["biến thể", "đổi câu hỏi", "tương tự"],
    tags: ["Biến thể", "Câu hỏi"],
  },
  {
    title: "Trộn mã đề",
    description: "Trộn câu hỏi, đáp án và tạo bảng đáp án theo mã đề.",
    href: "/tools/exam-mixer",
    category: "exam-assessment",
    popular: true,
    badge: "Mới",
    aliases: ["trộn đề", "mã đề", "đảo câu"],
    tags: ["Mã đề", "Đáp án"],
  },
  {
    title: "Soạn giáo án",
    description: "Soạn kế hoạch bài dạy có mục tiêu, hoạt động và đánh giá.",
    href: "/tools/lesson-plan-generator",
    category: "lesson-materials",
    popular: true,
    aliases: ["giáo án", "kế hoạch bài dạy", "bài dạy"],
    tags: ["Kế hoạch", "Hoạt động"],
    example: "Ví dụ: giáo án Ngữ văn 9, bài dạy 45 phút",
  },
  {
    title: "Tạo phiếu học tập",
    description: "Chuẩn bị phiếu học tập có bài tập, nhiệm vụ và đáp án.",
    href: "/tools/worksheet-generator",
    category: "lesson-materials",
    popular: true,
    aliases: ["phiếu", "worksheet", "bài tập", "nhiệm vụ"],
    tags: ["Word/PDF", "Bài tập", "Đáp án"],
    example: "Ví dụ: phiếu học tập Toán 8, hoạt động nhóm",
  },
  {
    title: "Tạo hoạt động lớp học",
    description: "Gợi ý hoạt động có mục tiêu, cách tổ chức và đánh giá.",
    href: "/tools/activity-generator",
    category: "lesson-materials",
    aliases: ["hoạt động", "trò chơi", "lớp học"],
    tags: ["Hoạt động", "Tổ chức lớp"],
  },
  {
    title: "Tạo bài tập phân hóa",
    description: "Tạo bài tập theo mức cơ bản, vừa và nâng cao.",
    href: "/tools/differentiated-exercises",
    category: "lesson-materials",
    aliases: ["phân hóa", "bài tập", "nâng cao"],
    tags: ["Phân hóa", "Bài tập"],
  },
  {
    title: "Tạo slide bài giảng",
    description: "Tạo dàn ý, chỉnh sửa slide có cấu trúc và xuất PowerPoint học sinh hoặc giáo viên.",
    href: "/tools/lesson-slides",
    category: "lesson-materials",
    popular: true,
    badge: "Mới",
    aliases: ["slide", "powerpoint", "bài giảng", "trình chiếu", "pptx"],
    tags: ["PowerPoint", "Bài giảng", "PPTX"],
    example: "Ví dụ: Vật lí 11 – Định luật Ohm, 12 slide",
  },
  {
    title: "Tạo dàn ý slide bài giảng",
    description: "Tạo cấu trúc slide, bullet, minh họa và câu hỏi nhanh.",
    href: "/tools/slide-outline-generator",
    category: "lesson-materials",
    aliases: ["slide", "powerpoint", "bài giảng"],
    tags: ["Slide", "Dàn ý"],
  },
  {
    title: "Tóm tắt bài học",
    description: "Tóm tắt kiến thức trọng tâm, từ khóa và câu hỏi ôn tập.",
    href: "/tools/lesson-summary",
    category: "lesson-materials",
    aliases: ["tóm tắt", "ôn tập", "kiến thức"],
    tags: ["Tóm tắt", "Ôn tập"],
  },
  {
    title: "Tạo sơ đồ tư duy",
    description: "Tạo outline sơ đồ tư duy dạng text với nhánh chính và từ khóa.",
    href: "/tools/mindmap-outline",
    category: "lesson-materials",
    aliases: ["sơ đồ tư duy", "mindmap", "nhánh"],
    tags: ["Mindmap", "Outline"],
  },
  {
    title: "Viết nhận xét học sinh",
    description: "Viết nhận xét tự nhiên, tích cực và dễ chỉnh sửa.",
    href: "/tools/student-comments",
    category: "homeroom-parent",
    popular: true,
    aliases: ["nhận xét", "học sinh", "cuối kỳ", "tiến bộ"],
    tags: ["Nhận xét", "Chủ nhiệm"],
    example: "Ví dụ: nhận xét cuối kỳ, nhận xét tiến bộ",
  },
  {
    title: "Nhận xét học sinh hàng loạt",
    description: "Nhập danh sách và tạo nhận xét cho nhiều học sinh cùng lúc.",
    href: "/tools/bulk-student-comments",
    category: "homeroom-parent",
    popular: true,
    badge: "CSV",
    aliases: ["hàng loạt", "csv", "nhận xét nhiều học sinh"],
    tags: ["CSV", "Nhận xét"],
  },
  {
    title: "Soạn tin nhắn phụ huynh",
    description: "Soạn tin nhắn ngắn, trang trọng và thân thiện.",
    href: "/tools/parent-message-generator",
    category: "homeroom-parent",
    popular: true,
    aliases: ["phụ huynh", "tin nhắn", "zalo", "thông báo"],
    tags: ["Phụ huynh", "Tin nhắn"],
    example: "Ví dụ: nhắc học bài, báo tiến bộ, mời họp",
  },
  {
    title: "Tạo kế hoạch chủ nhiệm",
    description: "Tạo kế hoạch chủ nhiệm tuần/tháng và phối hợp phụ huynh.",
    href: "/tools/homeroom-plan",
    category: "homeroom-parent",
    aliases: ["chủ nhiệm", "kế hoạch", "tuần"],
    tags: ["Chủ nhiệm", "Kế hoạch"],
  },
  {
    title: "Tạo biên bản họp phụ huynh",
    description: "Soạn biên bản họp có nội dung, ý kiến và kết luận.",
    href: "/tools/parent-meeting-minutes",
    category: "homeroom-parent",
    aliases: ["biên bản", "họp phụ huynh", "cuộc họp"],
    tags: ["Biên bản", "Phụ huynh"],
  },
  {
    title: "Chuyển công thức sang LaTeX",
    description: "Chuyển công thức dạng text nhập tay sang LaTeX.",
    href: "/tools/latex-converter",
    category: "formula-latex",
    aliases: ["latex", "công thức", "toán"],
    tags: ["LaTeX", "Toán học"],
  },
  {
    title: "Ảnh công thức → LaTeX",
    description: "Nhận diện công thức từ ảnh đã cắt gọn.",
    href: "/tools/image-to-latex",
    category: "formula-latex",
    popular: true,
    badge: "Beta",
    aliases: ["latex", "ảnh công thức", "hình học", "tikz", "toán", "công thức"],
    tags: ["LaTeX", "Toán học", "Sao chép nhanh"],
    example: "Ví dụ: phân số, căn thức, ma trận, hình học → TikZ",
  },
  {
    title: "Preview LaTeX",
    description: "Nhập LaTeX và xem preview công thức bằng KaTeX.",
    href: "/tools/latex-preview",
    category: "formula-latex",
    aliases: ["preview", "xem trước", "latex"],
    tags: ["Preview", "LaTeX"],
  },
  {
    title: "Ngân hàng TikZ",
    description: "Lưu và sao chép nhanh mã TikZ cho hình học, đồ thị và bài giảng.",
    href: "/tikz-bank",
    category: "formula-latex",
    popular: true,
    aliases: ["tikz", "latex", "hình học", "đồ thị", "mã vẽ hình", "kho tikz"],
    tags: ["TikZ", "LaTeX", "Hình học", "Sao chép nhanh"],
    example: "Ví dụ: tam giác, đường tròn, đồ thị, hình học không gian",
  },
  {
    title: "Tạo mô phỏng 3D",
    description: "Tạo cảnh 3D đơn giản từ mô tả để minh họa bài học.",
    href: "/tools/3d-animation",
    category: "visual-tools",
    badge: "Beta",
    popular: true,
    aliases: ["3d", "mô phỏng", "chuyển động", "trực quan", "vật lý", "hóa học"],
    tags: ["3D", "Minh họa", "Beta"],
    example: "Ví dụ: Trái Đất quay quanh Mặt Trời, con lắc đơn, phân tử H2O",
  },
  {
    title: "Mẫu cá nhân",
    description: "Tạo, sửa, xóa và copy mẫu tài liệu cá nhân.",
    href: "/templates",
    category: "personalization",
    aliases: ["mẫu", "template", "cá nhân"],
    tags: ["Mẫu", "Cá nhân"],
  },
];

export function getToolSearchText(tool: ToolMeta) {
  return [
    tool.title,
    tool.description,
    categoryLabels[tool.category],
    ...(tool.aliases || []),
    ...(tool.tags || []),
    tool.example || "",
  ].join(" ").toLowerCase();
}
