import { auditStructuredExam } from "@/lib/exam-audit/audit";
import type { ExamQuestion, StructuredExam } from "@/lib/exam-types";
import type { GeneratedDocument, QuestionItem } from "@/lib/types";
import type { Worksheet, WorksheetActivity, WorksheetLevel } from "@/lib/worksheet/types";
import { createWorksheetDraft, generateFallbackActivity, normalizeWorksheet, stableWorksheetHash, worksheetQuestions, worksheetToDocument } from "@/lib/worksheet/workflow";
import type { ExerciseTypeSection, FormulaSection, KnowledgeSection, ReviewOutlineItem, ReviewPack, ReviewPackValidation, ReviewSectionType, ReviewSourcePreview, WorkedExample } from "@/lib/review-pack/types";

export const REVIEW_PACK_VERSION = "1.0";
export function reviewId(prefix = "review") { return typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
export function reviewSectionCacheKey(pack: ReviewPack, item: ReviewOutlineItem, source?: ReviewSourcePreview) { return stableWorksheetHash({ version: REVIEW_PACK_VERSION, source: source?.text || pack.metadata.sourceHash || "manual", subject: pack.subject, grade: pack.grade, topic: pack.topic, item }); }
const cleanLines = (value: string) => value.split(/\r?\n/).map((line) => line.replace(/^#{1,5}\s*|^[-*•\d.)\s]+/, "").trim()).filter(Boolean);
const normalizeText = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d").replace(/Đ/g, "D").toLocaleLowerCase("vi").replace(/[^a-z0-9]+/g, " ").trim();

export function defaultReviewSettings(): ReviewPack["settings"] { return { includeKnowledge: true, includeFormulas: true, includeSummaryTable: false, includeExerciseTypes: true, includeWorkedExamples: true, includeBasicPractice: true, includeApplicationPractice: true, includeAdvancedPractice: false, includeQuickQuiz: true, includeAnswers: true, includeDetailedSolutions: true, includeTeacherNotes: false, sourceOnly: false, detailLevel: "standard", differentiation: "basic_advanced", exerciseCount: 10, quizCount: 5, quizType: "mixed", questionBankMode: "new_only" }; }

export function createReviewPackDraft(input: Partial<ReviewPack> = {}): ReviewPack {
  const now = new Date().toISOString();
  return { id: input.id || reviewId(), title: input.title || "ĐỀ CƯƠNG ÔN TẬP", subject: input.subject || "", grade: input.grade || "", topic: input.topic || "", textbookSeries: input.textbookSeries || "", purpose: input.purpose || "chapter", estimatedMinutes: input.estimatedMinutes || 90, notes: input.notes || "", outline: input.outline || [], knowledgeSections: input.knowledgeSections || [], formulaSections: input.formulaSections || [], summaryRows: input.summaryRows || [], exerciseTypes: input.exerciseTypes || [], workedExamples: input.workedExamples || [], practiceActivities: input.practiceActivities || [], quickQuiz: input.quickQuiz, solutions: input.solutions, teacherNotes: input.teacherNotes || [], settings: { ...defaultReviewSettings(), ...input.settings }, metadata: { sourceType: "manual", createdAt: now, updatedAt: now, version: REVIEW_PACK_VERSION, ...input.metadata } };
}

export function normalizeReviewPack(input: ReviewPack): ReviewPack {
  const draft = createReviewPackDraft(input);
  return { ...draft, ...input, outline: (input.outline || []).map((item, index) => ({ ...item, id: item.id || reviewId("section"), order: index + 1, sourceCoverage: item.sourceCoverage || [], generationStatus: item.generationStatus || "outline" })), knowledgeSections: (input.knowledgeSections || []).map((item) => ({ ...item, id: item.id || reviewId("knowledge") })), formulaSections: (input.formulaSections || []).map((item) => ({ ...item, id: item.id || reviewId("formula"), symbols: item.symbols || [] })), summaryRows: (input.summaryRows || []).map((item) => ({ ...item, id: item.id || reviewId("row") })), exerciseTypes: (input.exerciseTypes || []).map((item) => ({ ...item, id: item.id || reviewId("type"), method: item.method || [], commonMistakes: item.commonMistakes || [], workedExampleIds: item.workedExampleIds || [], practiceActivityIds: item.practiceActivityIds || [] })), workedExamples: (input.workedExamples || []).map((item) => ({ ...item, id: item.id || reviewId("example"), steps: item.steps || [] })), practiceActivities: normalizeWorksheet({ ...createWorksheetDraft(), activities: input.practiceActivities || [] }).activities, settings: { ...draft.settings, ...input.settings }, metadata: { ...draft.metadata, ...input.metadata, version: REVIEW_PACK_VERSION, updatedAt: new Date().toISOString() } };
}

const sectionInfo: Record<ReviewSectionType, [string, string, ReviewOutlineItem["level"]]> = {
  knowledge: ["Kiến thức trọng tâm", "Tóm tắt khái niệm, quy tắc và điều kiện cần nhớ", "standard"], formula: ["Công thức cần nhớ", "Giữ công thức, đơn vị, ký hiệu và điều kiện sử dụng", "standard"], summary_table: ["Bảng tổng hợp", "Đối chiếu khái niệm và ý chính", "standard"], exercise_types: ["Các dạng bài thường gặp", "Nhận diện dạng và phương pháp giải", "mixed"], worked_examples: ["Ví dụ mẫu", "Minh họa phương pháp theo từng bước", "standard"], basic_practice: ["Bài tập cơ bản", "Củng cố trực tiếp và có gợi ý", "basic"], application_practice: ["Bài tập vận dụng", "Vận dụng kiến thức trong tình huống chuẩn", "standard"], advanced_practice: ["Bài tập nâng cao", "Kết hợp kiến thức và giảm hỗ trợ", "advanced"], quick_quiz: ["Tự kiểm tra nhanh", "Kiểm tra mức nắm kiến thức sau ôn tập", "mixed"], answers: ["Đáp án", "Đáp án tách riêng cho giáo viên", "mixed"], solutions: ["Lời giải chi tiết", "Các bước giải và lưu ý lỗi thường gặp", "mixed"], teacher_notes: ["Ghi chú giáo viên", "Gợi ý tổ chức và hỗ trợ học sinh", "mixed"] };

export function createReviewOutline(pack: ReviewPack, source?: ReviewSourcePreview): ReviewOutlineItem[] {
  const enabled: ReviewSectionType[] = [];
  const s = pack.settings;
  if (s.includeKnowledge) enabled.push("knowledge"); if (s.includeFormulas) enabled.push("formula"); if (s.includeSummaryTable) enabled.push("summary_table"); if (s.includeExerciseTypes) enabled.push("exercise_types"); if (s.includeWorkedExamples) enabled.push("worked_examples"); if (s.includeBasicPractice) enabled.push("basic_practice"); if (s.includeApplicationPractice) enabled.push("application_practice"); if (s.includeAdvancedPractice) enabled.push("advanced_practice"); if (s.includeQuickQuiz) enabled.push("quick_quiz"); if (s.includeAnswers) enabled.push("answers"); if (s.includeDetailedSolutions) enabled.push("solutions"); if (s.includeTeacherNotes) enabled.push("teacher_notes");
  const practiceCount = Math.max(1, Math.floor(s.exerciseCount / Math.max(1, enabled.filter((type) => type.endsWith("practice")).length)));
  return enabled.map((type, index) => { const [title, purpose, level] = sectionInfo[type]; return { id: reviewId("section"), order: index + 1, type, title, purpose, estimatedLength: ["knowledge", "exercise_types", "solutions"].includes(type) ? "long" : "medium", exerciseCount: type.endsWith("practice") ? practiceCount : type === "worked_examples" ? 2 : type === "quick_quiz" ? s.quizCount : 0, level, sourceCoverage: source?.keyKnowledge.slice(0, 3) || [], generationStatus: "outline" }; });
}

function sourceLines(source: ReviewSourcePreview | undefined, pack: ReviewPack) { const lines = cleanLines(source?.text || ""); if (lines.length) return lines; return [`${pack.topic || "Chủ đề"}: giáo viên bổ sung kiến thức trọng tâm đã xác nhận.`, `Mục tiêu ôn tập ${pack.topic || "chủ đề"} theo yêu cầu của lớp ${pack.grade || "đang dạy"}.`]; }
function levelFor(type: ReviewSectionType): WorksheetLevel { return type === "basic_practice" ? "basic" : type === "advanced_practice" ? "advanced" : "standard"; }
function activityType(index: number): WorksheetActivity["type"] { return (["multiple_choice", "true_false", "short_answer", "fill_blank", "matching", "ordering", "problem_solving"] as const)[index % 7]; }

function makePractice(pack: ReviewPack, item: ReviewOutlineItem, start: number): WorksheetActivity[] {
  const worksheet = createWorksheetDraft({ subject: pack.subject, grade: pack.grade, topic: pack.topic, differentiation: pack.settings.differentiation, settings: { ...createWorksheetDraft().settings, activityCount: Math.max(2, item.exerciseCount) } });
  return Array.from({ length: item.exerciseCount }, (_, index) => generateFallbackActivity({ id: reviewId("activity"), order: start + index + 1, title: `${item.title} ${index + 1}`, type: activityType(start + index), level: levelFor(item.type), purpose: "review", prompt: "", instructions: "Hoàn thành nhiệm vụ theo yêu cầu.", expectedOutput: "Câu trả lời có căn cứ.", estimatedMinutes: 4, answerSpace: "three_lines", learningOutcome: `Củng cố ${pack.topic || "chủ đề"}`, generationStatus: "outline" }, worksheet));
}

function createQuiz(pack: ReviewPack, count: number): StructuredExam {
  const types = pack.settings.quizType === "mixed" ? ["multiple_choice", "true_false", "short_answer"] as const : [pack.settings.quizType] as const;
  const questions = Array.from({ length: count }, (_, index): ExamQuestion => { const part = types[index % types.length]; const common = { id: reviewId("quiz"), part, number: index + 1, stem: `Câu ${index + 1}. Kiểm tra nhanh kiến thức về ${pack.topic || "chủ đề"}.`, answer: part === "multiple_choice" ? "A" : part === "true_false" ? "Đúng; Sai; Đúng; Đúng" : `Nội dung đúng về ${pack.topic || "chủ đề"}`, explanation: `Đối chiếu kiến thức trọng tâm về ${pack.topic || "chủ đề"}.`, score: Number((10 / count).toFixed(3)), difficulty: index < Math.ceil(count * .4) ? "Nhận biết" as const : index < Math.ceil(count * .8) ? "Thông hiểu" as const : "Vận dụng" as const, topic: pack.topic || "Chủ đề ôn tập" }; return part === "multiple_choice" ? { ...common, options: { A: `Nhận định đúng về ${pack.topic || "chủ đề"}`, B: "Nhận định nhiễu 1", C: "Nhận định nhiễu 2", D: "Nhận định nhiễu 3" } } : part === "true_false" ? { ...common, trueFalseItems: [{ label: "a", text: `Mệnh đề đúng về ${pack.topic || "chủ đề"}`, answer: true }, { label: "b", text: "Mệnh đề cần bác bỏ", answer: false }, { label: "c", text: "Mệnh đề đúng thứ hai", answer: true }, { label: "d", text: "Mệnh đề đúng thứ ba", answer: true }] } : common; });
  const parts: StructuredExam["parts"] = (["multiple_choice", "true_false", "short_answer"] as const).map((type) => ({ type, title: type === "multiple_choice" ? "PHẦN I. TRẮC NGHIỆM" : type === "true_false" ? "PHẦN II. ĐÚNG/SAI" : "PHẦN III. TRẢ LỜI NGẮN", instruction: "Thực hiện theo yêu cầu.", questions: questions.filter((question) => question.part === type).map((question, index) => ({ ...question, number: index + 1 })) })).filter((part) => part.questions.length);
  return { metadata: { title: `Tự kiểm tra - ${pack.topic || "Ôn tập"}`, examStyle: "Kiểm tra nhanh", subject: pack.subject || "", grade: pack.grade || "", duration: `${Math.max(5, count * 2)} phút`, examCode: "REVIEW", totalScore: 10 }, parts, teacherOnly: { scoringGuide: "Chấm theo đáp án đã xác nhận.", matrix: "", specification: "", notes: "Giáo viên cần rà soát trước khi sử dụng." } };
}

function quizSolutions(exam: StructuredExam): ReviewPack["solutions"] { const questions = exam.parts.flatMap((part) => part.questions.map((question) => ({ questionId: question.id, questionNumber: question.number, sectionId: part.type, questionType: question.part, currentAnswer: question.answer, verifiedAnswer: question.answer, answerStatus: "matches" as const, confidence: "high" as const, conciseAnswer: String(question.answer), detailedSolution: question.explanation, steps: [{ order: 1, title: "Đối chiếu kiến thức", content: question.explanation, result: String(question.answer) }], contentHash: stableWorksheetHash(question), teacherConfirmed: true }))); return { examHash: stableWorksheetHash(exam), generatedAt: new Date().toISOString(), verificationStatus: "verified", questions, summary: { totalQuestions: questions.length, verifiedCount: questions.length, mismatchCount: 0, uncertainCount: 0, missingSolutionCount: 0, deterministicVerifiedCount: questions.length, semanticReviewedCount: 0, cacheHitCount: 0 }, metadata: { detailLevel: "detailed", sourceType: "review-pack", solutionVersion: "1.0" } }; }

export function generateReviewSection(packInput: ReviewPack, outlineId: string, source?: ReviewSourcePreview, force = false): ReviewPack {
  const pack = normalizeReviewPack(packInput); const item = pack.outline.find((entry) => entry.id === outlineId); if (!item) return pack;
  const edited = item.type === "knowledge" ? pack.knowledgeSections.find((entry) => entry.id === item.id)?.teacherEdited
    : item.type === "formula" ? pack.formulaSections.find((entry) => entry.id === item.id)?.teacherEdited
    : item.type === "exercise_types" ? pack.exerciseTypes.find((entry) => entry.id === item.id)?.teacherEdited
    : item.type === "worked_examples" ? pack.workedExamples.find((entry) => entry.id.startsWith(`${item.id}-`))?.teacherEdited
    : item.type.endsWith("practice") ? pack.practiceActivities.some((entry) => entry.sourceSectionId === item.id && entry.teacherEdited)
    : item.teacherEdited;
  if (edited && !force) return pack;
  const lines = sourceLines(source, pack); const slice = lines.slice(0, item.estimatedLength === "short" ? 3 : item.estimatedLength === "long" ? 10 : 6); const next: ReviewPack = { ...pack };
  if (item.type === "knowledge") { const section: KnowledgeSection = { id: item.id, title: item.title, summary: slice[0] || `Kiến thức ${pack.topic}`, keyPoints: slice.slice(0, 6), shortExample: slice.find((line) => /ví dụ/i.test(line)), commonMistake: "Nhầm điều kiện áp dụng hoặc bỏ sót dữ kiện quan trọng." }; next.knowledgeSections = [...pack.knowledgeSections.filter((entry) => entry.id !== item.id), section]; }
  if (item.type === "formula") { const formulas = lines.filter((line) => /\\[a-z]+|\$[^$]+\$|=/.test(line)).slice(0, 5); const section: FormulaSection = { id: item.id, title: item.title, latex: formulas.join("\n") || `\\text{Giáo viên bổ sung công thức đã xác nhận cho ${pack.topic || "chủ đề"}}`, symbols: [], conditions: "Kiểm tra điều kiện và đơn vị trước khi áp dụng.", example: formulas[0] }; next.formulaSections = [...pack.formulaSections.filter((entry) => entry.id !== item.id), section]; }
  if (item.type === "summary_table") next.summaryRows = slice.map((line) => ({ id: reviewId("row"), concept: line.split(/[:–-]/)[0], keyPoint: line, example: "" }));
  if (item.type === "exercise_types") { const section: ExerciseTypeSection = { id: item.id, title: `Nhận diện và xử lý dạng bài về ${pack.topic || "chủ đề"}`, recognitionSignal: `Đề bài yêu cầu vận dụng trực tiếp hoặc kết hợp kiến thức ${pack.topic || "chủ đề"}.`, method: ["Xác định dữ kiện và yêu cầu.", "Chọn kiến thức hoặc công thức phù hợp.", "Thực hiện từng bước và kiểm tra kết quả."], commonMistakes: ["Bỏ sót dữ kiện.", "Dùng kiến thức không đúng điều kiện."], workedExampleIds: pack.workedExamples.map((entry) => entry.id), practiceActivityIds: pack.practiceActivities.map((entry) => entry.id) }; next.exerciseTypes = [...pack.exerciseTypes.filter((entry) => entry.id !== item.id), section]; }
  if (item.type === "worked_examples") { const examples: WorkedExample[] = Array.from({ length: Math.max(1, item.exerciseCount) }, (_, index) => ({ id: `${item.id}-${index + 1}`, title: `Ví dụ ${index + 1}`, prompt: slice[index] || `Thực hiện một nhiệm vụ mẫu về ${pack.topic || "chủ đề"}.`, method: "Xác định yêu cầu, chọn kiến thức phù hợp và trình bày theo từng bước.", steps: ["Đọc và tóm tắt dữ kiện.", "Áp dụng kiến thức trọng tâm.", "Kiểm tra và kết luận."], finalAnswer: `Kết quả cần phù hợp với yêu cầu về ${pack.topic || "chủ đề"}.`, note: "Giáo viên rà soát dữ kiện và kết quả trước khi sử dụng." })); next.workedExamples = [...pack.workedExamples.filter((entry) => !entry.id.startsWith(`${item.id}-`)), ...examples]; }
  if (item.type.endsWith("practice")) { const existing = pack.practiceActivities.filter((entry) => entry.sourceSectionId !== item.id); const generated = makePractice(pack, item, existing.length).map((activity) => ({ ...activity, sourceSectionId: item.id })); next.practiceActivities = [...existing, ...generated].map((activity, index) => ({ ...activity, order: index + 1 })); }
  if (item.type === "quick_quiz") { next.quickQuiz = createQuiz(pack, item.exerciseCount || pack.settings.quizCount); next.solutions = quizSolutions(next.quickQuiz); }
  if (item.type === "answers" && next.quickQuiz && !next.solutions) next.solutions = quizSolutions(next.quickQuiz);
  if (item.type === "solutions" && next.quickQuiz) next.solutions = quizSolutions(next.quickQuiz);
  if (item.type === "teacher_notes") next.teacherNotes = [`Dành ${pack.estimatedMinutes} phút để tổ chức ôn tập.`, "Ưu tiên hỗ trợ học sinh ở các dạng bài còn sai nhiều.", "Nội dung là bản nháp cần giáo viên rà soát."];
  next.outline = next.outline.map((entry) => entry.id === item.id ? { ...entry, generationStatus: "ready" } : entry); return normalizeReviewPack(next);
}

function reviewJson(value: string): Record<string, unknown> | null {
  const cleaned = value.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  const candidates = [cleaned, cleaned.slice(cleaned.indexOf("{"), cleaned.lastIndexOf("}") + 1)];
  for (const candidate of candidates) { if (!candidate.startsWith("{")) continue; try { const parsed = JSON.parse(candidate); if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) return parsed as Record<string, unknown>; } catch { /* dùng fallback xác định */ } }
  return null;
}
const textValue = (value: unknown) => typeof value === "string" ? value.trim() : "";
const textRows = (value: unknown) => Array.isArray(value) ? value.map(textValue).filter(Boolean) : [];

export function parseGeneratedReviewSection(content: string, packInput: ReviewPack, outlineId: string, source?: ReviewSourcePreview, structuredExam?: unknown): ReviewPack {
  let pack = generateReviewSection(packInput, outlineId, source);
  const item = pack.outline.find((entry) => entry.id === outlineId); const data = reviewJson(content); if (!item || !data) return pack;
  if (item.type === "knowledge") { const current = pack.knowledgeSections.find((entry) => entry.id === item.id); if (current) pack = { ...pack, knowledgeSections: pack.knowledgeSections.map((entry) => entry.id === item.id ? { ...entry, title: textValue(data.title) || entry.title, summary: textValue(data.summary) || entry.summary, keyPoints: textRows(data.keyPoints).length ? textRows(data.keyPoints) : entry.keyPoints, shortExample: textValue(data.shortExample) || entry.shortExample, commonMistake: textValue(data.commonMistake) || entry.commonMistake } : entry) }; }
  if (item.type === "formula") { const current = pack.formulaSections.find((entry) => entry.id === item.id); const symbols = Array.isArray(data.symbols) ? data.symbols.flatMap((raw) => { if (!raw || typeof raw !== "object") return []; const row = raw as Record<string, unknown>; const symbol = textValue(row.symbol); const meaning = textValue(row.meaning); return symbol && meaning ? [{ symbol, meaning, unit: textValue(row.unit) || undefined }] : []; }) : []; if (current) pack = { ...pack, formulaSections: pack.formulaSections.map((entry) => entry.id === item.id ? { ...entry, title: textValue(data.title) || entry.title, latex: textValue(data.latex) || entry.latex, symbols: symbols.length ? symbols : entry.symbols, conditions: textValue(data.conditions) || entry.conditions, example: textValue(data.example) || entry.example } : entry) }; }
  if (item.type === "summary_table" && Array.isArray(data.rows)) { const rows = data.rows.flatMap((raw, index) => { if (!raw || typeof raw !== "object") return []; const row = raw as Record<string, unknown>; const concept = textValue(row.concept); const keyPoint = textValue(row.keyPoint); return concept && keyPoint ? [{ id: `${item.id}-${index + 1}`, concept, keyPoint, example: textValue(row.example) || undefined }] : []; }); if (rows.length) pack = { ...pack, summaryRows: rows }; }
  if (item.type === "exercise_types") { const current = pack.exerciseTypes.find((entry) => entry.id === item.id); if (current) pack = { ...pack, exerciseTypes: pack.exerciseTypes.map((entry) => entry.id === item.id ? { ...entry, title: textValue(data.title) || entry.title, recognitionSignal: textValue(data.recognitionSignal) || entry.recognitionSignal, method: textRows(data.method).length ? textRows(data.method) : entry.method, commonMistakes: textRows(data.commonMistakes).length ? textRows(data.commonMistakes) : entry.commonMistakes } : entry) }; }
  if (item.type === "worked_examples" && Array.isArray(data.examples)) { const examples = data.examples.flatMap((raw, index) => { if (!raw || typeof raw !== "object") return []; const row = raw as Record<string, unknown>; const prompt = textValue(row.prompt); const finalAnswer = textValue(row.finalAnswer); const steps = textRows(row.steps); return prompt && finalAnswer && steps.length ? [{ id: `${item.id}-${index + 1}`, title: textValue(row.title) || `Ví dụ ${index + 1}`, prompt, method: textValue(row.method) || "Phân tích dữ kiện và thực hiện theo từng bước.", steps, finalAnswer, note: textValue(row.note) || undefined, formula: textValue(row.formula) || undefined }] : []; }); if (examples.length) pack = { ...pack, workedExamples: [...pack.workedExamples.filter((entry) => !entry.id.startsWith(`${item.id}-`)), ...examples] }; }
  if (item.type.endsWith("practice") && Array.isArray(data.activities)) { const allowed = new Set<WorksheetActivity["type"]>(["multiple_choice", "true_false", "short_answer", "fill_blank", "matching", "ordering", "table_completion", "problem_solving", "discussion", "diagram_labeling"]); const current = pack.practiceActivities.filter((entry) => entry.sourceSectionId === item.id); const generated = data.activities.flatMap((raw, index) => { if (!raw || typeof raw !== "object") return []; const row = raw as Record<string, unknown>; const prompt = textValue(row.prompt); if (!prompt) return []; const fallback = current[index] || makePractice(pack, item, index)[0]; const type = allowed.has(row.type as WorksheetActivity["type"]) ? row.type as WorksheetActivity["type"] : fallback.type; const level = ["basic", "standard", "advanced"].includes(textValue(row.level)) ? textValue(row.level) as WorksheetLevel : fallback.level; return [{ ...fallback, id: current[index]?.id || `${item.id}-${index + 1}`, sourceSectionId: item.id, title: textValue(row.title) || fallback.title, type, level, prompt, answer: textValue(row.answer) || fallback.answer, explanation: textValue(row.explanation) || fallback.explanation, hint: textValue(row.hint) || fallback.hint, generationStatus: "ready" as const }]; }); if (generated.length) pack = { ...pack, practiceActivities: [...pack.practiceActivities.filter((entry) => entry.sourceSectionId !== item.id), ...generated].map((entry, index) => ({ ...entry, order: index + 1 })) }; }
  if (item.type === "quick_quiz" && structuredExam && typeof structuredExam === "object") { const exam = structuredExam as StructuredExam; if (exam.metadata && Array.isArray(exam.parts)) pack = { ...pack, quickQuiz: exam, solutions: quizSolutions(exam) }; }
  if (item.type === "teacher_notes") { const notes = textRows(data.teacherNotes); if (notes.length) pack = { ...pack, teacherNotes: notes }; }
  return normalizeReviewPack(pack);
}

export function validateReviewPack(pack: ReviewPack): ReviewPackValidation {
  const errors: string[] = []; const warnings: string[] = []; const ids = new Set<string>();
  if (!pack.topic?.trim()) errors.push("Chưa có chủ đề ôn tập."); if (!pack.outline.length) errors.push("Đề cương chưa có cấu trúc phần.");
  pack.outline.forEach((item) => { if (ids.has(item.id)) errors.push(`Phần “${item.title}” bị trùng ID.`); ids.add(item.id); if (!item.title.trim()) errors.push("Có phần chưa có tiêu đề."); if (item.generationStatus === "failed") warnings.push(`Phần “${item.title}” chưa tạo được nội dung.`); });
  const prompts = new Set<string>(); pack.practiceActivities.forEach((activity) => { const key = normalizeText(activity.prompt); if (prompts.has(key)) errors.push(`Bài tập “${activity.title || activity.order}” bị trùng nội dung.`); prompts.add(key); });
  const sameLevel = new Map<string, Set<WorksheetLevel>>(); pack.practiceActivities.forEach((activity) => { const key = normalizeText(activity.prompt); const levels = sameLevel.get(key) || new Set<WorksheetLevel>(); levels.add(activity.level); sameLevel.set(key, levels); }); if ([...sameLevel.values()].some((levels) => levels.size > 1)) warnings.push("Có bài tập phân hóa chỉ khác nhãn mức độ; cần viết lại dữ kiện hoặc mức hỗ trợ.");
  pack.formulaSections.forEach((item) => { if (!item.latex.trim()) errors.push(`Phần “${item.title}” chưa có công thức.`); const left = (item.latex.match(/\{/g) || []).length; const right = (item.latex.match(/\}/g) || []).length; if (left !== right) errors.push(`Công thức trong “${item.title}” có ngoặc LaTeX chưa cân bằng.`); });
  pack.workedExamples.forEach((item) => { if (!item.finalAnswer.trim()) errors.push(`Ví dụ “${item.title}” chưa có đáp án.`); if (!item.steps.length) errors.push(`Ví dụ “${item.title}” chưa có các bước giải.`); });
  if (pack.quickQuiz) { const audit = auditStructuredExam(pack.quickQuiz, { totalScore: pack.quickQuiz.metadata.totalScore }); if (audit.summary.errorCount) errors.push(`Bài tự kiểm tra còn ${audit.summary.errorCount} lỗi cấu trúc.`); if (audit.summary.warningCount) warnings.push(`Bài tự kiểm tra có ${audit.summary.warningCount} cảnh báo cần rà soát.`); }
  const status = errors.length ? "blocked" : warnings.length ? "warning" : "ready"; return { valid: !errors.length, status, errors, warnings, sectionCount: pack.outline.length, exerciseCount: pack.practiceActivities.length, quizQuestionCount: pack.quickQuiz?.parts.flatMap((part) => part.questions).length || 0 };
}

export function reviewSourceFromDocument(document: GeneratedDocument, sourceActivityIds: string[] = []): ReviewSourcePreview {
  if (document.reviewPack) return { title: document.title, sourceType: "saved_review", sourceDocumentId: document.id, subject: document.reviewPack.subject, grade: document.reviewPack.grade, topic: document.reviewPack.topic, text: reviewPackToText(document.reviewPack, "teacher"), objectives: document.reviewPack.knowledgeSections.flatMap((item) => item.keyPoints), keyKnowledge: document.reviewPack.knowledgeSections.flatMap((item) => item.keyPoints), confirmed: true, warnings: [] };
  if (document.lessonPlan) { const activities = document.lessonPlan.periods.flatMap((period) => period.activities).filter((item) => !sourceActivityIds.length || sourceActivityIds.includes(item.id)); return { title: document.title, sourceType: "lesson_plan", sourceDocumentId: document.id, subject: document.lessonPlan.subject, grade: document.lessonPlan.grade, topic: document.lessonPlan.topic, text: activities.map((item) => `${item.title}\n${item.content}\n${item.expectedProduct || ""}\n${item.assessmentEvidence || ""}`).join("\n\n"), objectives: document.lessonPlan.objectives.filter((objective) => !sourceActivityIds.length || activities.some((item) => item.objectiveIds.includes(objective.id))).map((item) => item.content), keyKnowledge: document.lessonPlan.keyKnowledge || [], confirmed: true, warnings: [] }; }
  if (document.slideDeck) { const visible = document.slideDeck.slides.filter((slide) => !slide.hidden); const texts = visible.flatMap((slide) => slide.blocks.filter((block) => !block.teacherOnly).map((block) => block.type === "bullets" ? block.content.join("; ") : block.type === "table" ? block.rows.map((row) => row.join(" | ")).join("\n") : block.type === "process" ? block.steps.join(" → ") : block.content)); return { title: document.title, sourceType: "slides", sourceDocumentId: document.id, subject: document.slideDeck.subject, grade: document.slideDeck.grade, topic: document.slideDeck.topic, text: texts.join("\n"), objectives: [], keyKnowledge: texts.slice(0, 20), confirmed: true, warnings: [] }; }
  if (document.worksheet) return { title: document.title, sourceType: "worksheet", sourceDocumentId: document.id, subject: document.worksheet.subject, grade: document.worksheet.grade, topic: document.worksheet.topic, text: document.content, objectives: document.worksheet.objectives || [], keyKnowledge: document.worksheet.keyKnowledge || [], confirmed: true, warnings: [] };
  if (document.gradingJob) { const confirmed = document.gradingJob.submissions.filter((item) => item.gradingResult?.confirmedByTeacher); const mistakes = confirmed.flatMap((item) => item.gradingResult?.questionResults.filter((result) => ["incorrect", "partial", "needs_teacher_review"].includes(result.status)).map((result) => `Câu ${result.questionNumber}: ${result.explanation || result.feedback || "Cần củng cố"}`) || []); return { title: document.title, sourceType: "grading_result", sourceDocumentId: document.id, text: mistakes.join("\n"), objectives: ["Củng cố các nội dung học sinh còn sai sau bài kiểm tra."], keyKnowledge: mistakes, confirmed: confirmed.length > 0 && confirmed.length === document.gradingJob.submissions.length, warnings: confirmed.length === document.gradingJob.submissions.length ? [] : ["Chỉ có thể tạo gói bổ sung từ bộ kết quả đã được giáo viên xác nhận đầy đủ."] }; }
  if (document.recognitionDraft) { const confirmed = document.recognitionDraft.reviewStatus === "confirmed"; const text = document.recognitionDraft.pages.flatMap((page) => page.blocks).filter((block) => block.reviewed && !block.excluded).map((block) => block.text).join("\n"); return { title: document.title, sourceType: "document", sourceDocumentId: document.id, text, objectives: [], keyKnowledge: cleanLines(text).slice(0, 20), confirmed, warnings: confirmed ? [] : ["Tài liệu nhận dạng chưa được giáo viên xác nhận."] }; }
  if (document.examSolutionSet) { const verified = document.examSolutionSet.verificationStatus === "verified"; const questions = document.examSolutionSet.questions.filter((item) => item.teacherConfirmed || item.answerStatus === "matches"); return { title: document.title, sourceType: "exam", sourceDocumentId: document.id, subject: document.generationMeta?.subject, grade: document.generationMeta?.grade, topic: document.generationMeta?.topic, text: questions.map((item) => `${item.conciseAnswer}\n${item.detailedSolution || ""}`).join("\n"), objectives: [], keyKnowledge: questions.map((item) => item.conciseAnswer), confirmed: verified, warnings: verified ? [] : ["Chỉ sử dụng lời giải đã được xác minh."] }; }
  const sourceType = document.type === "exam" ? "exam" : document.type === "question-bank" ? "question_bank" : "document"; return { title: document.title, sourceType, sourceDocumentId: document.id, subject: document.examMeta?.subject || document.generationMeta?.subject, grade: document.examMeta?.grade || document.generationMeta?.grade, topic: document.examMeta?.topic || document.generationMeta?.topic, text: document.content, objectives: cleanLines(document.content).filter((line) => /mục tiêu|yêu cầu cần đạt/i.test(line)).slice(0, 8), keyKnowledge: cleanLines(document.content).slice(0, 24), confirmed: true, warnings: [] };
}

function activityText(activity: WorksheetActivity, audience: "student" | "teacher") { const lines = [`${activity.order}. ${activity.title || "Bài tập"} · ${{ basic: "Cơ bản", standard: "Vận dụng", advanced: "Nâng cao" }[activity.level]}`, activity.prompt]; activity.items?.forEach((item, index) => { lines.push(`${index + 1}. ${item.prompt}`); item.options?.forEach((option) => lines.push(`${option.label}. ${option.text}`)); if (audience === "teacher") lines.push(`Đáp án: ${item.answer || "Cần rà soát"}`, item.explanation ? `Giải thích: ${item.explanation}` : ""); }); if (audience === "teacher") lines.push(`Đáp án: ${activity.answer || "Cần rà soát"}`, activity.explanation ? `Giải thích: ${activity.explanation}` : "", activity.commonMistake ? `Lỗi thường gặp: ${activity.commonMistake}` : ""); else lines.push("................................................................................................", "................................................................................................"); return lines.filter(Boolean); }

export function reviewPackToText(pack: ReviewPack, audience: "student" | "teacher" | "formula" | "practice" | "solutions" = "teacher") {
  const rows = [pack.title, `Môn: ${pack.subject || "—"} | Khối: ${pack.grade || "—"}`, `Chủ đề: ${pack.topic || "—"}`, ""];
  if (audience === "formula") { pack.formulaSections.forEach((item, index) => rows.push(`${index + 1}. ${item.title}`, item.latex, item.conditions ? `Điều kiện: ${item.conditions}` : "", item.example ? `Ví dụ: ${item.example}` : "")); return rows.filter(Boolean).join("\n"); }
  if (audience === "solutions") { pack.solutions?.questions.forEach((item) => rows.push(`Câu ${item.questionNumber}. ${item.conciseAnswer}`, item.detailedSolution || "", ...(item.steps || []).map((step) => `${step.order}. ${step.content}`))); return rows.filter(Boolean).join("\n"); }
  if (audience !== "practice") { pack.knowledgeSections.forEach((item, index) => rows.push(`I.${index + 1}. ${item.title}`, item.summary, ...item.keyPoints.map((point) => `• ${point}`), item.shortExample ? `Ví dụ ngắn: ${item.shortExample}` : "", audience === "teacher" && item.commonMistake ? `Lỗi thường gặp: ${item.commonMistake}` : "")); pack.formulaSections.forEach((item, index) => rows.push(`II.${index + 1}. ${item.title}`, item.latex, item.conditions ? `Điều kiện: ${item.conditions}` : "")); pack.exerciseTypes.forEach((item, index) => rows.push(`III.${index + 1}. ${item.title}`, `Dấu hiệu: ${item.recognitionSignal}`, ...item.method.map((step, stepIndex) => `${stepIndex + 1}. ${step}`), ...(audience === "teacher" ? item.commonMistakes.map((mistake) => `Lỗi thường gặp: ${mistake}`) : []))); pack.workedExamples.forEach((item, index) => rows.push(`IV.${index + 1}. ${item.title}`, item.prompt, `Phương pháp: ${item.method}`, ...(audience === "teacher" ? [...item.steps.map((step, stepIndex) => `${stepIndex + 1}. ${step}`), `Đáp án: ${item.finalAnswer}`, item.note || ""] : []))); }
  rows.push("V. BÀI TẬP LUYỆN TẬP"); pack.practiceActivities.forEach((activity) => rows.push(...activityText(activity, audience === "student" ? "student" : "teacher")));
  if (audience !== "practice" && pack.quickQuiz) { rows.push("VI. TỰ KIỂM TRA NHANH"); pack.quickQuiz.parts.forEach((part) => { rows.push(part.title, part.instruction); part.questions.forEach((question) => { rows.push(`Câu ${question.number}. ${question.stem}`); if (question.options) Object.entries(question.options).forEach(([key, value]) => rows.push(`${key}. ${value}`)); if (audience === "teacher") rows.push(`Đáp án: ${question.answer}`, `Giải thích: ${question.explanation}`); }); }); }
  if (audience === "teacher" && pack.teacherNotes?.length) rows.push("VII. GHI CHÚ GIÁO VIÊN", ...pack.teacherNotes.map((note) => `• ${note}`)); rows.push("", "Nội dung là bản nháp hỗ trợ giáo viên. Giáo viên cần kiểm tra, chỉnh sửa trước khi sử dụng chính thức."); return rows.filter((line) => line !== "").join("\n");
}

export function reviewPackToDocument(pack: ReviewPack, audience: "student" | "teacher" | "formula" | "practice" | "solutions" = "teacher"): GeneratedDocument { const validation = validateReviewPack(pack); const normalized = normalizeReviewPack({ ...pack, metadata: { ...pack.metadata, validationStatus: validation.status } }); return { id: normalized.id, title: `${normalized.title} · ${{ student: "Học sinh", teacher: "Giáo viên", formula: "Công thức", practice: "Luyện tập", solutions: "Đáp án và lời giải" }[audience]}`, type: "review-pack", folder: "Khác", createdAt: normalized.metadata.createdAt, content: reviewPackToText(normalized, audience), reviewPack: normalized, structuredExam: audience === "teacher" ? normalized.quickQuiz : undefined, examSolutionSet: audience === "teacher" ? normalized.solutions : undefined, generationMeta: { subject: normalized.subject, grade: normalized.grade, topic: normalized.topic, purpose: normalized.purpose, sectionCount: normalized.outline.length, exerciseCount: normalized.practiceActivities.length, source: normalized.metadata.sourceType, exportStatus: validation.status === "blocked" ? "blocked" : validation.status === "warning" ? "warning" : "ready" } }; }

export function reviewPackWorksheet(pack: ReviewPack): Worksheet { return normalizeWorksheet({ ...createWorksheetDraft(), id: reviewId("worksheet"), title: `PHIẾU LUYỆN TẬP - ${pack.topic || "ÔN TẬP"}`, subject: pack.subject, grade: pack.grade, topic: pack.topic, textbookSeries: pack.textbookSeries, purpose: "review", differentiation: pack.settings.differentiation, activities: pack.practiceActivities, settings: { ...createWorksheetDraft().settings, includeAnswers: true, includeTeacherGuide: true, sourceOnly: pack.settings.sourceOnly, activityCount: pack.practiceActivities.length }, metadata: { ...createWorksheetDraft().metadata, sourceType: "document", sourceDocumentId: pack.id, sourceTitle: pack.title } }); }
export function reviewPackWorksheetDocument(pack: ReviewPack) { return worksheetToDocument(reviewPackWorksheet(pack), "teacher"); }
export function reviewPackQuizDocument(pack: ReviewPack): GeneratedDocument | null { if (!pack.quickQuiz) return null; return { id: reviewId("quiz-document"), title: pack.quickQuiz.metadata.title, type: "exam", folder: "Đề kiểm tra", createdAt: new Date().toISOString(), content: pack.quickQuiz.parts.flatMap((part) => part.questions.map((question) => `Câu ${question.number}. ${question.stem}`)).join("\n\n"), structuredExam: pack.quickQuiz, examSolutionSet: pack.solutions, generationMeta: { source: "review-pack", subject: pack.subject, grade: pack.grade, topic: pack.topic, questionCount: pack.quickQuiz.parts.flatMap((part) => part.questions).length } }; }
export function reviewPackQuestions(pack: ReviewPack): QuestionItem[] { return worksheetQuestions(reviewPackWorksheet(pack)); }
export function duplicatePromptKeys(pack: ReviewPack) { const values = [...pack.practiceActivities.map((item) => item.prompt), ...pack.workedExamples.map((item) => item.prompt), ...(pack.quickQuiz?.parts.flatMap((part) => part.questions.map((item) => item.stem)) || [])]; const seen = new Set<string>(); return values.map(normalizeText).filter((value) => { if (seen.has(value)) return true; seen.add(value); return false; }); }
