import assert from "node:assert/strict";
import JSZip from "jszip";
import { buildDeterministicSolutionSet } from "../lib/answer-solutions/verify";
import { auditStructuredExam } from "../lib/exam-audit/audit";
import { normalizeGeneratedDocument } from "../lib/content/generated-content";
import { validateExamDocxBlob } from "../lib/docx/validate-exam";
import { compareExamQuestions, findExamDuplicates } from "../lib/exam/duplicate-detection";
import { sanitizeExamStructure } from "../lib/exam/exam-structure";
import { canonicalShortAnswer, validateMultipleChoiceOptions, validateVisualDependency } from "../lib/exam/exam-quality";
import { ensureStableExamIdentity } from "../lib/exam/identity";
import { editExamQuestion, proposeQuestionReplacement, applyQuestionReplacement } from "../lib/exam/question-workflow";
import { createExamVariants } from "../lib/exam-mixer/engine";
import { defaultExamMixingOptions } from "../lib/exam-mixer/types";
import { buildOfficialExamDocxBlob } from "../lib/export-exam-docx";
import type { ExamInput, GeneratedDocument } from "../lib/types";
import { chemistryFixture, englishFixture, literatureFixture, math12ProductionExam, physicsFixture } from "./fixtures/exam-production";

let passed = 0;
async function check(name: string, run: () => void | Promise<void>) { await run(); passed += 1; console.log(`✓ ${name}`); }
const input: ExamInput = { schoolName: "THPT Kiểm thử", teacherName: "", subject: "Toán", grade: "12", bookSeries: "", topic: "Hàm số và tọa độ Oxyz", duration: "90 phút", examType: "Kết hợp", examStyle: "THPTQG / tốt nghiệp", trueFalseCount: 4, shortAnswerCount: 6, examCode: "0101", multipleChoiceCount: 12, essayCount: 0, totalScore: 10, level: "Trung bình", recognitionRate: 30, understandingRate: 40, applicationRate: 20, advancedRate: 10, includeAnswers: true, includeRubric: true, includeMatrix: true, includeSpecification: true, extraRequirements: "" };
const baseExam = ensureStableExamIdentity(math12ProductionExam());
const document: GeneratedDocument = { id: "production-exam", title: baseExam.metadata.title, type: "exam", content: "", createdAt: new Date(0).toISOString(), structuredExam: baseExam, examMeta: { subject: "Toán", grade: "12", duration: "90 phút", topic: input.topic, examStyle: input.examStyle, examCode: "0101" } };

async function main() {
await check("1. Chuẩn hóa đúng 12/4/6 = 22 và 10 điểm", () => { const result = sanitizeExamStructure(baseExam, input as unknown as ExamInput & Record<string, unknown>); assert.equal(result.finalCount, 22); assert.deepEqual(result.generated, { partI: 12, partII: 4, partIII: 6 }); assert.equal(result.exam.parts.flatMap((part) => part.questions).reduce((sum, q) => sum + q.score, 0), 10); });
await check("2. ID câu và mệnh đề ổn định qua chuẩn hóa", () => { const twice = ensureStableExamIdentity(ensureStableExamIdentity(baseExam)); assert.deepEqual(twice.parts.map((p) => p.questions.map((q) => [q.id, q.trueFalseItems?.map((s) => s.id)])), baseExam.parts.map((p) => p.questions.map((q) => [q.id, q.trueFalseItems?.map((s) => s.id)]))); });
await check("3. Chỉnh một câu không đổi các câu khác", () => { const target = baseExam.parts[0].questions[0]; const before = baseExam.parts.flatMap((p) => p.questions).filter((q) => q.id !== target.id); const changed = editExamQuestion(document, target.id, { stem: `${target.stem} (đã chỉnh)` }); assert.deepEqual(changed.structuredExam?.parts.flatMap((p) => p.questions).filter((q) => q.id !== target.id), before); assert.equal(changed.structuredExam?.parts[0].questions[0].id, target.id); });
await check("4. Tạo lại câu dùng đề xuất và không ghi đè im lặng", () => { const target = baseExam.parts[0].questions[1]; const proposal = proposeQuestionReplacement(baseExam, target.id, { ...target, stem: "Nội dung thay thế đã hoàn chỉnh." }); assert.equal(baseExam.parts[0].questions[1].stem, target.stem); assert.equal(applyQuestionReplacement(document, proposal).structuredExam?.parts[0].questions[1].stem, "Nội dung thay thế đã hoàn chỉnh."); });
await check("5. Trùng chính xác bị loại; tương tự chỉ cảnh báo", () => { const exact = { ...baseExam.parts[0].questions[1], id: "exact-copy", stem: baseExam.parts[0].questions[0].stem }; assert.equal(compareExamQuestions(baseExam.parts[0].questions[0], exact)?.confidence, "exact"); const possible = { ...baseExam.parts[0].questions[1], id: "possible", stem: "Bài toán trường hợp 99: dữ kiện riêng 99." }; const possible2 = { ...possible, id: "possible-2", stem: "Bài toán trường hợp 100: dữ kiện riêng 100." }; assert.equal(compareExamQuestions(possible, possible2)?.confidence, "possible"); });
await check("6. MCQ đủ bốn phương án, một nhãn đáp án và không trùng", () => baseExam.parts[0].questions.forEach((question) => assert.equal(validateMultipleChoiceOptions(question).valid, true)));
await check("7. Phân bố đáp án Part I là 3/3/3/3", () => assert.deepEqual(Object.fromEntries(["A", "B", "C", "D"].map((letter) => [letter, baseExam.parts[0].questions.filter((q) => q.answer === letter).length])), { A: 3, B: 3, C: 3, D: 3 }));
await check("8. Đúng/Sai đủ bốn ý và giữ ánh xạ theo statement ID", () => { const variants = createExamVariants({ exam: baseExam, sourceExamId: "p", sourceExamTitle: "P", variantCount: 2, startingCode: 101, seed: "stable", options: { ...defaultExamMixingOptions, shuffleTrueFalseStatements: true } }); const source = new Map(baseExam.parts[1].questions.flatMap((q) => q.trueFalseItems || []).map((s) => [s.id, s.answer])); variants.variants.forEach((variant) => variant.exam.parts[1].questions.flatMap((q) => q.trueFalseItems || []).forEach((s) => assert.equal(source.get(s.id), s.answer))); });
await check("9. Trả lời ngắn có giá trị chuẩn", () => baseExam.parts[2].questions.forEach((question) => assert.equal(canonicalShortAnswer(question)?.canonicalValue, Number(question.answer))));
await check("10. Sai số xác định chặn trạng thái sẵn sàng", () => { const copy = structuredClone(baseExam); copy.parts[2].questions[0].answer = "99"; const result = auditStructuredExam(copy, { expectedSectionCounts: { partI: 12, partII: 4, partIII: 6 }, totalScore: 10, numericShortAnswers: true }); assert.equal(result.summary.readiness, "failed"); assert.ok(result.issues.some((issue) => issue.code === "verified_answer_mismatch")); });
await check("11. Thiếu hình, bảng, đoạn đọc bị từ chối; nội dung đính kèm được giữ", () => { assert.equal(validateVisualDependency({ stem: "Quan sát hình bên và trả lời." }).valid, false); assert.equal(validateVisualDependency({ stem: "Dựa vào bảng sau, trả lời." }).valid, false); assert.equal(validateVisualDependency({ stem: "Dựa vào đoạn văn trên, trả lời." }).valid, false); assert.equal(validateVisualDependency(literatureFixture().parts[0].questions[0]).valid, true); assert.equal(validateVisualDependency(englishFixture().parts[0].questions[0]).valid, true); });
await check("12. Fixture Vật lí, Hóa học giữ đơn vị và dữ kiện", () => { assert.match(physicsFixture().parts[0].questions[0].stem, /Ω|U=RI/); assert.match(chemistryFixture().parts[0].questions[0].stem, /g\/mol|H2O/); });
await check("13. Lời giải ánh xạ bằng ID và cache câu không đổi", () => { const first = buildDeterministicSolutionSet(baseExam); const changed = editExamQuestion({ ...document, examSolutionSet: first }, baseExam.parts[0].questions[0].id, { stem: `${baseExam.parts[0].questions[0].stem} chỉnh` }); assert.equal(changed.examSolutionSet?.questions.length, 21); assert.ok(changed.examSolutionSet?.questions.every((solution) => solution.questionId !== baseExam.parts[0].questions[0].id)); });
await check("14. Mở lại lịch sử giữ 22 câu và làm sạch cache cũ", () => { const reopened = normalizeGeneratedDocument(JSON.parse(JSON.stringify({ ...document, examSolutionSet: buildDeterministicSolutionSet(baseExam) })) as GeneratedDocument); assert.equal(reopened.structuredExam?.parts.flatMap((p) => p.questions).length, 22); assert.equal(reopened.examSolutionSet?.questions.length, 22); });
await check("15. Exam Mixer giữ 22 câu, điểm và đáp án", () => { const set = createExamVariants({ exam: baseExam, sourceExamId: "p", sourceExamTitle: "P", variantCount: 2, startingCode: 101, seed: "mix", options: defaultExamMixingOptions }); set.variants.forEach((variant) => { assert.equal(variant.exam.parts.flatMap((p) => p.questions).length, 22); assert.equal(variant.auditResult.totalScore, 10); }); });
await check("16. Student/teacher DOCX, OMML và XML đều hợp lệ", async () => { const student = await buildOfficialExamDocxBlob(document, { includeTeacher: false }); const teacher = await buildOfficialExamDocxBlob(document, { includeTeacher: true }); const studentValidation = await validateExamDocxBlob(student, baseExam, { includeTeacher: false }); const teacherValidation = await validateExamDocxBlob(teacher, baseExam, { includeTeacher: true }); assert.equal(studentValidation.valid, true); assert.equal(teacherValidation.valid, true); assert.equal(studentValidation.hasOmml, true); assert.equal(teacherValidation.hasTeacherSection, true); const studentXml = await (await JSZip.loadAsync(await student.arrayBuffer())).file("word/document.xml")!.async("string"); const teacherXml = await (await JSZip.loadAsync(await teacher.arrayBuffer())).file("word/document.xml")!.async("string"); assert.doesNotMatch(studentXml, /PHẦN DÀNH CHO GIÁO VIÊN|ĐÁP ÁN VÀ THANG ĐIỂM/u); assert.match(teacherXml, /ĐÁP ÁN VÀ THANG ĐIỂM/u); assert.match(teacherXml, /<m:oMath/); assert.doesNotMatch(teacherXml.replace(/<[^>]+>/g, ""), /\$|\\\(|\\\)/); assert.match(teacherXml, /Trong không gian Oxyz/); assert.match(teacherXml, /<w:tbl>/); });
await check("17. Bộ phát hiện trùng không gắn cờ chỉ vì cùng chủ đề", () => { const findings = findExamDuplicates(baseExam); assert.equal(findings.some((item) => item.confidence === "exact" || item.confidence === "high"), false); });

console.log(`Exam production hardening: ${passed}/17 nhóm kiểm tra đạt.`);
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
