import assert from "node:assert/strict";
import fs from "node:fs";
import JSZip from "jszip";
import { buildGenericDocxBlob } from "../lib/export-docx";
import type { GeneratedDocument } from "../lib/types";
import { canAccessLessonPlan, createLessonOutline, createLessonPlanDraft, generateLessonActivityFallback, lessonPlanToDocument, lessonPlanToText, lessonSourceFromDocument, normalizeLessonPlan, objectiveCoverage, parseLessonActivityResponse, redistributePeriod, validateLessonPlan, validateLessonTiming } from "../lib/lesson-plan/workflow";

let passed=0;async function check(name:string,run:()=>void|Promise<void>){await run();passed+=1;console.log(`✓ ${passed}. ${name}`);}const root=process.cwd();
const draft=createLessonPlanDraft({subject:"Vật lí",grade:"11",topic:"Định luật Ohm",periodCount:1,minutesPerPeriod:45,differentiation:{mode:"three_levels"},settings:{detailLevel:"standard",layout:"activities",defaultWorkMode:"mixed",sourceOnly:true,includeWarmUp:true,includeKnowledge:true,includePractice:true,includeApplication:true,includeConsolidation:true,includeHomework:true,includeAssessment:true,includeSlideGuide:false,includeWorksheet:true,includeRubric:true,includeExpectedProducts:true}});
const outline=createLessonOutline(draft);const ready=normalizeLessonPlan({...draft,periods:outline.map((period)=>({...period,activities:period.activities.map((activity)=>generateLessonActivityFallback(draft,activity))}))});

async function main(){
await check("Route giáo án cũ còn tương thích",()=>{assert.match(fs.readFileSync(`${root}/app/tools/lesson-plan-generator/page.tsx`,"utf8"),/lesson-plan/);assert.ok(fs.existsSync(`${root}/app/tools/lesson-plan/page.tsx`));});
await check("Chủ đề thủ công tạo dàn ý hợp lệ",()=>assert.ok(outline[0].activities.length>=2));
await check("Nguồn tài liệu chỉ dùng nội dung đã xác nhận",()=>{const source=lessonSourceFromDocument({id:"r",title:"Tài liệu",type:"document-recognition",content:"",createdAt:"x",recognitionDraft:{id:"r",sourceType:"image",sourceFileName:"a.png",pageCount:1,reviewStatus:"confirmed",documentHash:"h",createdAt:"x",updatedAt:"x",pages:[{pageNumber:1,type:"scanned_image",textLength:4,imageCoverage:1,recognitionRequired:true,warnings:[],rotation:0,status:"recognized",blocks:[{id:"1",pageNumber:1,type:"paragraph",text:"Đã duyệt",boundingBox:{x:0,y:0,width:1,height:1},confidence:"high",readingOrder:1,warnings:[],reviewed:true,excluded:false},{id:"2",pageNumber:1,type:"paragraph",text:"Chưa duyệt",boundingBox:{x:0,y:0,width:1,height:1},confidence:"low",readingOrder:2,warnings:[],reviewed:false,excluded:false}]}]}} as GeneratedDocument);assert.match(source.text,/Đã duyệt/);assert.doesNotMatch(source.text,/Chưa duyệt/);});
await check("Slide loại nội dung teacher-only",()=>{const doc={id:"s",title:"Slide",type:"lesson-slides",content:"",createdAt:"x",slideDeck:{title:"Ohm",purpose:"new_lesson",aspectRatio:"16:9",themeId:"clean",teacherNotesEnabled:true,assets:[],slides:[{id:"1",order:1,type:"content",layout:"title_content",blocks:[{id:"a",type:"text",region:"main",alignment:"left",content:"Nội dung học sinh"},{id:"b",type:"text",region:"main",alignment:"left",content:"Ghi chú ẩn",teacherOnly:true}],teacherNotes:"Bí mật"}],metadata:{sourceType:"manual",createdAt:"x",updatedAt:"x"}}} as GeneratedDocument;const source=lessonSourceFromDocument(doc);assert.match(source.text,/Nội dung học sinh/);assert.doesNotMatch(source.text,/Ghi chú ẩn|Bí mật/);});
await check("Dàn ý chỉnh được trước generation",()=>assert.equal({...outline[0].activities[0],title:"Đã chỉnh"}.title,"Đã chỉnh"));
await check("Tổng thời gian từng tiết được kiểm tra",()=>assert.equal(validateLessonTiming({...draft,periods:outline})[0].status,"match"));
await check("Vượt thời lượng được báo lỗi",()=>{const plan={...ready,periods:ready.periods.map((period,index)=>index?period:{...period,activities:period.activities.map((activity,itemIndex)=>itemIndex?activity:{...activity,durationMinutes:activity.durationMinutes+8})})};assert.equal(validateLessonTiming(plan)[0].status,"over");assert.match(validateLessonPlan(plan).errors.join(" "),/vượt/);});
await check("ID hoạt động giữ ổn định",()=>assert.equal(parseLessonActivityResponse('{"content":"Mới","steps":[{"name":"Bước","teacherAction":"Giao câu hỏi cụ thể","studentAction":"Giải câu hỏi","output":"Bài làm"}]}',ready,ready.periods[0].activities[0]).id,ready.periods[0].activities[0].id));
await check("Tạo lại một hoạt động giữ hoạt động khác",()=>{const before=ready.periods[0].activities[1];const next=ready.periods[0].activities.map((item,index)=>index?item:{...item,content:"Tạo lại"});assert.deepEqual(next[1],before);});
await check("Sửa tay không bị ghi đè im lặng",()=>assert.equal({...ready.periods[0].activities[0],teacherEdited:true,content:"Giáo viên sửa"}.teacherEdited,true));
await check("Mục tiêu ánh xạ tới hoạt động",()=>assert.ok(objectiveCoverage(ready).every((item)=>item.activityTitles.length>0)));
await check("Thiếu bao phủ mục tiêu được báo",()=>{const missing={...ready,objectives:[...ready.objectives,{id:"missing",category:"other" as const,content:"Mục tiêu chưa dùng"}]};assert.equal(objectiveCoverage(missing).at(-1)?.status,"missing_activity");});
await check("Thiếu minh chứng được báo",()=>{const first=ready.objectives[0].id;const plan={...ready,periods:ready.periods.map((period)=>({...period,activities:period.activities.map((activity)=>activity.objectiveIds.includes(first)?{...activity,assessmentEvidence:""}:activity)}))};assert.equal(objectiveCoverage(plan).find((item)=>item.objectiveId===first)?.status,"missing_evidence");});
await check("Hành động giáo viên/học sinh đi theo cặp",()=>assert.ok(ready.periods.flatMap((item)=>item.activities).every((item)=>item.steps.every((step)=>step.teacherAction&&step.studentAction))));
await check("Phân hóa giữ cùng mục tiêu",()=>{const activity=ready.periods[0].activities[0];assert.ok(activity.differentiation?.support&&activity.differentiation.advanced);assert.ok(activity.objectiveIds.length);});
await check("Nhiệm vụ hỗ trợ và nâng cao khác nhau",()=>{const item=ready.periods[0].activities[0].differentiation!;assert.notEqual(item.support,item.advanced);});
await check("Worksheet nhận đúng dữ liệu hoạt động",()=>{const source=lessonPlanToDocument({...ready,periodCount:1,periods:[{...ready.periods[0],activities:[ready.periods[0].activities[0]]}]});assert.equal(source.generationMeta?.topic,"Định luật Ohm");assert.match(source.content,/Sản phẩm dự kiến/);});
await check("Slide mapping dùng LessonPlan canonical",()=>{const source=lessonPlanToDocument(ready);assert.ok(source.lessonPlan);assert.match(fs.readFileSync(`${root}/lib/lesson-slides/source.ts`,"utf8"),/lesson-plan/);});
await check("Rubric tiếp tục dùng công cụ hiện có",()=>assert.match(fs.readFileSync(`${root}/components/lesson-plan/LessonPlanWorkspace.tsx`,"utf8"),/rubric-generator/));
await check("Kiểm tra nhanh dùng Exam/Worksheet hiện có",()=>{const source=fs.readFileSync(`${root}/components/lesson-plan/LessonPlanWorkspace.tsx`,"utf8");assert.match(source,/exam-generator/);assert.match(source,/openWorksheetGenerator/);});
await check("Word chứa đầy đủ hoạt động",async()=>{const zip=await JSZip.loadAsync(await (await buildGenericDocxBlob(lessonPlanToDocument(ready,"full"))).arrayBuffer());const xml=await zip.file("word/document.xml")!.async("string");for(const activity of ready.periods[0].activities)assert.match(xml,new RegExp(activity.title));});
await check("Bảng Word giữ cấu trúc chỉnh sửa",async()=>{const zip=await JSZip.loadAsync(await (await buildGenericDocxBlob(lessonPlanToDocument(ready,"teacher_student_table"))).arrayBuffer());const xml=await zip.file("word/document.xml")!.async("string");assert.match(xml,/<w:tbl>/);assert.match(xml,/Hoạt động của giáo viên/);});
await check("PDF payload không có metadata nội bộ",()=>assert.doesNotMatch(lessonPlanToDocument(ready,"full").content,/provider|base.?url|api.?key|ownerId/i));
await check("Tiếng Việt được giữ",()=>assert.match(lessonPlanToText(ready,"full"),/MỤC TIÊU|TIẾN TRÌNH DẠY HỌC|Định luật Ohm/));
await check("History phục hồi đúng LessonPlan",()=>{const doc=lessonPlanToDocument(ready);const restored=JSON.parse(JSON.stringify(doc.lessonPlan));assert.equal(JSON.stringify(restored),JSON.stringify(doc.lessonPlan));});
await check("Teacher không truy cập giáo án người khác",()=>{assert.equal(canAccessLessonPlan({...ready,ownerId:"a"},"b"),false);assert.equal(canAccessLessonPlan({...ready,ownerId:"a"},"b",true),true);});
await check("Maintenance chặn teacher",()=>assert.match(fs.readFileSync(`${root}/app/tools/lesson-plan/page.tsx`,"utf8"),/getMaintenanceBlockForUser/));
await check("Admin bypass vẫn dùng chính sách hiện có",()=>assert.match(fs.readFileSync(`${root}/lib/maintenance.ts`,"utf8"),/role === "admin"/));
await check("Worksheet regression được giữ",()=>assert.match(fs.readFileSync(`${root}/package.json`,"utf8"),/worksheet:test/));
await check("Lesson Slides regression được giữ",()=>assert.match(fs.readFileSync(`${root}/package.json`,"utf8"),/lesson:slides-test/));
await check("Rubric route vẫn tồn tại",()=>assert.ok(fs.existsSync(`${root}/app/tools/rubric-generator/page.tsx`)));
await check("Exam regression được giữ",()=>assert.match(fs.readFileSync(`${root}/package.json`,"utf8"),/exam:quality-test/));
await check("Word/PDF dùng pipeline hiện có",()=>{const source=fs.readFileSync(`${root}/lib/lesson-plan/export.ts`,"utf8");assert.match(source,/buildGenericDocxBlob/);assert.match(source,/printGeneratedDocument/);});
await check("Phân bổ thời gian deterministic",()=>{const period=redistributePeriod({...ready.periods[0],activities:ready.periods[0].activities.map((item)=>({...item,durationMinutes:1}))});assert.equal(period.activities.reduce((sum,item)=>sum+item.durationMinutes,0),45);});
assert.equal(passed,34);console.log(`Lesson plan workflow: ${passed}/34 nhóm kiểm tra đạt (bao phủ 33 yêu cầu và 1 kiểm tra phân bổ deterministic).`);
}
main().catch((error)=>{console.error(error);process.exit(1);});
