import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import JSZip from "jszip";
import { requiredTikzLibraries } from "../lib/ai/extract-tikz";
import { compareDiagramModels } from "../lib/tikz/comparison";
import { createDraftFromDescription } from "../lib/tikz/description";
import { applyManualTikzCode, applyStructuredEdit } from "../lib/tikz/editor";
import { generateTikzFromDraft } from "../lib/tikz/generator";
import { detectLabelOverlaps, proposeLayoutRepairs, repairNearlyOverlappingPoints } from "../lib/tikz/layout-repair";
import { createTikzDiagramDraft, normalizeDiagramClass, normalizeLegacyTikzDraft, stableTikzId } from "../lib/tikz/model";
import { parseNaturalDiagramEdit } from "../lib/tikz/natural-edits";
import { preprocessDiagramImage } from "../lib/tikz/preprocess";
import { renderTikzDraftToSvg } from "../lib/tikz/render-svg";
import { buildTikzAssets, buildTikzZip } from "../lib/tikz/server-export";
import { inspectTikzSafety, sanitizeDownloadName } from "../lib/tikz/safety";
import { inspectTikzSyntax, repairTikzSyntax } from "../lib/tikz/syntax";
import type { TikzDiagramDraft } from "../lib/tikz/types";
import { qualitySummary, validateTikzDraft } from "../lib/tikz/validation";

let passed = 0;
async function check(name: string, task: () => void | Promise<void>) { await task(); passed += 1; console.log(`✓ ${passed}. ${name}`); }
function deterministic(raw: Record<string, unknown>, source = "fixture"): TikzDiagramDraft { const draft = createTikzDiagramDraft({ sourceHash: stableTikzId("fixture", source), sourceName: source, rawStructure: raw, tikzCode: "\\begin{tikzpicture}\n\\end{tikzpicture}" }); const generated = generateTikzFromDraft(draft); draft.tikz = { ...draft.tikz, snippet: generated.snippet, generatedSnippet: generated.snippet, standalone: generated.standalone, libraries: generated.libraries, packages: generated.packages }; draft.compilation = inspectTikzSyntax(generated.snippet); draft.validation = validateTikzDraft(draft); draft.quality = qualitySummary(draft); return draft; }

const pyramidRaw = { diagramType: "solid_geometry", figureType: "pyramid", confidence: 0.91, points: [{ label: "A", coordinate: [-3, 0] }, { label: "B", coordinate: [3, 0] }, { label: "C", coordinate: [2, 1.5] }, { label: "D", coordinate: [-2, 1.5] }, { label: "S", coordinate: [0, 4] }, { label: "O", coordinate: [0, 0.75] }], solidEdges: [["A", "B"], ["B", "C"], ["C", "D"], ["S", "A"], ["S", "B"], ["S", "C"], ["A", "C"], ["B", "D"]], dashedEdges: [["D", "A"], ["S", "D"]], relations: [{ type: "intersection", point: "O", lines: [["A", "C"], ["B", "D"]] }], rightAngles: [{ vertex: "O", certain: true }] };
const graphRaw = { diagramType: "function_graph", confidence: 0.9, axes: { xLabel: "x", yLabel: "y", origin: "O" }, ticks: [{ axis: "x", value: -3, label: "-3" }, { axis: "x", value: 1, label: "1" }], curves: [{ id: "f", label: "y=f(x)", approximatePoints: [[-3, -2], [-1, 3], [1, -1], [3, 4]] }], markedPoints: [{ coordinate: [-3, -2] }, { coordinate: [-1, 3] }, { coordinate: [1, -1] }, { coordinate: [3, 4] }, { label: "O", coordinate: [0, 0] }], guides: [{ style: "dashed", from: [-3, 0], to: [-3, -2] }] };
const lineRaw = { diagramType: "line_angle_diagram", confidence: 0.86, points: [{ label: "A", coordinate: [-2, 1] }, { label: "B", coordinate: [2, 1] }, { label: "C", coordinate: [-2, -1] }, { label: "D", coordinate: [2, -1] }], segments: [{ from: "A", to: "B" }, { from: "C", to: "D" }, { from: "A", to: "C" }], relations: [{ type: "parallel", points: ["A", "B", "C", "D"] }, { type: "perpendicular", segment1: ["A", "B"], segment2: ["A", "C"], certain: true }], rightAngles: [{ vertex: "A", certain: true }] };
const chartRaw = { diagramType: "statistical_chart", confidence: 0.88, bars: [{ label: "Lớp 6", value: 12, x: 1 }, { label: "Lớp 7", value: 18, x: 2 }] };
const physicsRaw = { diagramType: "physics_diagram", subtype: "force_diagram", confidence: 0.72, points: [{ label: "O", coordinate: [0, 0] }], forces: [{ label: "P", from: [0, 0], to: [0, -2] }] };
const pyramid = deterministic(pyramidRaw, "pyramid"); const graph = deterministic(graphRaw, "graph"); const lines = deterministic(lineRaw, "lines"); const chart = deterministic(chartRaw, "chart"); const physics = deterministic(physicsRaw, "physics");

async function main() {
await check("Route Image-to-LaTeX hiện có vẫn tồn tại", () => assert.match(readFileSync("app/tools/image-to-latex/page.tsx", "utf8"), /TikzReviewWorkspace/));
await check("Không tạo route công cụ TikZ trùng", () => assert.equal(readFileSync("lib/tool-registry.ts", "utf8").match(/href:\s*"\/tools\/image-to-latex"/g)?.length, 1));
await check("Bản ghi TikZ cũ được chuẩn hóa", () => assert.match(normalizeLegacyTikzDraft({ content: pyramid.tikz.snippet }).tikz.snippet, /tikzpicture/));
await check("Bản ghi TikZ Bank snake_case được đọc", () => assert.equal(normalizeLegacyTikzDraft({ tikz_code: pyramid.tikz.snippet, title: "Cũ" }).source.sourceType, "tikz_bank"));
await check("Stable ID giữ nguyên với cùng nhãn", () => assert.equal(stableTikzId("point", "A"), stableTikzId("point", "A")));
await check("Phân loại geometry_diagram tương thích", () => assert.equal(normalizeDiagramClass("geometry_diagram"), "solid_geometry"));
await check("Phân loại hình phẳng", () => assert.equal(normalizeDiagramClass("triangle"), "plane_geometry"));
await check("Phân loại đồ thị", () => assert.equal(graph.classification.type, "function_graph"));
await check("Phân loại sơ đồ đường-góc", () => assert.equal(lines.classification.type, "line_angle_diagram"));
await check("Phân loại biểu đồ", () => assert.equal(chart.classification.type, "statistical_chart"));
await check("Phân loại vật lí", () => assert.equal(physics.classification.type, "physics_diagram"));
await check("Unknown vẫn là unknown", () => assert.equal(normalizeDiagramClass("unfamiliar"), "unknown"));
await check("Tin cậy thấp yêu cầu giáo viên xác nhận", () => assert.equal(createDraftFromDescription("hình không xác định").quality.teacherConfirmationRequired, true));
await check("Hình chóp giữ đủ S,A,B,C,D", () => assert.deepEqual(["S", "A", "B", "C", "D"].filter((label) => !pyramid.objects.some((item) => item.label === label)), []));
await check("Giao điểm O chỉ có một object", () => assert.equal(pyramid.objects.filter((item) => item.label === "O").length, 1));
await check("Quan hệ giao điểm được lưu một lần", () => assert.equal(pyramid.relationships.filter((item) => item.type === "intersects").length, 1));
await check("Cạnh khuất giữ nét đứt", () => assert.ok(pyramid.objects.some((item) => item.type === "segment" && item.style === "dashed")));
await check("Quan hệ song song được giữ", () => assert.ok(lines.relationships.some((item) => item.type === "parallel")));
await check("Quan hệ vuông góc được giữ", () => assert.ok(lines.relationships.some((item) => item.type === "perpendicular")));
await check("Dấu vuông góc tham chiếu điểm hợp lệ", () => assert.ok(lines.objects.some((item) => item.type === "right_angle_marker" && item.points?.length)));
await check("Generator tạo tikzpicture hoàn chỉnh", () => assert.match(pyramid.tikz.snippet, /\\begin\{tikzpicture\}[\s\S]*\\end\{tikzpicture\}/));
await check("Generator dùng một lệnh logic mỗi dòng", () => assert.ok(pyramid.tikz.snippet.split("\n").filter((line) => /\\(?:draw|node|fill|coordinate)/.test(line)).every((line) => line.split("%")[0].trim().endsWith(";"))));
await check("Không có coordinate trùng tên", () => assert.equal(inspectTikzSyntax(pyramid.tikz.snippet).errors.some((item) => item.code === "duplicate_node"), false));
await check("Standalone có package TikZ", () => assert.match(pyramid.tikz.standalone, /\\usepackage\{tikz\}/));
await check("Library intersections được phát hiện", () => assert.ok(requiredTikzLibraries("\\path[name intersections={of=a and b, by=O}];").includes("intersections")));
await check("Library angles/quotes được phát hiện", () => assert.deepEqual(requiredTikzLibraries("\\pic {angle=A--B--C};").sort(), ["angles", "quotes"]));
await check("Library calc được phát hiện", () => assert.ok(requiredTikzLibraries("\\coordinate (M) at ($(A)!0.5!(B)$);").includes("calc")));
await check("Không bơm library khổng lồ mặc định", () => assert.equal(requiredTikzLibraries("\\draw (0,0)--(1,1);").length, 0));
await check("Thiếu semicolon được phát hiện", () => assert.ok(inspectTikzSyntax("\\begin{tikzpicture}\n\\draw (0,0)--(1,1)\n\\end{tikzpicture}").errors.some((item) => item.code === "missing_semicolon")));
await check("Thiếu semicolon được đề xuất sửa", () => assert.match(repairTikzSyntax("\\begin{tikzpicture}\n\\draw (0,0)--(1,1)\n\\end{tikzpicture}").code, /\(1,1\);/));
await check("Ngoặc thiếu được phát hiện", () => assert.ok(inspectTikzSyntax("\\begin{tikzpicture}\n\\node {A;\n\\end{tikzpicture}").errors.some((item) => item.code === "unmatched_brace")));
await check("Node trùng được phát hiện", () => assert.ok(inspectTikzSyntax("\\begin{tikzpicture}\n\\coordinate (A) at (0,0);\n\\coordinate (A) at (1,1);\n\\end{tikzpicture}").errors.some((item) => item.code === "duplicate_node")));
await check("write18 bị chặn", () => assert.equal(inspectTikzSafety("\\write18{whoami}").safe, false));
await check("openin bị chặn", () => assert.equal(inspectTikzSafety("\\openin1=/etc/passwd").safe, false));
await check("include không an toàn bị chặn", () => assert.equal(inspectTikzSafety("\\include{../secret}").safe, false));
await check("Tài nguyên mạng bị chặn", () => assert.equal(inspectTikzSafety("https://example.com/a.png").safe, false));
await check("Lệnh draw an toàn không bị chặn theo substring", () => assert.equal(inspectTikzSafety("\\draw (0,0)--(1,1);").safe, true));
await check("Tên tải xuống được làm sạch", () => assert.equal(sanitizeDownloadName("Hình S.ABCD / 2026"), "hinh-s-abcd-2026"));
await check("Hình chóp thiếu đỉnh không sẵn sàng", () => { const broken = deterministic({ ...pyramidRaw, points: (pyramidRaw.points as Array<Record<string, unknown>>).filter((item) => item.label !== "S") }, "broken"); assert.notEqual(broken.validation.status, "ready"); });
await check("Đồ thị có đủ hai trục", () => assert.equal(graph.validation.checks.find((item) => item.code === "graph_axes")?.passed, true));
await check("Đồ thị giữ mọi điểm đánh dấu", () => assert.equal(graph.objects.filter((item) => item.type === "plotted_point").length, 5));
await check("Nhãn O không lặp", () => assert.ok(graph.objects.filter((item) => item.label === "O").length <= 1));
await check("Đường cong nằm trong model", () => assert.ok(graph.objects.some((item) => item.type === "function_curve" && item.coordinates?.length === 4)));
await check("Line-angle có đủ đường chính", () => assert.equal(lines.validation.checks.find((item) => item.code === "line_count")?.passed, true));
await check("Biểu đồ giữ nhãn và giá trị", () => assert.equal(chart.validation.checks.find((item) => item.code === "chart_values")?.passed, true));
await check("Sơ đồ lực giữ mũi tên", () => assert.ok(physics.objects.some((item) => item.type === "force_arrow")));
await check("SVG preview có kích thước hợp lệ", () => { const svg = renderTikzDraftToSvg(pyramid); assert.match(svg.svg, /^<svg/); assert.ok(svg.width > 0 && svg.height > 0); });
await check("SVG preview giữ nhãn S", () => assert.match(renderTikzDraftToSvg(pyramid).svg, />S<\/text>/));
await check("PNG kết xuất có chữ ký hợp lệ", async () => { const assets = await buildTikzAssets(pyramid); assert.deepEqual([...assets.png.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]); });
await check("ZIP chứa TEX/SVG/PNG/README", async () => { const zip = await JSZip.loadAsync(await buildTikzZip(pyramid)); for (const name of ["diagram.tex", "diagram-standalone.tex", "diagram.svg", "diagram.png", "README.txt"]) assert.ok(zip.file(name)); });
await check("README không chứa dữ liệu nội bộ", async () => { const zip = await JSZip.loadAsync(await buildTikzZip(pyramid)); const readme = await zip.file("README.txt")!.async("text"); assert.doesNotMatch(readme, /provider|api key|base url|supabase/i); });
await check("Di chuyển điểm cập nhật TikZ", () => { const point = pyramid.objects.find((item) => item.label === "S")!; const moved = applyStructuredEdit(pyramid, { type: "move_object", objectId: point.id, position: { x: 1, y: 5 } }); assert.notEqual(moved.tikz.snippet, pyramid.tikz.snippet); assert.match(moved.tikz.snippet, /\(1,5\)/); });
await check("Đổi tên điểm cập nhật nhãn", () => { const point = pyramid.objects.find((item) => item.label === "O")!; const renamed = applyStructuredEdit(pyramid, { type: "rename_point", objectId: point.id, label: "I" }); assert.match(renamed.tikz.snippet, /\$I\$/); });
await check("Đổi cạnh thành nét đứt cập nhật TikZ", () => { const edge = pyramid.objects.find((item) => item.type === "segment" && item.style === "solid")!; const changed = applyStructuredEdit(pyramid, { type: "change_line_style", objectId: edge.id, style: "dashed" }); assert.match(changed.tikz.snippet, /\\draw\[thick, dashed\]/); });
await check("Thêm dấu vuông góc dùng điểm hợp lệ", () => { const point = pyramid.objects.find((item) => item.label === "O")!; const changed = applyStructuredEdit(pyramid, { type: "add_right_angle", pointId: point.id }); assert.match(changed.tikz.snippet, /right-angle-marker O/); });
await check("Di chuyển nhãn không đổi association", () => { const point = pyramid.objects.find((item) => item.label === "A")!; const changed = applyStructuredEdit(pyramid, { type: "move_label", objectId: point.id, anchor: "below" }); assert.equal(changed.objects.find((item) => item.id === point.id)?.label, "A"); });
await check("Sửa một object giữ object khác", () => { const point = pyramid.objects.find((item) => item.label === "A")!; const other = pyramid.objects.find((item) => item.label === "B")!; const changed = applyStructuredEdit(pyramid, { type: "move_object", objectId: point.id, position: { x: -4, y: 0 } }); assert.deepEqual(changed.objects.find((item) => item.id === other.id), other); });
await check("Code sửa tay được giữ", () => { const manual = applyManualTikzCode(pyramid, pyramid.tikz.snippet.replace("scale=1", "scale=1.2")); assert.match(manual.tikz.snippet, /scale=1\.2/); assert.equal(manual.tikz.semanticSync, "partially_detached"); });
await check("Lệnh đổi cạnh tạo diff có cấu trúc", () => { const parsed = parseNaturalDiagramEdit("Đổi cạnh AB thành nét đứt", pyramid); assert.equal(parsed.operations[0]?.type, "change_line_style"); });
await check("Lệnh đổi tên điểm tạo diff có cấu trúc", () => { const parsed = parseNaturalDiagramEdit("Đổi tên điểm O thành I", pyramid); assert.equal(parsed.operations[0]?.type, "rename_point"); });
await check("Lệnh thêm vuông góc tạo diff có cấu trúc", () => { const parsed = parseNaturalDiagramEdit("Thêm dấu vuông góc tại O", pyramid); assert.equal(parsed.operations[0]?.type, "add_right_angle"); });
await check("Lệnh nguy hiểm không thành thao tác", () => { const parsed = parseNaturalDiagramEdit("\\input{secret}", pyramid); assert.equal(parsed.operations.length, 0); });
await check("Phát hiện nhãn chồng nhau", () => { const copy = structuredClone(pyramid); const [a, b] = copy.objects.filter((item) => item.type === "point"); b.position = a.position; assert.ok(detectLabelOverlaps(copy).length); });
await check("Đề xuất sửa nhãn chồng", () => { const copy = structuredClone(pyramid); const [a, b] = copy.objects.filter((item) => item.type === "point"); b.position = a.position; assert.ok(proposeLayoutRepairs(copy).length); });
await check("Tách điểm gần trùng không đổi điểm khác", () => { const copy = structuredClone(pyramid); const [a, b] = copy.objects.filter((item) => item.type === "point"); b.position = a.position; assert.ok(repairNearlyOverlappingPoints(copy).moved.includes(b.id)); });
await check("So sánh model tính coverage", () => assert.equal(compareDiagramModels(pyramid, pyramid).objectCoverage, 100));
await check("Thiếu object làm hạ trạng thái so sánh", () => { const reduced = { ...pyramid, objects: pyramid.objects.slice(0, 2) }; assert.notEqual(compareDiagramModels(pyramid, reduced).status, "near_match"); });
await check("Lệch nhãn nhỏ không tự thành blocking", () => { const changed = structuredClone(pyramid); const point = changed.objects.find((item) => item.label === "A")!; point.anchor = "below"; assert.notEqual(compareDiagramModels(pyramid, changed).status, "mismatch"); });
await check("Mô tả hình chóp tạo model semantic", () => assert.equal(createDraftFromDescription("Hình chóp S.ABCD").classification.subtype, "pyramid"));
await check("Mô tả tam giác tạo ba điểm", () => assert.equal(createDraftFromDescription("Tam giác ABC").objects.filter((item) => item.type === "point").length, 3));
await check("Mô tả đồ thị giữ điểm nhập", () => assert.ok(createDraftFromDescription("Đồ thị qua (2,3) và (-1,0)").objects.some((item) => item.position?.x === 2 && item.position.y === 3)));
await check("Preprocess sửa orientation và giữ kích thước", async () => { const input = readFileSync("tests/fixtures/document-recognition/02-rotated-page.png"); const processed = await preprocessDiagramImage(input, { rotation: 90, contrast: "enhanced" }); assert.ok(processed.originalWidth && processed.processedWidth && processed.base64.length > 100); });
await check("Preprocess cache theo hash/settings", async () => { const input = readFileSync("tests/fixtures/document-recognition/03-perspective-photo.png"); const first = await preprocessDiagramImage(input, {}); const second = await preprocessDiagramImage(input, {}); assert.equal(first.sourceHash, second.sourceHash); assert.equal(first.base64, second.base64); });
await check("API render kiểm tra đăng nhập và maintenance", () => { const source = readFileSync("app/api/tikz/render/route.ts", "utf8"); assert.match(source, /getCurrentUser/); assert.match(source, /getMaintenanceBlockForUser/); });
await check("API không tin user_id từ client", () => assert.doesNotMatch(readFileSync("app/api/tikz/render/route.ts", "utf8"), /body\.user_id|body\.userId/));
await check("Source image không tạo URL công khai", () => assert.doesNotMatch(readFileSync("app/api/ai/image-to-latex/route.ts", "utf8"), /publicUrl|public\/source/));
await check("Route xử lý tối đa 10MB", () => assert.match(readFileSync("app/api/ai/image-to-latex/route.ts", "utf8"), /10 \* 1024 \* 1024/));
await check("History có canonical TikZ draft", () => assert.match(readFileSync("lib/types.ts", "utf8"), /tikzDiagramDraft/));
await check("Image-to-LaTeX công thức không bị xóa", () => assert.match(readFileSync("lib/ai/image-to-latex.ts", "utf8"), /type:\s*"latex"/));
await check("Document Recognition vẫn dẫn đến route canonical", () => assert.match(readFileSync("components/document-recognition/DocumentRecognitionWorkspace.tsx", "utf8"), /\/tools\/image-to-latex/));
await check("TikZ Bank mở cùng trình chỉnh sửa", () => assert.match(readFileSync("app/tikz-bank/page.tsx", "utf8"), /soanlab:tikz-open/));
await check("Không bật shell escape", () => assert.doesNotMatch(readFileSync("lib/tikz/server-export.ts", "utf8"), /shell-escape|exec\(|spawn\(/));

assert.equal(passed, 82);
console.log(`TikZ workflow v2: ${passed}/82 kiểm tra semantic, chỉnh sửa, preview, export và bảo mật đạt.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
