import assert from "node:assert/strict";
import { normalizeAIExamOutput } from "../lib/exam/normalize-ai-exam";
import { createGenerationRequestContext } from "../lib/generation/request-context";
import { validateTopicItem } from "../lib/generation/topic-validator";
import { buildExamPrompt } from "../lib/ai/prompts";
import { calculateExamStructure, sanitizeExamStructure } from "../lib/exam/exam-structure";
import { assembleSectionedExam, buildExamSectionPrompt, buildSectionOnlyInput, isUsableExamCount, minimumUsableExamCount, sectionCounts } from "../lib/exam/section-generation";
import { validateShortAnswerNumeric, validateVisualDependency } from "../lib/exam/exam-quality";
import type { ExamInput } from "../lib/types";

const input = { schoolName: "", teacherName: "", subject: "Toán", grade: "12", bookSeries: "Kết nối tri thức", topic: "hàm số", duration: "45 phút", examType: "Trắc nghiệm", examStyle: "Kiểm tra thường", trueFalseCount: 0, shortAnswerCount: 0, examCode: "101", multipleChoiceCount: 10, essayCount: 0, totalScore: 10, level: "Trung bình", recognitionRate: 30, understandingRate: 40, applicationRate: 20, advancedRate: 10, includeAnswers: true, includeRubric: true, includeMatrix: true, includeSpecification: true, extraRequirements: "" } as ExamInput;
const question = (index: number) => ({ id: `q${index}`, stem: `Cho hàm số y=x^3-${index}x. Hàm số đồng biến trên khoảng nào?`, options: { A: "A", B: "B", C: "C", D: "D" }, correctAnswer: ["A", "B", "C", "D"][index % 4], explanation: "Xét dấu đạo hàm để tìm khoảng đồng biến.", score: 1, difficulty: index < 3 ? "Nhận biết" : index < 7 ? "Thông hiểu" : index < 9 ? "Vận dụng" : "Vận dụng cao", topic: "hàm số" });
const raw = `Kết quả:\n\`\`\`json\n${JSON.stringify({ metadata: { title: "Đề hàm số", subject: "Toán", grade: "12" }, sections: [{ type: "multiple_choice", questions: [question(0), question(1)] }, { type: "multiple_choice", questions: Array.from({ length: 8 }, (_, index) => question(index + 2)) }], teacherOnly: { scoringGuide: "Đáp án theo từng câu." } })}\n\`\`\``;
const parsed = normalizeAIExamOutput(raw, input);
assert.equal(parsed.ok, true);
if (parsed.ok) assert.equal(parsed.structuredExam.parts.flatMap((part) => part.questions).length, 10);
const directArray = normalizeAIExamOutput(`Dữ liệu: ${JSON.stringify(Array.from({ length: 10 }, (_, index) => question(index)))}`, input);
assert.equal(directArray.ok, true);
if (directArray.ok) assert.equal(directArray.structuredExam.parts[0].questions.length, 10);
const prompt = buildExamPrompt(input);
assert.match(prompt, /đủ chính xác 10 câu/i);
assert.match(prompt, /Nhận biết 3, Thông hiểu 4, Vận dụng 2, Vận dụng cao 1/);

const thptInput = { ...input, examStyle: "THPTQG / tốt nghiệp", multipleChoiceCount: 12, trueFalseCount: 4, shortAnswerCount: 6, totalScore: 10 } as ExamInput;
assert.deepEqual(calculateExamStructure(thptInput as ExamInput & Record<string, unknown>), { sectionCounts: { partI: 12, partII: 4, partIII: 6 }, requestedQuestionCount: 22, totalScore: 10, difficultyDistribution: { recognition: 30, comprehension: 40, application: 20, highApplication: 10 } });
assert.deepEqual(calculateExamStructure({ multipleChoiceCount: 10, trueFalseCount: 0, shortAnswerCount: 0, totalScore: 10 }), { sectionCounts: { partI: 10, partII: 0, partIII: 0 }, requestedQuestionCount: 10, totalScore: 10, difficultyDistribution: { recognition: 30, comprehension: 40, application: 20, highApplication: 10 } });
const safeInvalid = calculateExamStructure({ multipleChoiceCount: "x", trueFalseCount: -2, shortAnswerCount: null, totalScore: "bad" } as unknown as Partial<ExamInput> & Record<string, unknown>);
assert.equal(safeInvalid.requestedQuestionCount, 0);
assert.equal(safeInvalid.totalScore, 10);
assert.ok((safeInvalid.warnings || []).length >= 3);
const mcSkills = ["tập xác định", "đạo hàm", "đồng biến", "nghịch biến", "điểm cực đại", "điểm cực tiểu", "giá trị lớn nhất", "giá trị nhỏ nhất", "tiệm cận đứng", "tiệm cận ngang", "tương giao", "hệ số góc tiếp tuyến"];
const mc = Array.from({ length: 12 }, (_, index) => ({ ...question(index), stem: `Câu hàm số số ${index + 1}: xác định ${mcSkills[index]} cho dữ kiện riêng của bài.`, correctAnswer: ["A", "B", "C", "D"][index % 4] }));
const tfSkills = ["đơn điệu của đa thức bậc ba", "tiệm cận của hàm phân thức", "cực trị từ bảng biến thiên", "tương giao giữa đồ thị và đường thẳng"];
const tf = Array.from({ length: 4 }, (_, index) => ({ id: `tf${index}`, stem: `Xét các khẳng định về ${tfSkills[index]}.`, statements: [0, 1, 2, 3].map((item) => ({ text: `Khẳng định ${item + 1} liên quan đến ${tfSkills[index]}.`, answer: item % 2 === 0 })), answer: `a Đúng; b Sai; c Đúng; d Sai ${index}`, explanation: `Phân tích ${tfSkills[index]} bằng công cụ phù hợp.`, score: 1, difficulty: "Thông hiểu", topic: "hàm số" }));
const shortSkills = ["Tính f(2) với hàm số đã cho", "Tính giá trị cực đại của hàm số", "Tìm số đường tiệm cận", "Tìm số nghiệm của phương trình", "Tính tổng hoành độ các giao điểm", "Tính hệ số góc tiếp tuyến"];
const short = Array.from({ length: 6 }, (_, index) => ({ id: `sa${index}`, stem: `${shortSkills[index]}.`, answer: `${index + 1}`, explanation: `Thực hiện phép tính và thu được kết quả ${index + 1}.`, score: 0.5, difficulty: "Vận dụng", topic: "hàm số" }));
const fullRaw = JSON.stringify({ metadata: { title: "Đề THPTQG", subject: "Toán", grade: "12" }, sections: [{ type: "multiple_choice", questions: mc }, { type: "true_false", questions: tf }, { type: "short_answer", questions: short }], teacherOnly: { scoringGuide: "Đáp án đủ 22 câu." } });
const fullParsed = normalizeAIExamOutput(fullRaw, thptInput);
assert.equal(fullParsed.ok, true);
if (fullParsed.ok) {
  const audit = sanitizeExamStructure(fullParsed.structuredExam, thptInput as ExamInput & Record<string, unknown>);
  assert.deepEqual(audit.generated, { partI: 12, partII: 4, partIII: 6 });
  assert.equal(audit.finalCount, 22);
  assert.equal(audit.complete, true);
  assert.equal(audit.exam.teacherOnly.scoringGuide.split("\n").length, 22);
  assert.match(audit.exam.parts.find((part) => part.type === "multiple_choice")?.title || "", /CÂU 12/);
  assert.match(audit.exam.parts.find((part) => part.type === "true_false")?.title || "", /CÂU 4/);
  assert.match(audit.exam.parts.find((part) => part.type === "short_answer")?.title || "", /CÂU 6/);
  const finalMc = audit.exam.parts.find((part) => part.type === "multiple_choice")?.questions || [];
  assert.deepEqual(Object.fromEntries(["A", "B", "C", "D"].map((letter) => [letter, finalMc.filter((question) => question.answer === letter).length])), { A: 3, B: 3, C: 3, D: 3 });
  const finalTf = audit.exam.parts.find((part) => part.type === "true_false")?.questions || [];
  assert.equal(new Set(finalTf.map((question) => question.trueFalseItems?.map((item) => item.answer ? "Đ" : "S").join(""))).size, 4);
  assert.equal(finalTf.flatMap((question) => question.trueFalseItems || []).filter((item) => item.answer).length, 8);
  const finalShort = audit.exam.parts.find((part) => part.type === "short_answer")?.questions || [];
  assert.ok(finalShort.every((question) => validateShortAnswerNumeric(question).valid));
  assert.ok(audit.exam.parts.flatMap((part) => part.questions).every((question) => validateVisualDependency(question).valid));
}
const tfSectionInput = buildSectionOnlyInput(thptInput as unknown as Record<string, unknown>, "true_false", 4, []) as unknown as ExamInput;
const tfWithoutTopAnswer = tf.map(({ answer, ...item }) => { assert.ok(answer); return item; });
const parsedTfArray = normalizeAIExamOutput(JSON.stringify(tfWithoutTopAnswer), tfSectionInput);
assert.equal(parsedTfArray.ok, true, "Parser phải suy ra đáp án Đúng/Sai từ bốn mệnh đề");
if (parsedTfArray.ok) assert.equal(parsedTfArray.structuredExam.parts.find((part) => part.type === "true_false")?.questions.length, 4);
const shortSectionInput = buildSectionOnlyInput(thptInput as unknown as Record<string, unknown>, "short_answer", 6, []) as unknown as ExamInput;
const parsedShortArray = normalizeAIExamOutput(JSON.stringify(short.map(({ answer, ...item }) => ({ ...item, shortAnswer: answer }))), shortSectionInput);
assert.equal(parsedShortArray.ok, true, "Parser phải nhận shortAnswer làm đáp án PHẦN III");
if (parsedShortArray.ok) assert.equal(parsedShortArray.structuredExam.parts.find((part) => part.type === "short_answer")?.questions.length, 6);
if (fullParsed.ok) {
  const byType = Object.fromEntries(fullParsed.structuredExam.parts.map((part) => [part.type, part.questions]));
  const assembled = assembleSectionedExam(thptInput as unknown as Record<string, unknown>, byType);
  assert.deepEqual(sectionCounts(assembled), { partI: 12, partII: 4, partIII: 6 });
  assert.equal(assembled.parts.flatMap((part) => part.questions).length, 22);
}
assert.equal(minimumUsableExamCount(22), 18);
assert.equal(isUsableExamCount(22, 1), false, "Không được hiển thị đề 1/22 như kết quả sử dụng được");
assert.equal(isUsableExamCount(22, 18), true);
const missingPartIInput = buildSectionOnlyInput(thptInput as unknown as Record<string, unknown>, "multiple_choice", 10, mc.slice(0, 2).map((item) => item.stem));
assert.deepEqual([missingPartIInput.multipleChoiceCount, missingPartIInput.trueFalseCount, missingPartIInput.shortAnswerCount], [10, 0, 0]);
assert.match(buildExamSectionPrompt(thptInput as unknown as Record<string, unknown>, "multiple_choice", 10, mc.slice(0, 2).map((item) => item.stem)), /Tạo đúng 10 câu/);
assert.match(buildExamSectionPrompt(thptInput as unknown as Record<string, unknown>, "true_false", 4, []), /Câu 2 \[Sai, Đúng, Đúng, Sai\]/);
assert.match(buildExamSectionPrompt(thptInput as unknown as Record<string, unknown>, "short_answer", 6, []), /shortAnswer bắt buộc là duy nhất một số/);
const incompleteRaw = JSON.stringify({ metadata: { title: "Thiếu", subject: "Toán", grade: "12" }, sections: [{ type: "multiple_choice", questions: mc.slice(0, 2) }, { type: "true_false", questions: tf.slice(0, 2) }], teacherOnly: { scoringGuide: "Đáp án tạm." } });
const incomplete = normalizeAIExamOutput(incompleteRaw, thptInput);
assert.equal(incomplete.ok, true);
if (incomplete.ok) assert.deepEqual(sanitizeExamStructure(incomplete.structuredExam, thptInput as ExamInput & Record<string, unknown>).missing, { partI: 10, partII: 2, partIII: 6 });
const repeatedExam = fullParsed.ok ? { ...fullParsed.structuredExam, parts: fullParsed.structuredExam.parts.map((part) => part.type === "multiple_choice" ? { ...part, questions: part.questions.map((item) => ({ ...item, stem: "Hàm số y=x^3-3x đồng biến trên khoảng nào?" })) } : part) } : null;
if (repeatedExam) assert.ok(sanitizeExamStructure(repeatedExam, thptInput as ExamInput & Record<string, unknown>).duplicateRemovedCount >= 11);

const mathContext = createGenerationRequestContext({ subject: "Toán", grade: "12", topic: "hàm số", questionType: "Trắc nghiệm" }, "exam");
assert.equal(validateTopicItem(mathContext, { content: "Hàm số y=x^3-3x đồng biến trên khoảng nào?", options: { A: "(-∞;-1)", B: "(-1;1)", C: "(1;+∞)", D: "R" }, answer: "A", explanation: "Xét đạo hàm.", topic: "hàm số", subject: "Toán", grade: "12" }).valid, true);
assert.equal(validateTopicItem(mathContext, { content: "Cho y=x^3-2x+1. Chọn kết quả đúng.", options: { A: "1", B: "2", C: "3", D: "4" }, answer: "A", explanation: "Biến đổi biểu thức đã cho.", topic: "hàm số", subject: "Toán", grade: "12" }).valid, true);
const thermalContext = createGenerationRequestContext({ subject: "Vật lý", grade: "10", topic: "nhiệt học", questionType: "Trắc nghiệm" }, "exam");
assert.equal(validateTopicItem(thermalContext, { content: "Một vật nhận nhiệt lượng 8400 J. Đại lượng nào quyết định độ tăng nhiệt độ?", options: { A: "Khối lượng và nhiệt dung riêng", B: "Điện trở", C: "Từ thông", D: "Tiêu cự" }, answer: "A", explanation: "Áp dụng Q=mcΔt.", topic: "nhiệt học", subject: "Vật lí", grade: "10" }).valid, true);
const unknownContext = createGenerationRequestContext({ subject: "Vật lí", grade: "10", topic: "chuyển pha nâng cao", questionType: "Trắc nghiệm" }, "exam");
assert.equal(validateTopicItem(unknownContext, { content: "Trong quá trình nóng chảy, nhiệt độ của chất kết tinh thay đổi thế nào?", options: { A: "Không đổi", B: "Tăng", C: "Giảm", D: "Bằng 0" }, answer: "A", explanation: "Nhiệt cung cấp dùng cho chuyển pha.", topic: "chuyển pha nâng cao", subject: "Vật lí", grade: "10" }).valid, true);
console.log("Exam structure: parser từng phần, lắp ráp 12/4/6 = 22, ngưỡng 18/22, missing 10/2/6, chống trùng và chủ đề đều đạt.");
