import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import { Sidebar } from "@/components/Sidebar";

const flow = ["Vào Dữ liệu demo và nạp dữ liệu mẫu.", "Vào Cài đặt, nhập thông tin trường và giáo viên.", "Tạo thử một đề kiểm tra.", "Xuất Word và mở file để kiểm tra.", "Thử nhận xét học sinh hàng loạt.", "Mở lại tài liệu trong Lịch sử.", "Gửi góp ý về quy trình và file Word."];

export default function TesterGuidePage() {
  return <div className="min-h-screen md:flex"><Sidebar /><main className="flex-1 p-4 sm:p-5 md:p-8"><PageHeader title="Hướng dẫn test Soạn Lab" description="Hướng dẫn ngắn dành cho giáo viên tham gia thử nghiệm riêng." /><section className="card max-w-4xl p-5 sm:p-6"><div className="rounded-md border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-800">Đây là bản demo. Thầy cô chỉ cần thử 3-5 công cụ, tập trung vào độ dễ dùng, quy trình và file Word. Chưa nên đánh giá độ chính xác nội dung vì AI thật chưa được bật.</div><h2 className="mt-6 text-xl font-bold text-ink">Luồng test gợi ý</h2><ol className="mt-4 space-y-3">{flow.map((item, index) => <li key={item} className="flex gap-3 text-sm leading-6 text-muted"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded bg-blue-50 font-bold text-brand">{index + 1}</span>{item}</li>)}</ol><p className="mt-6 text-sm leading-6 text-muted">Nếu gặp lỗi, hãy dùng trang Góp ý và ghi rõ công cụ, thao tác vừa thực hiện và kết quả mong muốn.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/demo-data" className="btn-secondary">Nạp dữ liệu demo</Link><Link href="/dashboard" className="btn-primary">Bắt đầu test</Link><Link href="/feedback" className="btn-secondary">Gửi góp ý</Link><Link href="/known-issues" className="btn-secondary">Xem giới hạn hiện tại</Link></div></section></main></div>;
}
